### ISSUE TITLE
Does ESP32 using esp-idf V5.0.1 supports ATECC608B secure element using esp-cryptoauthlib ? (IDFGH-9726)

### ISSUE THREAD

**Issue by LumbirBwut** [espressif/esp-idf#11061]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.1

### Operating System used.

macOS

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

While in esp-idf V5.0.1, code should correctly compile with esp-cryptoauthlib.

### What is the actual behavior?

While in esp-idf V5.0.1, code doesn't correctly compile with esp-cryptoauthlib.

### Steps to reproduce.

My code was functionnal in esp-idf V4.3 meaning that I could use my ATECC608B secure element trhough esp-cryptoauthlib.
Unfortunatly, when I try to merge with the most recent version of esp-idf, it didn't work anymore and didn't succeed to compile.
Here are the error message (inside esp-idf/components/mbedtls/mbedtls/include/mbedtls/check_config.h) :
```bash
error: #error "MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation"
  154 | #error "MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation"
```
Which is triggered because of this line (check_config.h):
```c++
#if defined(MBEDTLS_ECP_RESTARTABLE)           && \
    ( defined(MBEDTLS_USE_PSA_CRYPTO)          || \
      defined(MBEDTLS_ECDH_COMPUTE_SHARED_ALT) || \
      defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)     || \
      defined(MBEDTLS_ECDSA_SIGN_ALT)          || \
      defined(MBEDTLS_ECDSA_VERIFY_ALT)        || \
      defined(MBEDTLS_ECDSA_GENKEY_ALT)        || \
      defined(MBEDTLS_ECP_INTERNAL_ALT)        || \
      defined(MBEDTLS_ECP_ALT) )
#error "MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation"
#endif
```
This line does trigger because both `MBEDTLS_ECP_RESTARTABLE` and `MBEDTLS_ECDSA_SIGN_ALT` and `MBEDTLS_ECDSA_VERIFY_ALT` are defined.
- `MBEDTLS_ECDSA_SIGN_ALT` and `MBEDTLS_ECDSA_VERIFY_ALT` are defined because of `use_secure_element` inside esp tls configuration
- `MBEDTLS_ECP_RESTARTABLE` is defined because of `BT_NIMBLE_CRYPTO_STACK_MBEDTLS` inside menuconfig which force it to be True

I did try to unset both `BT_NIMBLE_CRYPTO_STACK_MBEDTLS` and `MBEDTLS_ECP_RESTARTABLE` in my menuconfig BUT it still leads me to new error which is:
```bash
In function 'atcac_sw_sha1_finish':
cc1: error: 'atcac_sw_sha2_256_finish' accessing 32 bytes in a region of size 20 [-Werror=stringop-overflow=]
cc1: note: referencing argument 2 of type 'uint8_t *' {aka 'unsigned char *'}
esp-cryptoauthlib/cryptoauthlib/lib/mbedtls/atca_mbedtls_wrap.c:419:5: note: in a call to function 'atcac_sw_sha2_256_finish'
  419 | int atcac_sw_sha2_256_finish(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
```

I do think it's related to this:
```c++
#define ATCA_SHA1_DIGEST_SIZE       (20)
#define ATCA_SHA2_256_DIGEST_SIZE   (32)
```
but got no idea on how to solve this.

Is esp-cryptoauthlib  not actually functionnal with esp-idf v5.0.1 ?

Thanks in advance 👍

**Comment by LumbirBwut** [comment]
After some investigations here I my results.
I used the example provided inside esp-idf concerning the cryptochip (`examples/peripherals/secure_element/atecc608_ecdsa`) and just modified the `sdkconfig` with the following:
```Makefile
#
# Compiler options
#
# CONFIG_COMPILER_OPTIMIZATION_DEFAULT is not set
CONFIG_COMPILER_OPTIMIZATION_SIZE=y

```

This lead me to this error:
```c++
peripherals/secure_element/atecc608_ecdsa/managed_components/espressif__esp-cryptoauthlib/cryptoauthlib/lib/calib/calib_sign.c:241:17: error: argument 1 null where non-null expected [-Werror=nonnull]
  241 |                 memcpy(signature, &packet.data[ATCA_RSP_DATA_IDX], ATCA_SIG_SIZE);
```
This can be easily corrected I think with the following:
```c++
// -> Line 237 should be:
if (NULL != signature) {
```

Unfortunately, rebuilding the whole lead me to this error I previoulsy had:
```c++
peripherals/secure_element/atecc608_ecdsa/managed_components/espressif__esp-cryptoauthlib/cryptoauthlib/lib/mbedtls/atca_mbedtls_wrap.c: In function 'atcac_sw_sha1_finish':
cc1: error: 'atcac_sw_sha2_256_finish' accessing 32 bytes in a region of size 20 [-Werror=stringop-overflow=]
cc1: note: referencing argument 2 of type 'uint8_t *' {aka 'unsigned char *'}
esp-idf/examples/peripherals/secure_element/atecc608_ecdsa/managed_components/espressif__esp-cryptoauthlib/cryptoauthlib/lib/mbedtls/atca_mbedtls_wrap.c:419:5: note: in a call to function 'atcac_sw_sha2_256_finish'
  419 | int atcac_sw_sha2_256_finish(
```

No clue on how to solve this though.
Thanks for your previous fast answer, hope we'll figure the whole out 👍

**Comment by AdityaHPatwardhan** [comment]
Hi @LumbirBwut  Sorry for the delayed reply.
It seems there are two different issues here -
1) Issue related to the line `if (NULL != signature) {` as you have noted. : This issue is fixed in the [current latest tag](https://github.com/MicrochipTech/cryptoauthlib/tree/v3.5.1) for the cryptoauthlib repository.
We will soon release a new version update for the esp-cryptoauthlib component to sync esp-cryptoauthlib to v3.5.1 of upstream cryptoauthlib. That should fix the issue

2) When `CONFIG_COMPILER_OPITIMIZATION_SIZE` or `CONFIG_COMPILER_OPTIMIZATION_PERF` is enabled, it seems compiler is throwing warnings due to aggressive optimization techniques, we can suppress the warning using `Wno-stringop-overflow` in this case.
This should be fixed in the upcoming version of esp-cryptoauthlib.

Thanks for raising the issue, I will update here once the latest version is available [here](https://components.espressif.com/components/espressif/esp-cryptoauthlib)

**Comment by AdityaHPatwardhan** [comment]
Hi @LumbirBwut We have released a new version for the esp-cryptoauthlib repository. `v3.5.1~1`
Please use the same version, that should fix both of the issues mentioned above.
I am closing this issue,
Feel free to re-open if you still find your problem unsolved.
Thanks,
Aditya

**Comment by JonathanWitthoeft** [comment]
@AdityaHPatwardhan I am having a very similar issue. I have  v3.5.1~1, 
I have `CONFIG_COMPILER_OPTIMIZATION_DEFAULT=y` and I am still getting this message:
```
atca_mbedtls_wrap.c: In function 'atcac_sw_sha1_finish':
cc1: error: 'atcac_sw_sha2_256_finish' accessing 32 bytes in a region of size 20 [-Werror=stringop-overflow=]
cc1: note: referencing argument 2 of type 'uint8_t *' {aka 'unsigned char *'}
atca_mbedtls_wrap.c:419:5: note: in a call to function 'atcac_sw_sha2_256_finish'
  419 | int atcac_sw_sha2_256_finish(
  ```

**Comment by AdityaHPatwardhan** [comment]
Hi @JonathanWitthoeft Can you share your `sdkconfig` file?
And the IDF version?

**Comment by JonathanWitthoeft** [comment]
@AdityaHPatwardhan As I am also using the matter sdk, I opened a new issue here with the full reproducible procedure:
https://github.com/espressif/esp-matter/issues/344

**Comment by dragomat** [comment]
Hi all,

I am having the same issue in the first comment of this thread. 
My code works with esp-idf V4.4.4 and I could use my ATECC608A secure element through esp-cryptoauthlib.

Now I am porting the code to esp-idf 5.0 (with latest version of esp-cryptoauthlib) and I am getting the same error as above:

`#error "MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation"`

which apparently can be solved by disabling the `BT_NIMBLE_CRYPTO_STACK_MBEDTLS` and `MBEDTLS_ECP_RESTARTABLE`, but is this the correct way to solve it, considering that it was working before with the same exact configuration? Are we sacrificing something fundamental by using TinyCrypt instead of MbedTLS with NIMBLE?

On a related note: is esp-cryptoauhtlib-utility compatible also with esp32-c6? It is not mentioned by the docs.

Thanks for any help you can give.
