### ISSUE TITLE
Wifi connection can be successfully connected using the wrong password (IDFGH-14968)

### ISSUE THREAD

**Issue by Z-KY** [espressif/esp-idf#15669]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.5-dev-2715-ga45d713b03-dirty

### Espressif SoC revision.

ESP32-C5 (revision v0.1)

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

Use the correct wifi information to connect to the network, call esp_wifi_disconnect, esp_wifi_stop, and then use the wrong wifi password to connect. The device should fail to connect to the network.

### What is the actual behavior?

Connect to the network with the correct WiFi information, call esp_wifi_disconnect, esp_wifi_stop, and then connect with the wrong WiFi password. The device is also successfully connected to the network.

### Steps to reproduce.

1. Create a station routine
2. In advance the code in wifi_init_sta about wifi initialization part and only execute it once in the program

![Image](https://github.com/user-attachments/assets/f5ed761f-6eac-4b1a-b30d-a68f701844e5)

3. Call wifi_init_sta twice, use the correct wifi information the first time, use the wrong wifi password the second time

![Image](https://github.com/user-attachments/assets/986d2635-8b51-488d-8aa2-ffe4343a28c4)

![Image](https://github.com/user-attachments/assets/d5d3b7cb-a211-4c44-9ef3-70077114e34e)

4. Compile the code and burn it to run

### Debug Logs.

```plain
I (23) boot: ESP-IDF v5.5-dev-2715-ga45d713b03 2nd stage bootloader
I (23) boot: compile time Mar 28 2025 10:24:19
I (24) boot: chip revision: v0.1
I (25) boot: efuse block revision: v0.1
I (29) boot.esp32c5: SPI Speed      : 80MHz
I (32) boot.esp32c5: SPI Mode       : DIO
I (36) boot.esp32c5: SPI Flash Size : 2MB
I (40) boot: Enabling RNG early entropy source...
I (44) boot: Partition Table:
I (47) boot: ## Label            Usage          Type ST Offset   Length
I (53) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (60) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (66) boot:  2 factory          factory app      00 00 00010000 00100000
I (73) boot: End of partition table
I (76) esp_image: segment 0: paddr=00010020 vaddr=42090020 size=1a564h (107876) map
I (103) esp_image: segment 1: paddr=0002a58c vaddr=40800000 size=05a8ch ( 23180) load
I (108) esp_image: segment 2: paddr=00030020 vaddr=42000020 size=881b8h (557496) map
I (204) esp_image: segment 3: paddr=000b81e0 vaddr=40805a8c size=0daf0h ( 56048) load
I (216) esp_image: segment 4: paddr=000c5cd8 vaddr=40813580 size=03d6ch ( 15724) load
I (224) boot: Loaded app from partition at offset 0x10000
I (225) boot: Disabling RNG early entropy source...
I (234) cpu_start: Unicore app
W (243) clk: esp_perip_clk_init() has not been implemented yet
I (248) cpu_start: Pro cpu start user code
I (249) cpu_start: cpu freq: 240000000 Hz
I (249) app_init: Application information:
I (249) app_init: Project name:     wifi_station
I (253) app_init: App version:      1
I (256) app_init: Compile time:     Mar 28 2025 10:23:45
I (261) app_init: ELF file SHA256:  6356ce0f1...
I (266) app_init: ESP-IDF:          v5.5-dev-2715-ga45d713b03
I (271) efuse_init: Min chip rev:     v0.0
I (275) efuse_init: Max chip rev:     v0.99 
I (279) efuse_init: Chip rev:         v0.1
I (283) heap_init: Initializing. RAM available for dynamic allocation:
I (289) heap_init: At 4081CB40 len 0003FE60 (255 KiB): RAM
I (294) heap_init: At 4085C9A0 len 00002B60 (10 KiB): RAM
I (299) heap_init: At 50000000 len 00003FE8 (15 KiB): RTCRAM
I (305) spi_flash: detected chip: generic
I (308) spi_flash: flash io: dio
W (311) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (324) sleep_gpio: Configure to isolate all GPIO pins in sleep state
I (330) sleep_gpio: Enable automatic switching of GPIO sleep configuration
I (336) coexist: coex firmware version: e727207
I (355) coexist: coexist rom version 78e5c6e42
I (355) main_task: Started on CPU0
I (355) main_task: Calling app_main()
I (365) wifi station: ESP_WIFI_MODE_STA
I (365) pp: pp rom version: db0b5b108
I (365) net80211: net80211 rom version: db0b5b108
I (375) wifi:wifi driver task: 40823efc, prio:23, stack:6656, core=0
I (375) wifi:wifi firmware version: 3c3dba1615
I (375) wifi:wifi certification version: v7.0
I (375) wifi:config NVS flash: enabled
I (375) wifi:config nano formatting: disabled
I (385) wifi:mac_version:HAL_MAC_ESP32AX_752MP,ut_version:N, band mode:0x3
I (385) wifi:Init data frame dynamic rx buffer num: 32
I (395) wifi:Init static rx mgmt buffer num: 5
I (395) wifi:Init management short buffer num: 32
I (405) wifi:Init dynamic tx buffer num: 32
I (405) wifi:Init static tx FG buffer num: 2
I (415) wifi:Init static rx buffer size: 1700 (rxctrl:64, csi:512)
I (415) wifi:Init static rx buffer num: 10
I (425) wifi:Init dynamic rx buffer num: 32
I (425) wifi_init: rx ba win: 6
I (425) wifi_init: accept mbox: 6
I (435) wifi_init: tcpip mbox: 32
I (435) wifi_init: udp mbox: 6
I (435) wifi_init: tcp mbox: 6
I (435) wifi_init: tcp tx win: 5760
I (445) wifi_init: tcp rx win: 5760
I (445) wifi_init: tcp mss: 1440
I (445) wifi_init: WiFi IRAM OP enabled
I (455) wifi_init: WiFi RX IRAM OP enabled
I (455) wifi_init: WiFi SLP IRAM OP enabled
first connect
I (475) phy_init: phy_version 103,48ac5755,Feb 22 2025,16:10:11
W (1185) wifi:WDEV_RXCCK_DELAY:952
W (1185) wifi:WDEV_RXOFDM_DELAY:240
W (1185) wifi:WDEV_RX_11G_OFDM_DELAY:234
W (1185) wifi:WDEV_TXCCK_DELAY:630
W (1185) wifi:WDEV_TXOFDM_DELAY:94
W (1195) wifi:ACK_TAB0   :0x   90a0b, QAM16:0x9 (24Mbps), QPSK:0xa (12Mbps), BPSK:0xb (6Mbps)
W (1205) wifi:CTS_TAB0   :0x   90a0b, QAM16:0x9 (24Mbps), QPSK:0xa (12Mbps), BPSK:0xb (6Mbps)
W (1205) wifi:WDEVBEAMFORMCONF:0x21d7120, HE_BF_RPT_RA_SET_OPT:1
W (1215) wifi:(agc)0x600a7128:0xd21f0c20, min.avgNF:0xce->0xd2(dB), RCalCount:0x1f0, min.RRssi:0xc20(-62.00)
W (1225) wifi:MODEM_SYSCON_WIFI_BB_CFG_REG(0x600a9c18):0x10003802
W (1235) wifi:(phy)rate:0x0(  LP-1Mbps), pwr:20, txing:20
W (1235) wifi:(phy)rate:0x1(  LP-2Mbps), pwr:20, txing:20
W (1245) wifi:(phy)rate:0x2(LP-5.5Mbps), pwr:20, txing:20
W (1245) wifi:(phy)rate:0x3( LP-11Mbps), pwr:20, txing:20
W (1255) wifi:(phy)rate:0x5(  SP-2Mbps), pwr:20, txing:20
W (1255) wifi:(phy)rate:0x6(SP-5.5Mbps), pwr:20, txing:20
W (1265) wifi:(phy)rate:0x7( SP-11Mbps), pwr:20, txing:20
W (1265) wifi:(phy)rate:0x8(    48Mbps), pwr:18, txing:18
W (1275) wifi:(phy)rate:0x9(    24Mbps), pwr:19, txing:19
W (1275) wifi:(phy)rate:0xa(    12Mbps), pwr:19, txing:19
W (1285) wifi:(phy)rate:0xb(     6Mbps), pwr:19, txing:19
W (1285) wifi:(phy)rate:0xc(    54Mbps), pwr:18, txing:18
W (1295) wifi:(phy)rate:0xd(    36Mbps), pwr:19, txing:19
W (1295) wifi:(phy)rate:0xe(    18Mbps), pwr:19, txing:19
W (1305) wifi:(phy)rate:0xf(     9Mbps), pwr:19, txing:19
W (1305) wifi:(phy)rate:0x10, mcs:0x0, pwr(bw20:19, bw40:19), txing:19
W (1315) wifi:(phy)rate:0x11, mcs:0x1, pwr(bw20:19, bw40:19), txing:19
W (1315) wifi:(phy)rate:0x12, mcs:0x2, pwr(bw20:18, bw40:18), txing:18
W (1325) wifi:(phy)rate:0x13, mcs:0x3, pwr(bw20:18, bw40:18), txing:18
W (1335) wifi:(phy)rate:0x14, mcs:0x4, pwr(bw20:17, bw40:17), txing:17
W (1335) wifi:(phy)rate:0x15, mcs:0x5, pwr(bw20:17, bw40:17), txing:17
W (1345) wifi:(phy)rate:0x16, mcs:0x6, pwr(bw20:17, bw40:16), txing:17
W (1355) wifi:(phy)rate:0x17, mcs:0x7, pwr(bw20:17, bw40:16), txing:17
W (1355) wifi:(phy)rate:0x18, mcs:0x8, pwr(bw20:16, bw40:0), txing:16
W (1365) wifi:(phy)rate:0x19, mcs:0x9, pwr(bw20:15, bw40:0), txing:15
W (1365) wifi:(hal)co_hosted_bss:0, max_indicator:0, bitmask:0xff, mBSSIDsEnable:0
I (1375) wifi:11ax coex: WDEVAX_PTI0(0x55777555), WDEVAX_PTI1(0x00003377).

I (1385) wifi:mode : sta (60:55:f9:fa:c9:b0)
I (1385) wifi:enable tsf
W (1385) wifi:(BB)enable busy check(0x18), disable idle check(0xaa)
I (1395) wifi station: wifi_init_sta finished.
W (1435) wifi:(cap)capinfo:0x11, Spectrum Management:0 
W (1435) wifi:(vht)vhtcap:0x338a59b2, sgi_rx(80mhz:1, 160/80+80mhz:0), stbc(tx:1, rx:1), ldpc_rx:1, bfmer(su:1, mu:1, nsts:2)
W (1445) wifi:(vht)max.RxMPDULen:2(11454), max.RxAMPDULenExponent:7, max.RxAMPDUpre-EOFpaddingBytes:1048575(0xfffff)
W (1455) wifi:(vht)rx(mcs:0xfffa, highest:0x0, highest_lgi_rate:0), tx(mcs:0xfffa, highest:0x2000, highest_lgi_rate:0), max_rate:144
W (1465) wifi:(vht)bandwidth:1, chan_center_frq_seg0:42, chan_center_frq_seg1:0
W (1475) wifi:(ht)primary_chann:36, ht2ndchan:1
W (1475) wifi:(vht)BSS bandwidth:80MHz
I (1485) wifi:(he)max.RxAMPDULenExponentExtension:3, max.RxAMPDUpre-EOFpaddingBytes:8388607(0x7fffff)
I (1495) wifi:(mac)omc_ul_mu_data_disable_rx:1
I (1495) wifi:(phy)ppe_thresholds_present:1, nominal_packet_padding:0
I (1505) wifi:(phy)dcm tx(constellation:2, nss:0), dcm rx(constellation:2, nss:0)
I (1505) wifi:(phy)rx_mcs_map:0xfffa, tx_mcs_map:0xfffa, stbc_tx:1, bfmer(su:1, mu:1), ldpc:1, max_rate:172
I (1515) wifi:(phy)nsts:2, ru_index_bitmap:0xf(242:1, 484:1, 996:1, 2*996:1)
I (1525) wifi:(phy)threshold_bits:48, nsts_num:2, ru_num:4, he_cap->len:29, ppe_threshold_len:7(6,11,4)
I (1535) wifi:(ppe)RU242, NSTS0, PPE16:0, PPE8:7, nominal_packet_padding:2
W (1535) wifi:(hal)co_hosted_bss:0, max_indicator:0, bitmask:0xff, mBSSIDsEnable:0
I (1545) wifi:(opr)len:7, TWT Required:0, VHT Opr Info Present:0, 6GHz Opr Info Present:0, Co-Hosted BSS:0(max_indicator:0), Basic MCS and NSS:0xfffc
I (1555) wifi:(opr)len:7, Default PE Duration:4, TXOP RTS Threshold:1023(0 us), ER-SU-Disable:0
I (1565) wifi:(opr)len:7, BSS Color:23, disabled:0, Partial BSS Color:0
I (1575) wifi:(spr)len:2, ctrl:0x3, PSR Disallowed:1, Non-SRG OBSS PD SR Disallowed:1
I (1585) wifi:(spr)len:2, ctrl:0x3, Non-SRG Offset Present:0, SRG Info Present:0
I (1595) wifi:new:<36,0>, old:<1,0>, ap:<255,255>, sta:<36,0>, prof:1, snd_ch_cfg:0x10
I (1595) wifi:(connect)dot11_authmode:0x3, pairwise_cipher:0x3, group_cipher:0x3
I (1605) wifi:state: init -> auth (0xb0)
I (1855) wifi:state: auth -> assoc (0x0)
I (1875) wifi:(assoc)RESP, Extended Capabilities length:10, operating_mode_notification:1
I (1875) wifi:(assoc)RESP, Extended Capabilities, MBSSID:0, TWT Responder:1, OBSS Narrow Bandwidth RU In OFDMA Tolerance:0
I (1885) wifi:(he)max.RxAMPDULenExponentExtension:3, max.RxAMPDUpre-EOFpaddingBytes:8388607(0x7fffff)
I (1895) wifi:(mac)omc_ul_mu_data_disable_rx:1
I (1895) wifi:(phy)ppe_thresholds_present:1, nominal_packet_padding:0
I (1905) wifi:(phy)dcm tx(constellation:2, nss:0), dcm rx(constellation:2, nss:0)
I (1915) wifi:(phy)rx_mcs_map:0xfffa, tx_mcs_map:0xfffa, stbc_tx:1, bfmer(su:1, mu:1), ldpc:1, max_rate:172
I (1925) wifi:(phy)nsts:2, ru_index_bitmap:0xf(242:1, 484:1, 996:1, 2*996:1)
I (1925) wifi:(phy)threshold_bits:48, nsts_num:2, ru_num:4, he_cap->len:29, ppe_threshold_len:7(6,11,4)
I (1935) wifi:(ppe)RU242, NSTS0, PPE16:0, PPE8:7, nominal_packet_padding:2
W (1945) wifi:(hal)co_hosted_bss:0, max_indicator:0, bitmask:0xff, mBSSIDsEnable:0
I (1955) wifi:(opr)len:7, TWT Required:0, VHT Opr Info Present:0, 6GHz Opr Info Present:0, Co-Hosted BSS:0(max_indicator:0), Basic MCS and NSS:0xfffc
I (1965) wifi:(opr)len:7, Default PE Duration:4, TXOP RTS Threshold:1023(0 us), ER-SU-Disable:0
I (1975) wifi:(opr)len:7, BSS Color:23, disabled:0, Partial BSS Color:0
I (1985) wifi:BSS max idle period:292(1000TU), protected keep alive:FALSE
I (1985) wifi:state: assoc -> run (0x10)
I (1995) wifi:(he)ppe_thresholds_present:1, nominal_packet_padding(rx:0, cfg:2)
I (1995) wifi:(trc)phytype:CBW20-SGI, snr:17, maxRate:172, highestRateIdx:0
W (2005) wifi:(trc)band:5G, phymode:3, highestRateIdx:0, lowestRateIdx:9, dataSchedTableSize:10
I (2015) wifi:(trc)band:5G, rate(L-MCS3, rateIdx:5), ampdu(rate:L-MCS3, schedIdx(5, stop:8)), snr:17, ampduState:wait operational
I (2025) wifi:ifidx:0, rssi:-80, nf:-97, phytype(0x3, CBW20-SGI), phymode(0x7, 11ax), max_rate:172, he:1, vht:1, ht:1
I (2035) wifi:(ht)max.RxAMPDULenExponent:3(65535 bytes), MMSS:4(2 us)
I (2055) wifi:(extcap)mbssid:0, enhanced_mbssid_advertise:0, complete_nontxbssid_profiles:0, twt_responder: 1
I (2065) wifi:connected with AlphaSTU_5G, aid = 2, channel 36, BW20(ABOVE, C0), bssid = ec:e7:c2:97:2f:0b
I (2065) wifi:security: WPA2-PSK, phy:11ax, rssi:-80, cipher(pairwise:0x3, group:0x3), pmf:0, 
I (2085) wifi:pm start, type: 1, twt_start:0

I (2085) wifi:pm start, type:1, aid:0x2, trans-BSSID:ec:e7:c2:97:2f:0b, BSSID[5]:0xb, mbssid(max-indicator:0, index:0), he:1
I (2095) wifi:dp: 1, bi: 102400, li: 3, scale listen interval from 307200 us to 307200 us
I (2095) wifi:set rx beacon pti, rx_bcn_pti: 10, bcn_timeout: 25000, mt_pti: 10, mt_time: 10000
I (2105) wifi:[ADDBA]TX addba request, tid:0, dialogtoken:1, bufsize:32, A-MSDU:0(not supported), policy:1(IMR), ssn:0(0x0)
I (2115) wifi:[ADDBA]TX addba request, tid:7, dialogtoken:2, bufsize:32, A-MSDU:0(not supported), policy:1(IMR), ssn:0(0x20)
I (2125) wifi:[ADDBA]TX addba request, tid:5, dialogtoken:3, bufsize:32, A-MSDU:0(not supported), policy:1(IMR), ssn:0(0x0)
I (2145) wifi:[ADDBA]RX addba response, status:0, tid:0/tb:1(0xa1), bufsize:32, batimeout:0, txa_wnd:32
I (2145) wifi:[ADDBA]RX addba response, status:0, tid:7/tb:1(0xa1), bufsize:32, batimeout:0, txa_wnd:32
I (2155) wifi:[ADDBA]RX addba response, status:0, tid:5/tb:1(0xa1), bufsize:32, batimeout:0, txa_wnd:32
I (2165) wifi:dp: 2, bi: 102400, li: 4, scale listen interval from 307200 us to 409600 us
I (2175) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (3185) esp_netif_handlers: sta ip: 192.168.1.221, mask: 255.255.255.0, gw: 192.168.1.1
I (3185) wifi station: got ip:192.168.1.221
I (3185) wifi station: connected to ap SSID:AlphaSTU_5G password:AoLoumKfYaRz
W (7325) wifi:<ba-add>idx:0, ifx:0, tid:0, TAHI:0x1000b2f, TALO:0x97c2e7ec, (ssn:1, win:64, cur_ssn:1), CONF:0xc0000001
second connect
I (13185) wifi:state: run -> init (0x0)
I (13195) wifi:pm stop, total sleep time: 10158873 us / 11099582 us

I (13195) wifi:<ba-del>idx:0, tid:0
I (13195) wifi:new:<36,0>, old:<36,0>, ap:<255,255>, sta:<36,0>, prof:1, snd_ch_cfg:0x0
I (13195) wifi station: retry to connect to the AP
I (13205) wifi station: connect to the AP fail
W (13205) wifi:(itwt)itwt_stop_process!
I (13205) wifi:flush txq
I (13215) wifi:stop sw txq
I (13215) wifi:lmac stop hw txq
W (13235) wifi:WDEV_RXCCK_DELAY:952
W (13235) wifi:WDEV_RXOFDM_DELAY:240
W (13235) wifi:WDEV_RX_11G_OFDM_DELAY:234
W (13235) wifi:WDEV_TXCCK_DELAY:630
W (13235) wifi:WDEV_TXOFDM_DELAY:94
W (13235) wifi:ACK_TAB0   :0x   90a0b, QAM16:0x9 (24Mbps), QPSK:0xa (12Mbps), BPSK:0xb (6Mbps)
W (13245) wifi:CTS_TAB0   :0x   90a0b, QAM16:0x9 (24Mbps), QPSK:0xa (12Mbps), BPSK:0xb (6Mbps)
W (13255) wifi:WDEVBEAMFORMCONF:0x21d7120, HE_BF_RPT_RA_SET_OPT:1
W (13265) wifi:(agc)0x600a7128:0xd217fa7c, min.avgNF:0xce->0xd2(dB), RCalCount:0x17f, min.RRssi:0xa7c(-88.25)
W (13275) wifi:MODEM_SYSCON_WIFI_BB_CFG_REG(0x600a9c18):0x10003802
W (13275) wifi:(phy)rate:0x0(  LP-1Mbps), pwr:20, txing:20
W (13285) wifi:(phy)rate:0x1(  LP-2Mbps), pwr:20, txing:20
W (13285) wifi:(phy)rate:0x2(LP-5.5Mbps), pwr:20, txing:20
W (13295) wifi:(phy)rate:0x3( LP-11Mbps), pwr:20, txing:20
W (13295) wifi:(phy)rate:0x5(  SP-2Mbps), pwr:20, txing:20
W (13305) wifi:(phy)rate:0x6(SP-5.5Mbps), pwr:20, txing:20
W (13305) wifi:(phy)rate:0x7( SP-11Mbps), pwr:20, txing:20
W (13315) wifi:(phy)rate:0x8(    48Mbps), pwr:18, txing:18
W (13315) wifi:(phy)rate:0x9(    24Mbps), pwr:19, txing:19
W (13325) wifi:(phy)rate:0xa(    12Mbps), pwr:19, txing:19
W (13325) wifi:(phy)rate:0xb(     6Mbps), pwr:19, txing:19
W (13335) wifi:(phy)rate:0xc(    54Mbps), pwr:18, txing:18
W (13335) wifi:(phy)rate:0xd(    36Mbps), pwr:19, txing:19
W (13345) wifi:(phy)rate:0xe(    18Mbps), pwr:19, txing:19
W (13345) wifi:(phy)rate:0xf(     9Mbps), pwr:19, txing:19
W (13355) wifi:(phy)rate:0x10, mcs:0x0, pwr(bw20:19, bw40:19), txing:19
W (13365) wifi:(phy)rate:0x11, mcs:0x1, pwr(bw20:19, bw40:19), txing:19
W (13365) wifi:(phy)rate:0x12, mcs:0x2, pwr(bw20:18, bw40:18), txing:18
W (13375) wifi:(phy)rate:0x13, mcs:0x3, pwr(bw20:18, bw40:18), txing:18
W (13375) wifi:(phy)rate:0x14, mcs:0x4, pwr(bw20:17, bw40:17), txing:17
W (13385) wifi:(phy)rate:0x15, mcs:0x5, pwr(bw20:17, bw40:17), txing:17
W (13395) wifi:(phy)rate:0x16, mcs:0x6, pwr(bw20:17, bw40:16), txing:17
W (13395) wifi:(phy)rate:0x17, mcs:0x7, pwr(bw20:17, bw40:16), txing:17
W (13405) wifi:(phy)rate:0x18, mcs:0x8, pwr(bw20:16, bw40:0), txing:16
W (13415) wifi:(phy)rate:0x19, mcs:0x9, pwr(bw20:15, bw40:0), txing:15
W (13415) wifi:(hal)co_hosted_bss:0, max_indicator:0, bitmask:0xff, mBSSIDsEnable:0
I (13425) wifi:11ax coex: WDEVAX_PTI0(0x55777555), WDEVAX_PTI1(0x00003377).

I (13435) wifi:mode : sta (60:55:f9:fa:c9:b0)
I (13435) wifi:enable tsf
W (13435) wifi:(BB)enable busy check(0x18), disable idle check(0xaa)
I (13445) wifi station: wifi_init_sta finished.
I (13445) wifi station: connected to ap SSID:AlphaSTU_5G password:123456789
W (13525) wifi:(vht)vhtcap:0x338a59b2, sgi_rx(80mhz:1, 160/80+80mhz:0), stbc(tx:1, rx:1), ldpc_rx:1, bfmer(su:1, mu:1, nsts:2)
W (13525) wifi:(vht)max.RxMPDULen:2(11454), max.RxAMPDULenExponent:7, max.RxAMPDUpre-EOFpaddingBytes:1048575(0xfffff)
W (13535) wifi:(vht)rx(mcs:0xfffa, highest:0x0, highest_lgi_rate:0), tx(mcs:0xfffa, highest:0x2000, highest_lgi_rate:0), max_rate:144
W (13545) wifi:(vht)bandwidth:1, chan_center_frq_seg0:42, chan_center_frq_seg1:0
W (13555) wifi:(ht)primary_chann:36, ht2ndchan:1
W (13555) wifi:(vht)BSS bandwidth:80MHz
I (13565) wifi:(he)max.RxAMPDULenExponentExtension:3, max.RxAMPDUpre-EOFpaddingBytes:8388607(0x7fffff)
I (13565) wifi:(mac)omc_ul_mu_data_disable_rx:1
I (13575) wifi:(phy)ppe_thresholds_present:1, nominal_packet_padding:0
I (13575) wifi:(phy)dcm tx(constellation:2, nss:0), dcm rx(constellation:2, nss:0)
I (13585) wifi:(phy)rx_mcs_map:0xfffa, tx_mcs_map:0xfffa, stbc_tx:1, bfmer(su:1, mu:1), ldpc:1, max_rate:172
I (13595) wifi:(phy)nsts:2, ru_index_bitmap:0xf(242:1, 484:1, 996:1, 2*996:1)
I (13605) wifi:(phy)threshold_bits:48, nsts_num:2, ru_num:4, he_cap->len:29, ppe_threshold_len:7(6,11,4)
I (13615) wifi:(ppe)RU242, NSTS0, PPE16:0, PPE8:7, nominal_packet_padding:2
W (13615) wifi:(hal)co_hosted_bss:0, max_indicator:0, bitmask:0xff, mBSSIDsEnable:0
I (13625) wifi:(opr)len:7, TWT Required:0, VHT Opr Info Present:0, 6GHz Opr Info Present:0, Co-Hosted BSS:0(max_indicator:0), Basic MCS and NSS:0xfffc
I (13635) wifi:(opr)len:7, Default PE Duration:4, TXOP RTS Threshold:1023(0 us), ER-SU-Disable:0
I (13645) wifi:(opr)len:7, BSS Color:23, disabled:0, Partial BSS Color:0
I (13655) wifi:(spr)len:2, ctrl:0x3, PSR Disallowed:1, Non-SRG OBSS PD SR Disallowed:1
I (13665) wifi:(spr)len:2, ctrl:0x3, Non-SRG Offset Present:0, SRG Info Present:0
I (13675) wifi:new:<36,0>, old:<1,0>, ap:<255,255>, sta:<36,0>, prof:1, snd_ch_cfg:0x10
I (13675) wifi:(connect)dot11_authmode:0x3, pairwise_cipher:0x3, group_cipher:0x3
I (13685) wifi:state: init -> auth (0xb0)
I (13695) wifi:state: auth -> assoc (0x0)
I (13725) wifi:(assoc)RESP, Extended Capabilities length:10, operating_mode_notification:1
I (13725) wifi:(assoc)RESP, Extended Capabilities, MBSSID:0, TWT Responder:1, OBSS Narrow Bandwidth RU In OFDMA Tolerance:0
I (13725) wifi:(he)max.RxAMPDULenExponentExtension:3, max.RxAMPDUpre-EOFpaddingBytes:8388607(0x7fffff)
I (13735) wifi:(mac)omc_ul_mu_data_disable_rx:1
I (13745) wifi:(phy)ppe_thresholds_present:1, nominal_packet_padding:0
I (13745) wifi:(phy)dcm tx(constellation:2, nss:0), dcm rx(constellation:2, nss:0)
I (13755) wifi:(phy)rx_mcs_map:0xfffa, tx_mcs_map:0xfffa, stbc_tx:1, bfmer(su:1, mu:1), ldpc:1, max_rate:172
I (13765) wifi:(phy)nsts:2, ru_index_bitmap:0xf(242:1, 484:1, 996:1, 2*996:1)
I (13775) wifi:(phy)threshold_bits:48, nsts_num:2, ru_num:4, he_cap->len:29, ppe_threshold_len:7(6,11,4)
I (13785) wifi:(ppe)RU242, NSTS0, PPE16:0, PPE8:7, nominal_packet_padding:2
W (13785) wifi:(hal)co_hosted_bss:0, max_indicator:0, bitmask:0xff, mBSSIDsEnable:0
I (13795) wifi:(opr)len:7, TWT Required:0, VHT Opr Info Present:0, 6GHz Opr Info Present:0, Co-Hosted BSS:0(max_indicator:0), Basic MCS and NSS:0xfffc 
I (13805) wifi:(opr)len:7, Default PE Duration:4, TXOP RTS Threshold:1023(0 us), ER-SU-Disable:0
I (13815) wifi:(opr)len:7, BSS Color:23, disabled:0, Partial BSS Color:0
I (13825) wifi:BSS max idle period:292(1000TU), protected keep alive:FALSE
I (13825) wifi:state: assoc -> run (0x10)
I (13835) wifi:(he)ppe_thresholds_present:1, nominal_packet_padding(rx:0, cfg:2)
I (13845) wifi:(trc)phytype:CBW20-SGI, snr:16, maxRate:172, highestRateIdx:0
W (13845) wifi:(trc)band:5G, phymode:3, highestRateIdx:0, lowestRateIdx:9, dataSchedTableSize:10
I (13855) wifi:(trc)band:5G, rate(L-MCS2, rateIdx:6), ampdu(rate:L-MCS2, schedIdx(6, stop:8)), snr:16, ampduState:wait operational
I (13865) wifi:ifidx:0, rssi:-81, nf:-97, phytype(0x3, CBW20-SGI), phymode(0x7, 11ax), max_rate:172, he:1, vht:1, ht:1
I (13875) wifi:(ht)max.RxAMPDULenExponent:3(65535 bytes), MMSS:4(2 us)
I (14735) wifi:(extcap)mbssid:0, enhanced_mbssid_advertise:0, complete_nontxbssid_profiles:0, twt_responder: 1
I (14735) wifi:connected with AlphaSTU_5G, aid = 2, channel 36, BW20(ABOVE, C0), bssid = ec:e7:c2:97:2f:0b
I (14745) wifi:security: WPA2-PSK, phy:11ax, rssi:-81, cipher(pairwise:0x3, group:0x3), pmf:0, 
I (14765) wifi:pm start, type: 1, twt_start:0

I (14765) wifi:pm start, type:1, aid:0x2, trans-BSSID:ec:e7:c2:97:2f:0b, BSSID[5]:0xb, mbssid(max-indicator:0, index:0), he:1
I (14765) wifi:dp: 1, bi: 102400, li: 3, scale listen interval from 307200 us to 307200 us
I (14775) wifi:set rx beacon pti, rx_bcn_pti: 10, bcn_timeout: 25000, mt_pti: 10, mt_time: 10000
I (14785) wifi:[ADDBA]TX addba request, tid:0, dialogtoken:4, bufsize:32, A-MSDU:0(not supported), policy:1(IMR), ssn:0(0x0)
I (14795) wifi:[ADDBA]TX addba request, tid:7, dialogtoken:5, bufsize:32, A-MSDU:0(not supported), policy:1(IMR), ssn:0(0x30)
I (14805) wifi:[ADDBA]TX addba request, tid:5, dialogtoken:6, bufsize:32, A-MSDU:0(not supported), policy:1(IMR), ssn:0(0x0)
I (14815) wifi:dp: 2, bi: 102400, li: 4, scale listen interval from 307200 us to 409600 us
I (14825) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (14835) wifi:[ADDBA]RX addba response, status:0, tid:0/tb:1(0xa1), bufsize:32, batimeout:0, txa_wnd:32
I (14845) wifi:[ADDBA]RX addba response, status:0, tid:7/tb:1(0xa1), bufsize:32, batimeout:0, txa_wnd:32
I (14845) wifi:[ADDBA]RX addba response, status:0, tid:5/tb:1(0xa1), bufsize:32, batimeout:0, txa_wnd:32
I (15875) esp_netif_handlers: sta ip: 192.168.1.221, mask: 255.255.255.0, gw: 192.168.1.1
I (15875) wifi station: got ip:192.168.1.221
W (20035) wifi:<ba-add>idx:0, ifx:0, tid:0, TAHI:0x1000b2f, TALO:0x97c2e7ec, (ssn:1, win:64, cur_ssn:1), CONF:0xc0000001
```

**Comment by Z-KY** [comment]
Further tests found that after successfully connecting to the Internet through the wrong password, the wifi information was written to nvs flash. After powering up again, the first time I connected to the Internet, I can still succeed by directly using the wrong password in nvs flash.

**Comment by Z-KY** [comment]
@filzek Hi,I made nvs clean and changes to the wifi storage type before connecting, but this didn't work.this is my code.

![Image](https://github.com/user-attachments/assets/dbdcadb0-8d9f-4c3d-aa04-d065b2c36989)

**Comment by filzek** [comment]
Did it return any error on the nvs esse?

**Comment by Z-KY** [comment]
> Did it return any error on the nvs erase actions?

No errors were returned. I tried running the above code on ESP32-C5-DevKitC-1 and the result was the same.

**Comment by mhdong** [comment]
hi @Z-KY 
Issue solved with https://github.com/espressif/esp-idf/commit/3d5bf355c30724781c4734cd3a29675b498fbdff

**Comment by Z-KY** [comment]
> hi [@Z-KY](https://github.com/Z-KY) Issue solved with [3d5bf35](https://github.com/espressif/esp-idf/commit/3d5bf355c30724781c4734cd3a29675b498fbdff)
hi, thanks, but I am running the code under the master branch of idf, my idf version is ESP-IDF v5.5-dev-2752-ga3864c088d, and I still have this problem. How can I solve it?

**Comment by mhdong** [comment]
hi @Z-KY 
Sorry, the commit I provided is earlier than the one you mentioned. I will try to reproduce and analyze it locally as soon as possible.

**Comment by Z-KY** [comment]
@mhdong Thank you.

**Comment by mhdong** [comment]
hi @Z-KY 
Issue solved with https://github.com/espressif/esp-idf/commit/a7d99f92046c3d424ff0f31a6424a6569167800d

**Comment by Z-KY** [comment]
@mhdong 
Yes, the problem has been solved, thank you very much for your answer.
