### ISSUE TITLE
Failed to get LL address, error: Invalid If index in a Ethernet-Openthread self-made Border Router with custom esp32c6 (IDFGH-15120)

### ISSUE THREAD

**Issue by diegomartinezvdi** [espressif/esp-idf#15799]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

**Board:** Custom ESP32-C6  
**ESP-IDF Version:** v5.4  
**Ethernet Chip:** W5500  
**Note:** Not using OpenThread CLI or RCP  

### Issue Description

I'm trying to reproduce the `esp_ot_br.c` example into a self-made border router. The issue I'm encountering is the following error: `E (70804) OPENTHREAD: Failed to get LL address, error: Invalid If index`

This error occurs in the function `otPlatGetInfraIfLinkLayerAddress`. There is a mismatch between the backbone interface index and the `infraIndex` that the OpenThread library assigns.

### What I'm Doing

I'm following a similar flow as the `esp_ot_br.c` example:

1. Creating the OpenThread interface first.
2. Then initializing the Ethernet interface.
3. Once the ESP32-C6 receives an IPv4 address, I set the Ethernet interface as the OpenThread backbone.

### Observations

- The `infra` interface is always initialized with index **7**.
- My Ethernet interface has index **3**.
- I only have 3 active interfaces:
  - loopback
  - openthread
  - ethernet

So I don't understand why OpenThread expects index 7. I've tried different initialization orders and configurations for OpenThread and Ethernet, but the error persists.

### Questions

- Why is OpenThread expecting interface index 7 instead of using the one actually assigned to the Ethernet interface?
- Is there a recommended order or configuration to avoid this index mismatch?
- Is it necessary to set the OpenThread interface as the default, even if I need the Ethernet one to use WebSockets?

### Additional Notes

- I’m **not** using the RCP or OpenThread CLI setup.
- Using W5500 with ESP-IDF Ethernet drivers.

### Logs
```
I (23) boot: ESP-IDF v5.4 2nd stage bootloader
I (24) boot: compile time Apr 16 2025 14:47:55
I (24) boot: chip revision: v0.0
I (24) boot: efuse block revision: v0.1
I (27) boot.esp32c6: SPI Speed      : 80MHz
I (31) boot.esp32c6: SPI Mode       : DIO
I (34) boot.esp32c6: SPI Flash Size : 4MB
I (38) boot: Enabling RNG early entropy source...
I (43) boot: Partition Table:
I (45) boot: ## Label            Usage          Type ST Offset   Length
I (52) boot:  0 nvs              WiFi data        01 02 0000d000 00004000
I (58) boot:  1 otadata          OTA data         01 00 00011000 00002000
I (65) boot:  2 phy_init         RF data          01 01 00013000 00001000
I (71) boot:  3 ota_0            OTA app          00 10 00020000 00180000
I (78) boot:  4 ota_1            OTA app          00 11 001a0000 00180000
I (84) boot:  5 factory_nvs      WiFi data        01 02 00320000 00004000
I (91) boot:  6 storage          WiFi data        01 02 00324000 000db000
I (97) boot: End of partition table
I (101) esp_image: segment 0: paddr=00020020 vaddr=420e0020 size=28808h (165896) map
I (139) esp_image: segment 1: paddr=00048830 vaddr=40800000 size=077e8h ( 30696) load
I (146) esp_image: segment 2: paddr=00050020 vaddr=42000020 size=de1d4h (909780) map
I (314) esp_image: segment 3: paddr=0012e1fc vaddr=408077e8 size=0a9cch ( 43468) load
I (324) esp_image: segment 4: paddr=00138bd0 vaddr=408121c0 size=0223ch (  8764) load
I (331) boot: Loaded app from partition at offset 0x20000
I (331) boot: Disabling RNG early entropy source...
I (342) cpu_start: Unicore app
I (351) cpu_start: Pro cpu start user code
I (351) cpu_start: cpu freq: 80000000 Hz
I (351) app_init: Application information:
I (354) app_init: Project name:     borderRouter
I (359) app_init: App version:      d5c81492-dirty
I (364) app_init: Compile time:     Apr 16 2025 14:40:31
I (370) app_init: ELF file SHA256:  73811ce0c7f388ad...
I (376) app_init: ESP-IDF:          v5.4
I (381) efuse_init: Min chip rev:     v0.0
I (385) efuse_init: Max chip rev:     v0.99 
I (390) efuse_init: Chip rev:         v0.0
I (395) heap_init: Initializing. RAM available for dynamic allocation:
I (402) heap_init: At 40822570 len 0005A0A0 (360 KiB): RAM
I (409) heap_init: At 4087C610 len 00002F54 (11 KiB): RAM
I (415) heap_init: At 50000000 len 00003FE8 (15 KiB): RTCRAM
I (422) spi_flash: detected chip: generic
I (426) spi_flash: flash io: dio
W (430) spi_flash: Detected size(8192k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (443) sleep_gpio: Configure to isolate all GPIO pins in sleep state
I (450) sleep_gpio: Enable automatic switching of GPIO sleep configuration
I (458) coexist: coex firmware version: 49a8cdc
I (471) coexist: coexist rom version 5b8dcfa
I (472) main_task: Started on CPU0
I (472) main_task: Calling app_main()
I (472) gpio: GPIO[6]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (482) gpio: GPIO[12]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (492) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (562) gpio: GPIO[20]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (562) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (572) gpio: GPIO[3]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (582) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (602) mdns_mem: mDNS task will be created from internal RAM
I (602) OPENTHREAD: Host connection mode none
I (602) phy_init: phy_version 320,348a293,Sep  3 2024,16:33:12
I (652) phy: libbtbb version: 04952fd, Sep  3 2024, 16:33:30
I(662) OPENTHREAD:[I] CslTxScheduler: Bus TX Time: 0 usec, Latency: 0 usec. Calculated CSL Frame Request Ahead: 20000 usec
I(662) OPENTHREAD:[I] ChildSupervsn-: Timeout: 0 -> 190
I (672) OPENTHREAD: OpenThread attached to netif
I(672) OPENTHREAD:[I] Notifier------: StateChanged (0x00038210) [MLAddr NetData PanId NetName ExtPanId]
I(682) OPENTHREAD:[I] RouterTable---: Route table
I (682) gpio: GPIO[10]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (692) main_task: Returned from app_main()
I (712) esp_eth.netif.netif_glue: 40:4c:ca:ff:fe:44
I (712) esp_eth.netif.netif_glue: ethernet attached to netif
I (10592) esp_netif_handlers: eth ip: 192.168.2.163, mask: 255.255.255.0, gw: 192.168.2.1
I (10592) esp_ot_br: Auto-start mode enabled
I(10592) OPENTHREAD:[I] SrpServer-----: Selected port 53536
I(10602) OPENTHREAD:[I] NetDataPublshr: Publishing DNS/SRP service unicast (ml-eid, port:53536)
I(10612) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service - State: NoEntry -> ToAdd
I(10622) OPENTHREAD:[I] RoutingManager: Initializing - InfraIfIndex:7
I(10622) OPENTHREAD:[I] InfraIf-------: Init infra netif 7
I(10632) OPENTHREAD:[N] RoutingManager: No valid /48 BR ULA prefix found in settings, generating new one
I(10652) OPENTHREAD:[I] Settings------: Saved BrUlaPrefix fd9e:fb32:9e8c::/48
I(10652) OPENTHREAD:[N] RoutingManager: BR ULA prefix: fd9e:fb32:9e8c::/48 (generated)
I(10662) OPENTHREAD:[I] RoutingManager: Generated local OMR prefix: fd9e:fb32:9e8c:1::/64
I(10672) OPENTHREAD:[I] RoutingManager: Generated local NAT64 prefix: fd9e:fb32:9e8c:2:0:0::/96
I(10682) OPENTHREAD:[N] RoutingManager: Local on-link prefix: fdde:ad00:beef:cafe::/64
I(10682) OPENTHREAD:[I] InfraIf-------: State changed: NOT RUNNING -> RUNNING
I(10692) OPENTHREAD:[I] RoutingManager: Enabling
I(10702) OPENTHREAD:[I] BbrLocal------: Add Domain Prefix: ::/0, NotFound
I(10702) OPENTHREAD:[I] BbrLocal------: Add BBR Service: seqno (126), delay (5s), timeout (3600s), InvalidState
I(10732) OPENTHREAD:[I] Settings------: Saved ActiveDataset
I(10732) OPENTHREAD:[I] DatasetManager: Active dataset set
E (10732) OPENTHREAD: Failed to leave multicast group
I(10732) OPENTHREAD:[I] Bbr-----------: Backbone TMF unsubscribes ff32:40:fdde:ad00:beef:0:0:3: OK
I(10752) OPENTHREAD:[I] Bbr-----------: Backbone TMF subscribes ff32:40:fd00:db8:a0:0:0:3: OK
I(10762) OPENTHREAD:[I] DnssdServer---: Started
I (10762) OPENTHREAD: Platform UDP bound to port 49153
I(10762) OPENTHREAD:[I] BbrLocal------: Remove BBR Service: seqno (126), delay (5s), timeout (3600s), NotFound
I(10782) OPENTHREAD:[N] Mle-----------: Role disabled -> detached
I(10782) OPENTHREAD:[I] Mle-----------: AttachState Idle -> Start
I(10792) OPENTHREAD:[I] Notifier------: StateChanged (0x131dd11d) [Ip6+ Role LLAddr MLAddr KeySeqCntr Ip6Mult+ Channel PanId NetName NetworkKey ...
I(10802) OPENTHREAD:[I] Notifier------: StateChanged (0x131dd11d) ... PSKc SecPolicy NetifState BbrState ActDset]
I (10812) OPENTHREAD: Platform UDP bound to port 61631
I(10822) OPENTHREAD:[I] Bbr-----------: Start listening on port 61631
I(10832) OPENTHREAD:[I] Bbr-----------: Backbone TMF subscribes ff32:40:fd00:db8:a0:0:0:3: OK
I(10842) OPENTHREAD:[I] BbrManager----: Start Backbone TMF agent: OK
I(10842) OPENTHREAD:[I] AnnounceSender: Stopped
I(10852) OPENTHREAD:[I] AnnounceSender: ChannelMask:{ 11-26 }, period:21500
I(10862) OPENTHREAD:[I] AnnounceSender: StartingChannel:15
I(10862) OPENTHREAD:[I] AnnounceSender: StartingChannel:15
I (10872) OT_STATE: netif up
I (10872) OPENTHREAD: NAT64 ready
I(11392) OPENTHREAD:[N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
I(11392) OPENTHREAD:[I] Mle-----------: AttachState Start -> ParentReq
I(11392) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers (ff02:0:0:0:0:0:0:2)
I(11412) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:94f1, ecn:no, to:0xffff, sec:no, prio:net
I(11412) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(11422) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(12172) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers (ff02:0:0:0:0:0:0:2)
I(12182) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:08ad, ecn:no, to:0xffff, sec:no, prio:net
I(12182) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(12192) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(12942) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(12942) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:978e, ecn:no, to:0xffff, sec:no, prio:net
I(12952) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(12962) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(14212) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(14212) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:5ada, ecn:no, to:0xffff, sec:no, prio:net
I(14222) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(14232) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(15482) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(15482) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:8b43, ecn:no, to:0xffff, sec:no, prio:net
I(15492) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(15502) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(16752) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(16762) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:e387, ecn:no, to:0xffff, sec:no, prio:net
I(16762) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(16772) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(18022) OPENTHREAD:[I] Mle-----------: AttachState ParentReq -> Idle
I(18022) OPENTHREAD:[N] RouterTable---: Allocate router id 16
I(18022) OPENTHREAD:[N] Mle-----------: RLOC16 fffe -> 4000
I(18022) OPENTHREAD:[N] Mle-----------: Role detached -> leader
I(18032) OPENTHREAD:[N] Mle-----------: Partition ID 0x2ab56d58
I(18042) OPENTHREAD:[I] RouterTable---: Route table
I(18042) OPENTHREAD:[I] RouterTable---:     16 0x4000 - me - leader
I(18052) OPENTHREAD:[I] Notifier------: StateChanged (0x100012a5) [Ip6+ Role Rloc+ PartitionId NetData Ip6Mult+ ActDset]
I(18072) OPENTHREAD:[I] Settings------: Saved NetworkInfo {rloc:0x4000, extaddr:beb3367dfac70617, role:leader, mode:0x0f, version:5, keyseq:0x0, ...
I(18082) OPENTHREAD:[I] Settings------: ... pid:0x2ab56d58, mlecntr:0x3ef, maccntr:0x3e8, mliid:7af0f780b077e99c}
I(18092) OPENTHREAD:[I] Mle-----------: Send Data Response (ff02:0:0:0:0:0:0:1)
I(18092) OPENTHREAD:[I] BbrLeader-----: PBBR state: None
I(18102) OPENTHREAD:[I] Settings------: Re-saved NetworkInfo {rloc:0x4000, extaddr:beb3367dfac70617, role:leader, mode:0x0f, version:5, keyseq:0x0, ...
I(18112) OPENTHREAD:[I] Settings------: ... pid:0x2ab56d58, mlecntr:0x3ef, maccntr:0x3e8, mliid:7af0f780b077e99c}
I(18132) OPENTHREAD:[I] AnnounceSender: Started
I(18132) OPENTHREAD:[I] SecTransport--: State: Closed -> Open
I (18142) OPENTHREAD: Platform UDP bound to port 49154
I(18142) OPENTHREAD:[I] BorderAgent---: Border Agent start listening on port 49154
I(18152) OPENTHREAD:[I] RoutingManager: RIO Preference changed: low -> medium
I(18162) OPENTHREAD:[I] RoutingManager: Starting
I(18162) OPENTHREAD:[I] RoutingManager: RsSender: Starting - will send first RS in 507 msec
I(18172) OPENTHREAD:[I] RoutingManager: Starting Nat64PrefixManager
I(18182) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:03.782 (3782 msec)
I(18192) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service (state:ToAdd) in netdata - total:0, preferred:0, desired:2
I(18202) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service - State: ToAdd -> Adding
I(18212) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service (state:Adding) - update in 1192 msec
I(18232) OPENTHREAD:[I] Settings------: Saved BorderAgentId {id:ae8c5ea767bd4d72975ef7c7486396d8}
I (18232) OPENTHREAD: NAT64 ready
I(18232) OPENTHREAD:[I] RoutingManager: Infraif NAT64 prefix: none
I(18242) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:03.459 (3459 msec)
I(18252) OPENTHREAD:[I] RoutingManager: Discovering infraif NAT64 prefix
I(18252) OPENTHREAD:[I] RoutingManager: NAT64 prefix timer scheduled in 300 seconds
I(18272) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:96, chksum:5528, ecn:no, to:0xffff, sec:no, prio:net
I(18272) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(18282) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:1]:19788
E (18692) OPENTHREAD: Failed to get LL address, error: Invalid If index
I(18692) OPENTHREAD:[I] RoutingManager: RsSender: Sent RS 1/3
I(18692) OPENTHREAD:[I] RoutingManager: Received RS from fe80:0:0:0:424c:caff:feff:fe44 on infra netif 7
I(18702) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:00.172 (172 msec)
I(18812) OPENTHREAD:[I] Mle-----------: Send Advertisement (ff02:0:0:0:0:0:0:1)
I(18822) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:90, chksum:ee50, ecn:no, to:0xffff, sec:no, prio:net
I(18822) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:bcb3:367d:fac7:617]:19788
I(18832) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:1]:19788
I(18892) OPENTHREAD:[I] RoutingManager: Evaluating routing policy
I(18892) OPENTHREAD:[I] RoutingManager: Setting local OMR prefix to generated prefix: fd9e:fb32:9e8c:1::/64
I(18892) OPENTHREAD:[I] RoutingManager: No favored OMR prefix found in Thread network.
I(18902) OPENTHREAD:[I] RoutingManager: Added local OMR prefix fd9e:fb32:9e8c:1::/64 (def-route:no) in Thread Network Data
I(18912) OPENTHREAD:[I] RoutingManager: Evaluating NAT64 prefix
I(18922) OPENTHREAD:[I] NetDataPublshr: Publishing ExternalRoute fd9e:fb32:9e8c:2:0:0::/96
I(18932) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fd9e:fb32:9e8c:2:0:0::/96 - State: NoEntry -> ToAdd
I(18942) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fd9e:fb32:9e8c:2:0:0::/96 (state:ToAdd) in netdata - total:0, preferred:0, desired:10
I(18952) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fd9e:fb32:9e8c:2:0:0::/96 - State: ToAdd -> Adding
I(18962) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fd9e:fb32:9e8c:2:0:0::/96 (state:Adding) - update in 2738 msec
I(18972) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:14.583 (14583 msec)
I(18982) OPENTHREAD:[I] NetworkData---: Sent ServerData
I(18992) OPENTHREAD:[I] NetworkData---: Received ServerData
I(18992) OPENTHREAD:[I] NetworkData---: Sent ServerData ack
I(19002) OPENTHREAD:[I] Notifier------: StateChanged (0x00000200) [NetData]
I(19012) OPENTHREAD:[I] Mle-----------: Send Data Response (ff02:0:0:0:0:0:0:1)
I(19022) OPENTHREAD:[I] BbrLeader-----: PBBR state: None
I(19032) OPENTHREAD:[I] Settings------: Saved SlaacIidSecretKey
I(19032) OPENTHREAD:[I] Slaac---------: Generated and saved secret key
I(19042) OPENTHREAD:[I] Slaac---------: Adding fd9e:fb32:9e8c:1:228f:c130:1885:fc70
I(19052) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:02.691 (2691 msec)
I(19062) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service (state:Adding) in netdata - total:0, preferred:0, desired:2
I(19062) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fd9e:fb32:9e8c:2:0:0::/96 (state:Adding) in netdata - total:0, preferred:0, desired:10
I (19082) OPENTHREAD: NAT64 ready
I(19082) OPENTHREAD:[I] Notifier------: StateChanged (0x00000001) [Ip6+]
I (19092) OPENTHREAD: NAT64 ready
I(19102) OPENTHREAD:[I] BbrLocal------: Add BBR Service: seqno (126), delay (5s), timeout (3600s), OK
W(19102) OPENTHREAD:[W] DuaManager----: Failed to perform next registration: InvalidState
I(19112) OPENTHREAD:[I] NetworkData---: Sent ServerData
I(19122) OPENTHREAD:[I] NetworkData---: Received ServerData
I(19122) OPENTHREAD:[I] NetworkData---: Allocated Service ID = 0
I(19132) OPENTHREAD:[I] NetworkData---: Sent ServerData ack
I(19142) OPENTHREAD:[I] Notifier------: StateChanged (0x00000200) [NetData]
I(19142) OPENTHREAD:[I] Mle-----------: Send Data Response (ff02:0:0:0:0:0:0:1)
I(19152) OPENTHREAD:[I] BbrLeader-----: PBBR state: Added
I(19162) OPENTHREAD:[I] BbrLeader-----: Rloc16:0x4000, seqno:126, delay:5, timeout:3600
I(19172) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:03.870 (3870 msec)
I(19182) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service (state:Adding) in netdata - total:0, preferred:0, desired:2
I(19192) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fd9e:fb32:9e8c:2:0:0::/96 (state:Adding) in netdata - total:0, preferred:0, desired:10
I (19202) OPENTHREAD: NAT64 ready
I(19202) OPENTHREAD:[I] Notifier------: StateChanged (0x02000001) [Ip6+ BbrState]
I(19212) OPENTHREAD:[I] Bbr-----------: Start listening on port 61631
I(19222) OPENTHREAD:[I] Bbr-----------: Backbone TMF subscribes ff32:40:fd00:db8:a0:0:0:3: OK
I(19232) OPENTHREAD:[I] BbrManager----: Start Backbone TMF agent: OK
I (19242) OPENTHREAD: NAT64 ready
```

### Code

```
// Private variables
static esp_openthread_platform_config_t s_openthread_platform_config;
 
// Private function declaration
static void ot_br_init(void *ctx);
static void ot_task_worker(void *ctx);
static void launch_openthread_border_router(const esp_openthread_platform_config_t *platform_config, const esp_openthread_platform_config_t *update_config);


// Public functions
void OpenThreadInit() {
  ESP_ERROR_CHECK(nvs_flash_init());
  ESP_ERROR_CHECK(esp_netif_init());
  ESP_ERROR_CHECK(esp_event_loop_create_default());

  esp_vfs_eventfd_config_t eventfd_config = {
      .max_fds = 4,
  };

  esp_openthread_platform_config_t config = {
      .radio_config = {.radio_mode = RADIO_MODE_NATIVE},
      .host_config = {.host_connection_mode = HOST_CONNECTION_MODE_NONE},
      .port_config = {
          .storage_partition_name = "nvs",
          .netif_queue_size = 10,
          .task_queue_size = 10},
  };

  ESP_ERROR_CHECK(esp_vfs_eventfd_register(&eventfd_config));
  ESP_ERROR_CHECK(mdns_init());
  ESP_ERROR_CHECK(mdns_hostname_set("esp-ot-br"));

  launch_openthread_border_router(&config, NULL);
}

void OpenThreadStartCommissioner(void) {
  printf("Starting commissioner...\n");
  esp_openthread_lock_acquire(portMAX_DELAY);
  otCommissionerStart(esp_openthread_get_instance(), &CommissionerStateChangeEventHandler, &JoinerEventHandler, NULL);
  esp_openthread_lock_release();
}

// Pravte function definition

static void ot_br_init(void *ctx) {
  EthernetInit();
  while(EthernetGetState() != ETHERNET_GOT_IP);
  if (true) {
    ESP_LOGI(TAG, "Auto-start mode enabled");
    esp_openthread_lock_acquire(portMAX_DELAY);
    esp_openthread_set_backbone_netif(EthernetGetNetIf());
    ESP_ERROR_CHECK(esp_openthread_border_router_init());
    otOperationalDatasetTlvs dataset;
    otError error = otDatasetGetActiveTlvs(esp_openthread_get_instance(), &dataset);
    ESP_ERROR_CHECK(esp_openthread_auto_start((error == OT_ERROR_NONE) ? &dataset : NULL));
    esp_openthread_lock_release();
  } else {
    ESP_LOGE(TAG, "Auto-start mode failed, please try to start manually");
  }
  vTaskDelete(NULL);
}

static void ot_task_worker(void *ctx) {
  esp_netif_config_t cfg = ESP_NETIF_DEFAULT_OPENTHREAD();
  esp_netif_t *openthread_netif = esp_netif_new(&cfg);

  assert(openthread_netif != NULL);

  // Initialize the OpenThread stack
  ESP_ERROR_CHECK(esp_openthread_init(&s_openthread_platform_config));

  esp_openthread_lock_acquire(portMAX_DELAY);

  ESP_ERROR_CHECK(esp_netif_attach(openthread_netif, esp_openthread_netif_glue_init(&s_openthread_platform_config)));
  ESP_ERROR_CHECK(esp_netif_set_default_netif(openthread_netif));
// #if CONFIG_OPENTHREAD_LOG_LEVEL_DYNAMIC
  // (void)otLoggingSetLevel(CONFIG_LOG_DEFAULT_LEVEL);
// #endif
  // esp_openthread_cli_init();
  // esp_cli_custom_command_init();
  // esp_openthread_cli_create_task();

  esp_openthread_lock_release();

  xTaskCreate(ot_br_init, "ot_br_init", 6144, NULL, 4, NULL);
  // Run the main loop
  esp_openthread_launch_mainloop();

  // Clean up
  esp_openthread_netif_glue_deinit();
  esp_netif_destroy(openthread_netif);
  esp_vfs_eventfd_unregister();
  vTaskDelete(NULL);
}

void launch_openthread_border_router(const esp_openthread_platform_config_t *platform_config, const esp_openthread_platform_config_t *update_config)
{
    s_openthread_platform_config = *platform_config;

    OT_UNUSED_VARIABLE(update_config);
    xTaskCreate(ot_task_worker, "ot_br_main", 8192, xTaskGetCurrentTaskHandle(), 5, NULL);
}
```

**Comment by chshu** [comment]
@diegomartinezvdi could you please check the return value of `EthernetGetNetIf()`, the issue should not happen if the `esp_openthread_set_backbone_netif(EthernetGetNetIf());` set the correct backbone netif.

**Comment by diegomartinezvdi** [comment]
@chshu it returns the pointer to the

**Comment by diegomartinezvdi** [comment]
> [@diegomartinezvdi](https://github.com/diegomartinezvdi) could you please check the return value of `EthernetGetNetIf()`, the issue should not happen if the `esp_openthread_set_backbone_netif(EthernetGetNetIf());` set the correct backbone netif.

**Comment by diegomartinezvdi** [comment]
Hi @chshu,

Thank you for your response and for your interest in the issue.

The function returns an `esp_netif_t *`, specifically the one named `ethNetIf`, which is declared globally as `static`. I'm sharing the file where the Ethernet functions are defined to provide more clarity.

Really appreciate your help!

```
#include "Ethernet/Ethernet.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "Pinout/Pinout.h"
#include <esp_netif.h>
#include <esp_eth.h>
#include <esp_event.h>
#include <esp_mac.h>
#include <driver/gpio.h>
#include "Pinout/Pinout.h"
#include "Hardware/Board.h"
#include "sdkconfig.h"
#include "System/Tick.h"
#include <string.h>
#include "Hardware/Phy.h"
#include "Debug/Debug.h"
#include "Configs/config.h"
#include "OpenThread/OpenThread.h"
#include <lwip/netif.h>
#include "esp_openthread_border_router.h"

#ifdef ETH_CHIP_USE_W5500
  #include "SPIHw/SPIHw.h"
#endif

#undef ETHERNET_DEBUG
#ifdef ETHERNET_DEBUG
  #include "Debug/Debug.h"
#endif

#define NO_IP_PREFIX "169.254"
#define HOSTNAME_LEN 13

// Funciones privadas
static void EthEventHandler(void *arg, esp_event_base_t eventBase, int32_t eventId, void *eventData);
static void IpEventHandler(void *arg, esp_event_base_t eventBase, int32_t eventId, void *eventData);
static void StopStack(void);
static void CreateHostName(char *hostName);
#ifdef ETH_CHIP_USE_LAN8720A
  static void InitLan8720a(eth_mac_config_t *macConfig, eth_phy_config_t *phyConfig);
#elif defined(ETH_CHIP_USE_W5500)
  static void InitW5500(eth_mac_config_t *macConfig, eth_phy_config_t *phyConfig);
  static void *CustomW5500Init(const void *spi_config);
  static esp_err_t CustomW5500Deinit(void *spi_ctx);
  static esp_err_t CustomW5500Read(void *spi_ctx, uint32_t cmd, uint32_t addr, void *data, uint32_t data_len);
  static esp_err_t CustomW5500Write(void *spi_ctx, uint32_t cmd, uint32_t addr, const void *data, uint32_t data_len);
#endif

// Variables privadas
static EthernetState ethState;
static esp_eth_handle_t ethHandle;
static esp_netif_t *ethNetIf;
static esp_eth_mac_t *mac;
static esp_eth_phy_t *phy;
static void *ethGlue;
#ifdef ETH_CHIP_USE_W5500
  static SPIDevice device;
#endif

// Funciones publicas
void EthernetInit() {
    uint32_t tick;
    char hostName[HOSTNAME_LEN] = {0};

    #ifdef ETH_CHIP_USE_LAN8720A
    // Habilitamos la salida de reloj del PHY
    PhyEnableClkOutput();
    #endif

    // Configuracion tcpip por defecto
    esp_netif_config_t cfg = ESP_NETIF_DEFAULT_ETH();
    ethNetIf = esp_netif_new(&cfg);

    if(ethNetIf == NULL){
      return;
    }

    CreateHostName(hostName);
    esp_netif_set_hostname(ethNetIf, hostName);
    // Inicializar TcpIP (netif -> capa abstracion para lwIP)
    ESP_ERROR_CHECK(esp_netif_init());

    eth_mac_config_t macConfig = ETH_MAC_DEFAULT_CONFIG();
    eth_phy_config_t phyConfig = ETH_PHY_DEFAULT_CONFIG();
    phyConfig.phy_addr = PHY_ADDR;
    phyConfig.reset_gpio_num = PINOUT_PHY_RST_GPIO;
    phyConfig.autonego_timeout_ms = ETHERNET_NEGOTIATION_TIMEOUT * 1000;

    #ifdef ETH_CHIP_USE_LAN8720A
      InitLan8720a(&macConfig, &phyConfig);
    #elif defined(ETH_CHIP_USE_W5500)
      InitW5500(&macConfig, &phyConfig);
    #endif
    struct netif *netif;
    for (netif = netif_list; netif != NULL; netif = netif->next) {
      // printf("Interface: %s, Index: %u\n", netif->name, netif->num);
  }
  // printf("------ index: %u ------\n", esp_netif_get_netif_impl_index(esp_netif_get_handle_from_ifkey("ETH_DEF")));

  char *test;
  test = esp_netif_get_ifkey(EthernetGetNetIf());
  // printf("------ MY NETIF: %s ------\n", test);
    esp_eth_config_t config = ETH_DEFAULT_CONFIG(mac, phy);
    ESP_ERROR_CHECK(esp_eth_driver_install(&config, &ethHandle));

    uint8_t baseMac[6];
    esp_efuse_mac_get_default(baseMac);
    uint8_t ethMac[6] = {baseMac[0], baseMac[1], baseMac[2], baseMac[3], baseMac[4], baseMac[5]};
    esp_eth_ioctl(ethHandle, ETH_CMD_S_MAC_ADDR, ethMac);

    ethGlue = esp_eth_new_netif_glue(ethHandle);
    ESP_ERROR_CHECK(esp_netif_attach(ethNetIf, ethGlue));
    // ESP_ERROR_CHECK(esp_netif_set_default_netif(ethNetIf));

    // printf("ETHERNET_DEBUG: ethernet netif attached and def\n");

    // Registrar handlers propios (recomendado justo antes de llamar a esp_eth_start)
    ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ESP_EVENT_ANY_ID, &EthEventHandler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, ESP_EVENT_ANY_ID, &IpEventHandler, NULL));
    
    tick = TickGet();

    // esp_openthread_set_backbone_netif(ethNetIf);

    ESP_ERROR_CHECK(esp_eth_start(ethHandle));

    while(TickGet() - tick < (ETHERNET_NEGOTIATION_TIMEOUT + ETHERNET_NEGOTIATION_THRESHOLD) * TICK_SECOND);

}

void EthernetReset() {
    PhyReset();

    StopStack();

    EthernetInit();
}

EthernetState EthernetGetState(){
    return ethState;
}

esp_netif_t *EthernetGetNetIf(){
  return ethNetIf;
}

// Funciones privadas
void EthEventHandler(void *arg, esp_event_base_t eventBase, int32_t eventId, void *eventData) {

    switch (eventId) {
    case ETHERNET_EVENT_CONNECTED:{
        #ifdef ETHERNET_DEBUG
            uint8_t mac_addr[6] = {0};
            esp_eth_handle_t ethHandle = *(esp_eth_handle_t *)eventData;
            esp_eth_ioctl(ethHandle, ETH_CMD_G_MAC_ADDR, mac_addr);
            Debug("ETHERNET: Connected\n");
            Debug("ETHERNET: MAC Addr %02x:%02x:%02x:%02x:%02x:%02x\n",
                    mac_addr[0], mac_addr[1], mac_addr[2], mac_addr[3], mac_addr[4], mac_addr[5]);
        #endif
        ethState = ETHERNET_CONNECTED;
        esp_netif_create_ip6_linklocal(ethNetIf);
        break;}
    case ETHERNET_EVENT_DISCONNECTED:
        #ifdef ETHERNET_DEBUG
            Debug("ETHERNET: Disconnected\n");
        #endif
        ethState = ETHERNET_DISCONNECTED;
        break;
    case ETHERNET_EVENT_START:
        #ifdef ETHERNET_DEBUG
            Debug("ETHERNET: Started\n");
        #endif
        break;
    case ETHERNET_EVENT_STOP:
        #ifdef ETHERNET_DEBUG
            Debug("ETHERNET: Stopped\n");
        #endif
        break;
    default:
        break;
    }
}

void IpEventHandler(void *arg, esp_event_base_t eventBase, int32_t eventId, void *eventData) {
    char ipPrefix[8];

    switch(eventId){
        case IP_EVENT_ETH_GOT_IP:{

          ip_event_got_ip_t *event = (ip_event_got_ip_t *) eventData;

          #ifdef ETHERNET_DEBUG
            Debug("ETHERNET: GOT IP\n");
          #endif

          sprintf(ipPrefix, "%d.%d" , esp_ip4_addr1(&event->ip_info.ip), esp_ip4_addr2(&event->ip_info.ip));

          if(strcmp(NO_IP_PREFIX, ipPrefix) != 0){
            ethState = ETHERNET_GOT_IP;
          }

          //  = esp_netif_get_handle_from_ifkey("eth");

          esp_ip6_addr_t ip6_addr;
          if (esp_netif_get_ip6_linklocal(ethNetIf, &ip6_addr) == ESP_OK) {
              printf("IPv6: %lx:%lx:%lx:%lx:%lx:%lx:%lx:%lx\n",
                  (ip6_addr.addr[0] >> 16) & 0xFFFF, ip6_addr.addr[0] & 0xFFFF,
                  (ip6_addr.addr[1] >> 16) & 0xFFFF, ip6_addr.addr[1] & 0xFFFF,
                  (ip6_addr.addr[2] >> 16) & 0xFFFF, ip6_addr.addr[2] & 0xFFFF,
                  (ip6_addr.addr[3] >> 16) & 0xFFFF, ip6_addr.addr[3] & 0xFFFF);
          } else {
            printf("ERROR IPV6\n");
          }

          // OpenThreadInit();

        break;
      }
    }
}

void StopStack(void){
    // Destruir todas las dependencias del driver antes de desinstalarlo
    // Parar el driver
    ESP_ERROR_CHECK(esp_eth_stop(ethHandle));

    // Desanclar eventos
    ESP_ERROR_CHECK(esp_event_handler_unregister(IP_EVENT, ESP_EVENT_ANY_ID, &IpEventHandler));
    ESP_ERROR_CHECK(esp_event_handler_unregister(ETH_EVENT, ESP_EVENT_ANY_ID, &EthEventHandler));

    ESP_ERROR_CHECK(esp_eth_del_netif_glue(ethGlue));
    esp_netif_destroy(ethNetIf);

    ESP_ERROR_CHECK(esp_eth_driver_uninstall(ethHandle));

    ESP_ERROR_CHECK(mac->del(mac));
    ESP_ERROR_CHECK(phy->del(phy));
}

void CreateHostName(char *hostName) {
  uint16_t prefixLen;
  char devid[CONFIG_DEVID_LEN + 1];

  ConfigGetDevId(devid);

  prefixLen = strlen("Gateway-");

  memcpy(hostName, "Gateway-", prefixLen);

  strncpy(&hostName[prefixLen], devid, 4);

  hostName[prefixLen + 4] = 0;
}

#ifdef ETH_CHIP_USE_LAN8720A
  void InitLan8720a(eth_mac_config_t *macConfig, eth_phy_config_t *phyConfig) {
    eth_esp32_emac_config_t emacConfig = ETH_ESP32_EMAC_DEFAULT_CONFIG();
    emacConfig.smi_gpio.mdc_num = MDC_GPIO;
    emacConfig.smi_gpio.mdio_num = MDIO_GPIO;
    mac = esp_eth_mac_new_esp32(&emacConfig, macConfig);
    phy = esp_eth_phy_new_lan87xx(phyConfig);
  }
#elif defined(ETH_CHIP_USE_W5500)
  void InitW5500(eth_mac_config_t *macConfig, eth_phy_config_t *phyConfig) {
    device.config.clock_speed_hz = 20000000;
    device.config.mode = 0;
    device.config.spics_io_num = -1;
    device.config.queue_size = 7;
    device.config.command_bits = 16;
    device.config.address_bits = 8;
    device.csPin = PINOUT_SPI_ETH_CS_GPIO;

    gpio_install_isr_service(0);
    SPIHwDeviceInit(&device);

    eth_w5500_config_t w5500Config = ETH_W5500_DEFAULT_CONFIG(SPI2_HOST, &device.config);

    w5500Config.int_gpio_num = PINOUT_PHY_SPI_INT_GPIO;
    w5500Config.custom_spi_driver.init = CustomW5500Init;
    w5500Config.custom_spi_driver.deinit = CustomW5500Deinit;
    w5500Config.custom_spi_driver.write = CustomW5500Write;
    w5500Config.custom_spi_driver.read = CustomW5500Read;
    w5500Config.custom_spi_driver.config = &w5500Config;
    mac = esp_eth_mac_new_w5500(&w5500Config, macConfig);
    phy = esp_eth_phy_new_w5500(phyConfig);
  }

  void *CustomW5500Init(const void *spi_config) {
    // This function is required to set up custom SPI read and write functions.
    // It does not perform any additional initialization.
    static int ret; 
    return &ret;
  }

  esp_err_t CustomW5500Deinit(void *spi_ctx) {
    // This function is required to set up custom SPI read and write functions.
    // It does not perform any additional deinitialization.
    return ESP_OK;
  }

  esp_err_t CustomW5500Read(void *spi_ctx, uint32_t cmd, uint32_t addr, void *data, uint32_t data_len) {
    SPIHwEnable(&device);
    SPIHwReadPayload(&device, cmd, addr, data, data_len);
    SPIHwDisable(&device);
    return ESP_OK;
  }

  esp_err_t CustomW5500Write(void *spi_ctx, uint32_t cmd, uint32_t addr, const void *data, uint32_t data_len) {
    SPIHwEnable(&device);
    esp_err_t ret = SPIHwWritePayload(&device, cmd, addr, data, data_len);
    SPIHwDisable(&device);
    return ret;
  }
#endif
```

**Comment by chshu** [comment]
@diegomartinezvdi Could you please update to IDF [v5.4.1](https://github.com/espressif/esp-idf/tree/v5.4.1), and test again? It looks like an old issue that has been fixed.

**Comment by diegomartinezvdi** [comment]
Hi again @chshu, 

I’ve just tried updating to IDF v5.4.1, but the error still persists.

**Comment by chshu** [comment]
@diegomartinezvdi Did you update the submodules after switching to IDF v5.4.1:

```
git submodule update --init --recursiv
```
The previous issue was fixed in the thread br lib, the issue may persist if you didn't update the thread lib submodule.

Otherwise, please share the logs from boot on IDF v5.4.1, we will do some furhter analysis.

**Comment by diegomartinezvdi** [comment]
Hello @chshu 

The issue still persists even after updating the submodules as suggested.
I’m attaching the logs below for reference.

**Comment by gytxxsy** [comment]
@diegomartinezvdi 

Using index `7` during initialization seems a bit strange. Could you add some log prints so that we can observe whether multiple netif add and remove operations are happening, as well as the actual name of the netif being used?
In function `otPlatGetInfraIfLinkLayerAddress` of `esp-idf/components/openthread/src/esp_openthread_netif_glue.c`, please modify the following code:
```
#include "lwip/netif.h"
...
...
otError otPlatGetInfraIfLinkLayerAddress(otInstance *aInstance, uint32_t aIfIndex, otPlatInfraIfLinkLayerAddress *aInfraIfLinkLayerAddress)
{
    esp_netif_t *backbone_netif = esp_openthread_get_backbone_netif();

    char name1[NETIF_NAMESIZE] = "";
    char name2[NETIF_NAMESIZE] = "";
    netif_index_to_name(aIfIndex, name1);
    netif_index_to_name(esp_netif_get_netif_impl_index(backbone_netif), name2);
    printf("netif1(%lu) %s, netif2(%d) %s\n", aIfIndex, name1, esp_netif_get_netif_impl_index(backbone_netif), name2);

    if (esp_netif_get_netif_impl_index(backbone_netif) != aIfIndex) {
        ESP_LOGE(OT_PLAT_LOG_TAG, "Failed to get LL address, error: Invalid If index");
        return OT_ERROR_FAILED;
    } else {
        esp_netif_get_mac(backbone_netif, aInfraIfLinkLayerAddress->mAddress);
        aInfraIfLinkLayerAddress->mLength = 6;
        return OT_ERROR_NONE;
    }
}
```

The initialization of the Thread border router actually uses the netif provided by esp_openthread_set_backbone_netif. Therefore, before calling esp_openthread_border_router_init(), you can try calling these two functions:
```C
esp_netif_get_netif_impl_index(esp_openthread_get_backbone_netif());
esp_netif_get_netif_impl_index(EthernetGetNetIf());
```

and print the current index value of the backbone_netif and ethNetIf. This will help with further debugging.

**Comment by diegomartinezvdi** [comment]
Hi @gytxxsy ,

Here are the logs after applying the changes you suggested.
Thanks for your help.

The infra NetIf appears to be unnamed.
```
I (23) boot: ESP-IDF v5.4 2nd stage bootloader
I (24) boot: compile time Apr 30 2025 11:35:16
I (24) boot: chip revision: v0.0
I (24) boot: efuse block revision: v0.1
I (27) boot.esp32c6: SPI Speed      : 80MHz
I (31) boot.esp32c6: SPI Mode       : DIO
I (34) boot.esp32c6: SPI Flash Size : 4MB
I (38) boot: Enabling RNG early entropy source...
I (43) boot: Partition Table:
I (45) boot: ## Label            Usage          Type ST Offset   Length
I (52) boot:  0 nvs              WiFi data        01 02 0000d000 00004000
I (58) boot:  1 otadata          OTA data         01 00 00011000 00002000
I (65) boot:  2 phy_init         RF data          01 01 00013000 00001000
I (71) boot:  3 ota_0            OTA app          00 10 00020000 00180000
I (78) boot:  4 ota_1            OTA app          00 11 001a0000 00180000
I (84) boot:  5 factory_nvs      WiFi data        01 02 00320000 00004000
I (91) boot:  6 storage          WiFi data        01 02 00324000 000db000
I (97) boot: End of partition table
I (101) esp_image: segment 0: paddr=00020020 vaddr=420f0020 size=2a9a8h (174504) map
I (140) esp_image: segment 1: paddr=0004a9d0 vaddr=40800000 size=05648h ( 22088) load
I (146) esp_image: segment 2: paddr=00050020 vaddr=42000020 size=e6e00h (945664) map
I (321) esp_image: segment 3: paddr=00136e28 vaddr=40805648 size=0cb6ch ( 52076) load
I (332) esp_image: segment 4: paddr=0014399c vaddr=408121c0 size=02244h (  8772) load
I (339) boot: Loaded app from partition at offset 0x20000
I (339) boot: Disabling RNG early entropy source...
I (350) cpu_start: Unicore app
I (359) cpu_start: Pro cpu start user code
I (359) cpu_start: cpu freq: 80000000 Hz
I (360) app_init: Application information:
I (362) app_init: Project name:     IotGateway
I (367) app_init: App version:      f2c357e8-dirty
I (372) app_init: Compile time:     Apr 30 2025 11:31:37
I (378) app_init: ELF file SHA256:  f3d0134519a70b8f...
I (384) app_init: ESP-IDF:          v5.4-dirty
I (389) efuse_init: Min chip rev:     v0.0
I (394) efuse_init: Max chip rev:     v0.99 
I (399) efuse_init: Chip rev:         v0.0
I (404) heap_init: Initializing. RAM available for dynamic allocation:
I (411) heap_init: At 408226A0 len 00059F70 (359 KiB): RAM
I (417) heap_init: At 4087C610 len 00002F54 (11 KiB): RAM
I (423) heap_init: At 50000000 len 00003FE8 (15 KiB): RTCRAM
I (431) spi_flash: detected chip: generic
I (434) spi_flash: flash io: dio
I (439) sleep_gpio: Configure to isolate all GPIO pins in sleep state
I (446) sleep_gpio: Enable automatic switching of GPIO sleep configuration
I (453) coexist: coex firmware version: 49a8cdc
I (480) coexist: coexist rom version 5b8dcfa
I (481) main_task: Started on CPU0
I (481) main_task: Calling app_main()
I (481) gpio: GPIO[6]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (491) gpio: GPIO[12]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (501) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (571) gpio: GPIO[20]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (571) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (571) gpio: GPIO[3]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (581) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (601) mdns_mem: mDNS task will be created from internal RAM
I (611) OPENTHREAD: Host connection mode none
I (611) phy_init: phy_version 320,348a293,Sep  3 2024,16:33:12
I (661) phy: libbtbb version: 04952fd, Sep  3 2024, 16:33:30
I(671) OPENTHREAD:[I] CslTxScheduler: Bus TX Time: 0 usec, Latency: 0 usec. Calculated CSL Frame Request Ahead: 20000 usec
I(671) OPENTHREAD:[I] ChildSupervsn-: Timeout: 0 -> 190
I(681) OPENTHREAD:[I] Settings------: Read NetworkInfo {rloc:0x4400, extaddr:b6e9944bbbcd46cd, role:router, mode:0x0f, version:5, keyseq:0x0, ...
I(691) OPENTHREAD:[I] Settings------: ... pid:0x4ebb01f4, mlecntr:0x47d153, maccntr:0x49af25, mliid:08877fcfecd9e941}
I (701) OPENTHREAD: OpenThread attached to netif
I(711) OPENTHREAD:[I] Notifier------: StateChanged (0x101fc310) [MLAddr KeySeqCntr NetData Channel PanId NetName ExtPanId NetworkKey PSKc ...
I(721) OPENTHREAD:[I] Notifier------: StateChanged (0x101fc310) ... SecPolicy ActDset]
I(731) OPENTHREAD:[I] AnnounceSender: ChannelMask:{ 11-26 }, period:21500
I(731) OPENTHREAD:[I] AnnounceSender: StartingChannel:15
I(741) OPENTHREAD:[I] AnnounceSender: StartingChannel:15
I(751) OPENTHREAD:[I] RouterTable---: Route table
I (751) gpio: GPIO[10]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (761) main_task: Returned from app_main()
I (781) esp_eth.netif.netif_glue: 40:4c:ca:ff:fe:45
I (781) esp_eth.netif.netif_glue: ethernet attached to netif
I (9901) esp_netif_handlers: eth ip: 192.168.2.120, mask: 255.255.255.0, gw: 192.168.2.1
I (9901) esp_ot_br: Auto-start mode enabled
THREAD_DEBUG: Reading indexes before calling esp_openthread_border_router_init
THREAD_DEBUG: Index esp_openthread_get_backbone_netif: 3
THREAD_DEBUG: Index EthernetGetNetIf: 3
I(9911) OPENTHREAD:[I] SrpServer-----: Selected port 53536
I(9921) OPENTHREAD:[I] NetDataPublshr: Publishing DNS/SRP service unicast (ml-eid, port:53536)
I(9931) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service - State: NoEntry -> ToAdd
I(9941) OPENTHREAD:[I] RoutingManager: Initializing - InfraIfIndex:7
I(9951) OPENTHREAD:[I] InfraIf-------: Init infra netif 7
I(9961) OPENTHREAD:[I] Settings------: Read BrUlaPrefix fd3d:1fcd:a8c6::/48
I(9961) OPENTHREAD:[N] RoutingManager: BR ULA prefix: fd3d:1fcd:a8c6::/48 (loaded)
I(9971) OPENTHREAD:[I] RoutingManager: Generated local OMR prefix: fd3d:1fcd:a8c6:1::/64
I(9981) OPENTHREAD:[I] RoutingManager: Generated local NAT64 prefix: fd3d:1fcd:a8c6:2:0:0::/96
I(9991) OPENTHREAD:[I] RoutingManager: Restored old prefix fdde:ad00:beef:cafe::/64, lifetime:1800
I(10001) OPENTHREAD:[N] RoutingManager: Local on-link prefix: fdde:ad00:beef:cafe::/64
I(10011) OPENTHREAD:[I] RoutingManager: Local on-link prefix state: Removed -> Deprecating (fdde:ad00:beef:cafe::/64)
I(10021) OPENTHREAD:[I] InfraIf-------: State changed: NOT RUNNING -> RUNNING
I(10031) OPENTHREAD:[I] RoutingManager: Enabling
I(10031) OPENTHREAD:[I] BbrLocal------: Add Domain Prefix: ::/0, NotFound
I(10041) OPENTHREAD:[I] BbrLocal------: Add BBR Service: seqno (18), delay (5s), timeout (3600s), InvalidState
I(10051) OPENTHREAD:[I] Settings------: Saved ActiveDataset
I(10051) OPENTHREAD:[I] DatasetManager: Active dataset set
I(10071) OPENTHREAD:[I] DnssdServer---: Started
I (10071) OPENTHREAD: Platform UDP bound to port 49153
I(10071) OPENTHREAD:[I] BbrLocal------: Remove BBR Service: seqno (18), delay (5s), timeout (3600s), NotFound
I(10081) OPENTHREAD:[N] Mle-----------: Role disabled -> detached
I(10091) OPENTHREAD:[I] Mle-----------: Attempt to become router
I(10101) OPENTHREAD:[I] Settings------: Read NetworkInfo {rloc:0x4400, extaddr:b6e9944bbbcd46cd, role:router, mode:0x0f, version:5, keyseq:0x0, ...
I(10111) OPENTHREAD:[I] Settings------: ... pid:0x4ebb01f4, mlecntr:0x47d153, maccntr:0x49af25, mliid:08877fcfecd9e941}
I(10131) OPENTHREAD:[I] Settings------: Saved NetworkInfo {rloc:0x4400, extaddr:b6e9944bbbcd46cd, role:router, mode:0x0f, version:5, keyseq:0x0, ...
I(10141) OPENTHREAD:[I] Settings------: ... pid:0x4ebb01f4, mlecntr:0x47d53c, maccntr:0x49b30d, mliid:08877fcfecd9e941}
I(10151) OPENTHREAD:[I] Mle-----------: Send Link Request (ff02:0:0:0:0:0:0:2)
I(10161) OPENTHREAD:[I] Notifier------: StateChanged (0x1300102d) [Ip6+ Role LLAddr Rloc+ Ip6Mult+ NetifState BbrState ActDset]
I (10171) OPENTHREAD: Platform UDP bound to port 61631
I(10171) OPENTHREAD:[I] Bbr-----------: Start listening on port 61631
I(10181) OPENTHREAD:[I] Bbr-----------: Backbone TMF subscribes ff32:40:fd00:db8:a0:0:0:3: OK
I(10191) OPENTHREAD:[I] BbrManager----: Start Backbone TMF agent: OK
I(10201) OPENTHREAD:[I] AnnounceSender: Stopped
I (10201) OT_STATE: netif up
I (10211) OPENTHREAD: NAT64 ready
I(10221) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:82, chksum:545c, ecn:no, to:0xffff, sec:no, prio:net
I(10221) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(10231) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(15391) OPENTHREAD:[I] Mle-----------: Send Link Request (ff02:0:0:0:0:0:0:2)
I(15401) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:82, chksum:f4c9, ecn:no, to:0xffff, sec:no, prio:net
I(15401) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(15411) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(20771) OPENTHREAD:[I] Mle-----------: Send Link Request (ff02:0:0:0:0:0:0:2)
I(20781) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:82, chksum:00a6, ecn:no, to:0xffff, sec:no, prio:net
I(20781) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(20791) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(22791) OPENTHREAD:[I] BbrLocal------: Remove BBR Service: seqno (18), delay (5s), timeout (3600s), NotFound
I(22791) OPENTHREAD:[N] Mle-----------: RLOC16 4400 -> fffe
I(22801) OPENTHREAD:[I] Mle-----------: AttachState Idle -> Start
I(22801) OPENTHREAD:[I] Notifier------: StateChanged (0x10000040) [Rloc- ActDset]
I (22811) OPENTHREAD: NAT64 ready
I(23051) OPENTHREAD:[N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
I(23051) OPENTHREAD:[I] Mle-----------: AttachState Start -> ParentReq
I(23051) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers (ff02:0:0:0:0:0:0:2)
I(23071) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:3fa6, ecn:no, to:0xffff, sec:no, prio:net
I(23071) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(23081) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(23831) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers (ff02:0:0:0:0:0:0:2)
I(23841) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:8a10, ecn:no, to:0xffff, sec:no, prio:net
I(23841) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(23851) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(24601) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(24611) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:619e, ecn:no, to:0xffff, sec:no, prio:net
I(24611) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(24621) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(25871) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(25881) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:5237, ecn:no, to:0xffff, sec:no, prio:net
I(25881) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(25891) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(27141) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(27151) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:45a3, ecn:no, to:0xffff, sec:no, prio:net
I(27151) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(27161) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
W (27261) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27261) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27271) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27271) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27281) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27361) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27361) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27361) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (27371) OPENTHREAD: Dropping unsupported mldv2 record of type 2
I(28411) OPENTHREAD:[I] Mle-----------: Send Parent Request to routers and REEDs (ff02:0:0:0:0:0:0:2)
I(28421) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:84, chksum:a455, ecn:no, to:0xffff, sec:no, prio:net
I(28421) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(28431) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I(29681) OPENTHREAD:[I] Mle-----------: AttachState ParentReq -> Idle
I(29681) OPENTHREAD:[N] RouterTable---: Allocate router id 17
I(29681) OPENTHREAD:[N] Mle-----------: RLOC16 fffe -> 4400
I(29681) OPENTHREAD:[N] Mle-----------: Role detached -> leader
I(29691) OPENTHREAD:[N] Mle-----------: Partition ID 0x70248bb5
I(29701) OPENTHREAD:[I] RouterTable---: Route table
I(29701) OPENTHREAD:[I] RouterTable---:     17 0x4400 - me - leader
I(29711) OPENTHREAD:[I] Notifier------: StateChanged (0x100012a5) [Ip6+ Role Rloc+ PartitionId NetData Ip6Mult+ ActDset]
I(29721) OPENTHREAD:[I] Mle-----------: Send Data Response (ff02:0:0:0:0:0:0:1)
I(29731) OPENTHREAD:[I] BbrLeader-----: PBBR state: None
I(29751) OPENTHREAD:[I] Settings------: Saved NetworkInfo {rloc:0x4400, extaddr:b6e9944bbbcd46cd, role:leader, mode:0x0f, version:5, keyseq:0x0, ...
I(29751) OPENTHREAD:[I] Settings------: ... pid:0x70248bb5, mlecntr:0x47d545, maccntr:0x49b30d, mliid:08877fcfecd9e941}
I(29761) OPENTHREAD:[I] AnnounceSender: Started
I(29771) OPENTHREAD:[I] SecTransport--: State: Closed -> Open
I (29781) OPENTHREAD: Platform UDP bound to port 49154
I(29781) OPENTHREAD:[I] BorderAgent---: Border Agent start listening on port 49154
I(29791) OPENTHREAD:[I] RoutingManager: RIO Preference changed: low -> medium
I(29801) OPENTHREAD:[I] RoutingManager: Starting
I(29801) OPENTHREAD:[I] RoutingManager: RoutePublisher state: none -> ula
I(29811) OPENTHREAD:[I] NetDataPublshr: Publishing ExternalRoute fc00::/7
I(29821) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fc00::/7 - State: NoEntry -> ToAdd
I(29831) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fc00::/7 (state:ToAdd) in netdata - total:0, preferred:0, desired:10
I(29841) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fc00::/7 - State: ToAdd -> Adding
I(29851) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fc00::/7 (state:Adding) - update in 181 msec
I(29861) OPENTHREAD:[I] RoutingManager: RsSender: Starting - will send first RS in 3 msec
I(29861) OPENTHREAD:[I] RoutingManager: Starting Nat64PrefixManager
I(29871) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:02.338 (2338 msec)
I(29881) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service (state:ToAdd) in netdata - total:0, preferred:0, desired:2
I(29891) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service - State: ToAdd -> Adding
I(29901) OPENTHREAD:[I] NetDataPublshr: DNS/SRP service (state:Adding) - update in 1279 msec
I(29911) OPENTHREAD:[I] NetDataPublshr: ExternalRoute fc00::/7 (state:Adding) in netdata - total:0, preferred:0, desired:10
I(29931) OPENTHREAD:[I] Settings------: Read BorderAgentId {id:b9f1f71efdb22336db86f7feac4fc1cf}
I (29931) OPENTHREAD: NAT64 ready
netif1(7) , netif2(3) en2
E (29941) OPENTHREAD: Failed to get LL address, error: Invalid If index
I(29941) OPENTHREAD:[I] RoutingManager: RsSender: Sent RS 1/3
I(29951) OPENTHREAD:[I] RoutingManager: Received RS from fe80:0:0:0:424c:caff:feff:fe45 on infra netif 7
I(29961) OPENTHREAD:[I] RoutingManager: Will evaluate routing policy in 00:00.086 (86 msec)
I(29971) OPENTHREAD:[I] MeshForwarder-: Sent IPv6 UDP msg, len:96, chksum:f01c, ecn:no, to:0xffff, sec:no, prio:net
I(29981) OPENTHREAD:[I] MeshForwarder-:     src:[fe80:0:0:0:b4e9:944b:bbcd:46cd]:19788
I(29991) OPENTHREAD:[I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:1]:19788
I(30001) OPENTHREAD:[I] RoutingManager: Infraif NAT64 prefix: none
```

**Comment by gytxxsy** [comment]
Hi @diegomartinezvdi 
This appears to be a library compatibility issue: the size of the LWIP-related structures in the BR library does not match the actual structure sizes used in the current LWIP component. I have the following two suggestions:

1. Check the ESP-IDF version you are using, check the commits of both the LWIP component (components/lwip/lwip) and the OpenThread library (components/openthread/lib/).

2. Enable the BR library compatibility check tool via menuconfig:
`idf.py menuconfig → Component config → OpenThread Extension CLI → Enable Espressif's extended features → Enable br lib compatibility check command`
After that, run the compatibility check command from the console, for example:
```bash
> brlibcheck

I (21780) OT_TEST: The offset `ip_addr` checking passed.
I (21780) OT_TEST: The offset `netmask` checking passed.
I (21780) OT_TEST: The offset `gw` checking passed.
I (21780) OT_TEST: The offset `ip6_addr` checking passed.
I (21780) OT_TEST: The offset `ip6_addr_state` checking passed.
I (21780) OT_TEST: The offset `ip6_addr_valid_life` checking passed.
I (21780) OT_TEST: The offset `ip6_addr_pref_life` checking passed.
I (21790) OT_TEST: The offset `input` checking passed.
I (21790) OT_TEST: The offset `output` checking passed.
I (21790) OT_TEST: The offset `linkoutput` checking passed.
I (21790) OT_TEST: The offset `status_callback` checking passed.
I (21790) OT_TEST: The offset `state` checking passed.
I (21790) OT_TEST: The offset `hostname` checking passed.
I (21790) OT_TEST: The offset `hwaddr` checking passed.
I (21790) OT_TEST: The offset `hwaddr_len` checking passed.
I (21790) OT_TEST: The offset `flags` checking passed.
I (21790) OT_TEST: The offset `name` checking passed.
I (21790) OT_TEST: The offset `num` checking passed.
I (21800) OT_TEST: The offset `ip6_autoconfig_enabled` checking passed.
I (21800) OT_TEST: The size of netif struct checking passed.
I (21800) OT_TEST: The br library compatibility checking passed.
Done

```

**Comment by gytxxsy** [comment]
@diegomartinezvdi 
This issue is caused by enabling `LWIP_AUTOIP`. The current version of the br lib does not support AutoIP. You can disable the following three configurations and try again:
```
CONFIG_LWIP_AUTOIP=y
CONFIG_LWIP_AUTOIP_TRIES=10
CONFIG_LWIP_AUTOIP_RATE_LIMIT_INTERVAL=60
```

**Comment by diegomartinezvdi** [comment]
Big thank you @gytxxsy and @chshu for helping me figure out the compatibility issue. I really appreciate your time, everything is working now!
