### ISSUE TITLE
RMT driver crash on C3, 5.3.3 (IDFGH-16191)

### ISSUE THREAD

**Issue by dzungpv** [espressif/esp-idf#17240]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have some device crash with message:
`Panic reason: assert failed: rmt_isr_handle_rx_done rmt_rx.c:576 (offset >= rx_chan->mem_off)`
Especial when wifi low signal

Core dump:
```
Crashed task handle: 0x3fcb00a8, name: 'wifi', GDB name: 'process 1070268584'
Crash happened in the interrupt context
Panic reason: assert failed: rmt_isr_handle_rx_done rmt_rx.c:576 (offset >= rx_chan->mem_off)

================== CURRENT THREAD REGISTERS ===================
ra             0x40389214	0x40389214 <__ubsan_include>
sp             0x3fc9c420	0x3fc9c420 <xIsrStack+1680>
gp             0x3fc98800	0x3fc98800 <ha_preset_set_topic[abi:cxx11]+20>
tp             0x3fcb0090	0x3fcb0090
t0             0x37363534	926299444
t1             0x7271706f	1920036975
t2             0x33323130	858927408
fp             0x78	0x78
s1             0x1	1
a0             0x3fc9c45c	1070187612
a1             0x3fc9adc1	1070181825
a2             0x1	1
a3             0x29	41
a4             0x1	1
a5             0x3fca2000	1070211072
a6             0x7a797877	2054781047
a7             0x76757473	1987409011
s2             0x9	9
s3             0x3fc9c57f	1070187903
s4             0x3fc9adc0	1070181824
s5             0x3fce0000	1070465024
s6             0x3fce0000	1070465024
s7             0x3fce0000	1070465024
s8             0x3ff1b000	1072803840
s9             0x3fce0000	1070465024
s10            0x3fcdf934	1070463284
s11            0x0	0
t3             0x6e6d6c6b	1852664939
t4             0x6a696867	1785292903
t5             0x66656463	1717920867
t6             0x62613938	1650538808
pc             0x4038078c	0x4038078c <panic_abort+18>

==================== CURRENT THREAD STACK =====================
#0  panic_abort (details=details@entry=0x3fc9c45c <xIsrStack+1740> "assert failed: rmt_isr_handle_rx_done rmt_rx.c:576 (offset >= rx_chan->mem_off)") at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/panic.c:463
#1  0x40389214 in esp_system_abort (details=details@entry=0x3fc9c45c <xIsrStack+1740> "assert failed: rmt_isr_handle_rx_done rmt_rx.c:576 (offset >= rx_chan->mem_off)") at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/port/esp_system_chip.c:87
#2  0x4039304a in __assert_func (file=file@entry=0x3c12db60 "rmt_rx.c", line=line@entry=576, func=<optimized out>, func@entry=0x3c149970 <__func__.1> "rmt_isr_handle_rx_done", expr=expr@entry=0x3c12db20 "offset >= rx_chan->mem_off") at /Users/vietdzung/esp/esp-idf-v5.3.x/components/newlib/assert.c:80
#3  0x40384b86 in rmt_isr_handle_rx_done (rx_chan=rx_chan@entry=0x3fca5cd8) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_driver_rmt/src/rmt_rx.c:576
#4  0x40384c8a in rmt_rx_default_isr (args=0x3fca5cd8) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_driver_rmt/src/rmt_rx.c:734
#5  0x4038138c in shared_intr_isr (arg=<optimized out>) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_hw_support/intr_alloc.c:445
#6  0x40396ad4 in _global_interrupt_handler (sp=<optimized out>, mcause=<optimized out>) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/riscv/interrupt.c:90
#7  0x4038026c in _interrupt_handler () at /Users/vietdzung/esp/esp-idf-v5.3.x/components/riscv/vectors.S:359
#8  0x40387930 in enable_timer_group0_for_calibration () at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_hw_support/port/esp32c3/rtc_time.c:212
Backtrace stopped: frame did not save the PC

======================== THREADS INFO =========================
  Id   Target Id          Frame 
* 1    process 1070268584 panic_abort (details=details@entry=0x3fc9c45c <xIsrStack+1740> "assert failed: rmt_isr_handle_rx_done rmt_rx.c:576 (offset >= rx_chan->mem_off)") at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/panic.c:463
  2    process 1070245988 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  3    process 1070324040 0x4038949a in vPortClearInterruptMaskFromISR (prev_int_level=1) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:529
  4    process 1070231800 0x403869e0 in esp_cpu_wait_for_intr () at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_hw_support/cpu.c:64
  5    process 1070332600 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  6    process 1070332952 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  7    process 1070235288 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  8    process 1070227812 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  9    process 1070251816 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  10   process 1070308640 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  11   process 1070225580 0x4038949a in vPortClearInterruptMaskFromISR (prev_int_level=1) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:529
  12   process 1070226296 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
  13   process 1070226792 0x40383600 in esp_crosscore_int_send_yield (core_id=core_id@entry=0) at /Users/vietdzung/esp/esp-idf-v5.3.x/components/esp_system/crosscore_int.c:121
```

**Comment by suda-morris** [comment]
Hi @dzungpv I think this issue was fixed in https://github.com/espressif/esp-idf/commit/0a063c4997b2f8339b0289863bc05e52a8d51c99

It's currently available in release/v5.3 branch, and will be included in the next v5.3.4 release. Please have a try and let me know if it help.

**Comment by dzungpv** [comment]
> Hi [@dzungpv](https://github.com/dzungpv) I think this issue was fixed in [0a063c4](https://github.com/espressif/esp-idf/commit/0a063c4997b2f8339b0289863bc05e52a8d51c99)
> 
> It's currently available in release/v5.3 branch, and will be included in the next v5.3.4 release. Please have a try and let me know if it help.

I will try to apply the fix only, I don't know why latest v5.3 or v5.4 not stable in wifi connection. Report here https://github.com/espressif/arduino-esp32/issues/11340 and now I still have the issue. I try to port project to native ESP IDF still the same.

**Comment by dzungpv** [comment]
And I don't know why 5.3.3 release on Apr 10 but not include the fix https://github.com/espressif/esp-idf/commit/0a063c4997b2f8339b0289863bc05e52a8d51c99 on Mar 20?

**Comment by suda-morris** [comment]
> And I don't know why 5.3.3 release on Apr 10 but not include the fix [0a063c4](https://github.com/espressif/esp-idf/commit/0a063c4997b2f8339b0289863bc05e52a8d51c99) on Mar 20?

Commit date is usually earlier than Merge date. And for some reason, the time window for us to merge backport fix is small. Sometimes the backport is ready but the merge window is closed and have to be postponed to the next time.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of updates, feel free to reopen with more updates.
