### ISSUE TITLE
Crash in `root_port_handle_events()` because of explicit `abort()` (IDFGH-16558)

### ISSUE THREAD

**Issue by cristianghsandu** [espressif/esp-idf#17677]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3

### Espressif SoC revision.

ESP32-S2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

External 3.3V

### What is the expected behavior?

Should not crash when USB device is disconnected.

### What is the actual behavior?

It crashes sometimes when the USB modem is disconnected.
According to my sources it crashes here, in `usb.c`, at line 855, abort() is called.
```
850             case ROOT_PORT_ACTIVE:
851                 // There was an enumerated device. We need to indicate to USBH that the device is gone
852                 pass_event_to_usbh = true;
853                 break;
854             default:
855                 abort();    // Should never occur
856                 break;
857             }
``

### Steps to reproduce.

Connect and disconnect a USB device, not sure if it matters what type.

### Debug Logs.

```plain
Stack trace is as follows:
espcoredump.py v1.14.0
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3ffd8e20, name: 'usb_lib', GDB name: 'process 1073581600'
Crashed task is not in the interrupt context
Panic reason: abort() was called at PC 0x400c2dbf on core 0

================== CURRENT THREAD REGISTERS ===================
exccause       0x1d (StoreProhibitedCause)
excvaddr       0x0
epc1           0x4008b3a0
epc2           0x0
epc3           0x0
epc4           0x0
epc5           0x0
epc6           0x0
eps2           0x0
eps3           0x0
eps4           0x0
eps5           0x0
eps6           0x0
pc             0x40025831          0x40025831 <panic_abort+21>
lbeg           0x0                 0
lend           0x0                 0
lcount         0x0                 0
sar            0x2                 2
ps             0x60023             393251
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             0x8002cafc          -2147300612
a1             0x3ffd8c80          1073581184
a2             0x3ffd8cc0          1073581248
a3             0x3ffd8d0d          1073581325
a4             0xa                 10
a5             0x0                 0
a6             0x1                 1
a7             0x3ffd79fc          1073576444
a8             0x0                 0
a9             0x1                 1
a10            0x3ffd8d0d          1073581325
a11            0x3ffd8d0d          1073581325
a12            0xa                 10
a13            0x0                 0
a14            0x1                 1
a15            0x0                 0

==================== CURRENT THREAD STACK =====================
#0  0x40025831 in panic_abort (details=0x3ffd8cc0 "abort() was called at PC 0x400c2dbf on core 0") at /home/lucian/git/esp-idf/components/esp_system/panic.c:463
#1  0x4002cafc in esp_system_abort (details=0x3ffd8cc0 "abort() was called at PC 0x400c2dbf on core 0") at /home/lucian/git/esp-idf/components/esp_system/port/esp_system_chip.c:92
#2  0x40032e69 in abort () at /home/lucian/git/esp-idf/components/newlib/abort.c:38
#3  0x400c2dc2 in root_port_handle_events (root_port_hdl=<optimized out>) at /home/lucian/git/esp-idf/components/usb/hub.c:855
#4  hub_process () at /home/lucian/git/esp-idf/components/usb/hub.c:1078
#5  0x400bbc40 in usb_host_lib_handle_events (timeout_ticks=<optimized out>, event_flags_ret=<optimized out>) at /home/lucian/git/esp-idf/components/usb/usb_host.c:537
#6  0x400a73ad in Modem::usb_lib_task (arg=0x3ffd7bb4) at /home/lucian/git/lmb-firmware/main/dev/modem/usb.cpp:35
#7  0x4002d861 in vPortTaskWrapper (pxCode=0x400a7394 <Modem::usb_lib_task(void*)>, pvParameters=0x3ffd7bb4) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

======================== THREADS INFO =========================
  Id   Target Id          Frame 
* 1    process 1073581600 0x40025831 in panic_abort (details=0x3ffd8cc0 "abort() was called at PC 0x400c2dbf on core 0") at /home/lucian/git/esp-idf/components/esp_system/panic.c:463
  2    process 1073586064 0x4002d561 in xQueueSemaphoreTake (xQueue=0x3ffda0f0, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1718
  3    process 1073522732 0x4002a732 in esp_cpu_wait_for_intr () at /home/lucian/git/esp-idf/components/esp_hw_support/cpu.c:64
  4    process 1073591000 0x4002d4d6 in xQueueReceive (xQueue=0x3ffda3e4, pvBuffer=0x3ffdb270, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1659
  5    process 1073575788 uxTaskResetEventItemValue () at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5660
  6    process 1073605536 0x4002d4d6 in xQueueReceive (xQueue=0x3ffd15b0, pvBuffer=0x3ffdea98, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1659
  7    process 1073520828 0x4001a8d4 in _xtos_set_intlevel ()
  8    process 1073519588 0x4001a8d4 in _xtos_set_intlevel ()
  9    process 1073535072 prvProcessReceivedCommands () at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/timers.c:856
  10   process 1073595036 0x4002d4d6 in xQueueReceive (xQueue=0x3ffdb4c4, pvBuffer=0x3ffdc1f0, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1659


       TCB             NAME PRIO C/B  STACK USED/FREE
---------- ---------------- -------- ----------------
0x3ffd8e20          usb_lib    11/11         272/3808
0x3ffd9f90          USB-CDC    10/10         320/3760
0x3ffca82c             IDLE      0/0         272/1252
0x3ffdb2d8              tiT    18/18         336/3240
0x3ffd776c       modem_task      2/2        304/18116
0x3ffdeba0   modem ctl task      2/2         480/3600
0x3ffca0bc             main      1/1         400/3680
0x3ffc9be4        esp_timer    22/22         288/3792
0x3ffcd860          Tmr Svc      1/1         240/1792
0x3ffdc29c          sys_evt    20/20         368/2436

==================== THREAD 1 (TCB: 0x3ffd8e20, name: 'usb_lib') =====================
#0  0x40025831 in panic_abort (details=0x3ffd8cc0 "abort() was called at PC 0x400c2dbf on core 0") at /home/lucian/git/esp-idf/components/esp_system/panic.c:463
#1  0x4002cafc in esp_system_abort (details=0x3ffd8cc0 "abort() was called at PC 0x400c2dbf on core 0") at /home/lucian/git/esp-idf/components/esp_system/port/esp_system_chip.c:92
#2  0x40032e69 in abort () at /home/lucian/git/esp-idf/components/newlib/abort.c:38
#3  0x400c2dc2 in root_port_handle_events (root_port_hdl=<optimized out>) at /home/lucian/git/esp-idf/components/usb/hub.c:855
#4  hub_process () at /home/lucian/git/esp-idf/components/usb/hub.c:1078
#5  0x400bbc40 in usb_host_lib_handle_events (timeout_ticks=<optimized out>, event_flags_ret=<optimized out>) at /home/lucian/git/esp-idf/components/usb/usb_host.c:537
#6  0x400a73ad in Modem::usb_lib_task (arg=0x3ffd7bb4) at /home/lucian/git/lmb-firmware/main/dev/modem/usb.cpp:35
#7  0x4002d861 in vPortTaskWrapper (pxCode=0x400a7394 <Modem::usb_lib_task(void*)>, pvParameters=0x3ffd7bb4) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 2 (TCB: 0x3ffd9f90, name: 'USB-CDC') =====================
#0  0x4002d561 in xQueueSemaphoreTake (xQueue=0x3ffda0f0, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1718
#1  0x400bbef8 in usb_host_client_handle_events (client_hdl=0x3ffd27a8, timeout_ticks=4294967295) at /home/lucian/git/esp-idf/components/usb/usb_host.c:757
#2  0x400b9e2a in cdc_acm_client_task (arg=0x0) at /home/lucian/git/lmb-firmware/managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c:196
#3  0x4002d861 in vPortTaskWrapper (pxCode=0x400b9dfc <cdc_acm_client_task>, pvParameters=0x0) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 3 (TCB: 0x3ffca82c, name: 'IDLE') =====================
#0  0x4002a732 in esp_cpu_wait_for_intr () at /home/lucian/git/esp-idf/components/esp_hw_support/cpu.c:64
#1  0x400cdb71 in esp_vApplicationIdleHook () at /home/lucian/git/esp-idf/components/esp_system/freertos_hooks.c:58
#2  0x4002e796 in prvIdleTask (pvParameters=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:4344
#3  0x4002d861 in vPortTaskWrapper (pxCode=0x4002e73c <prvIdleTask>, pvParameters=0x0) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 4 (TCB: 0x3ffdb2d8, name: 'tiT') =====================
#0  0x4002d4d6 in xQueueReceive (xQueue=0x3ffda3e4, pvBuffer=0x3ffdb270, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1659
#1  0x400eaa6a in sys_arch_mbox_fetch (mbox=0x3ffc7dbc <tcpip_mbox>, msg=0x3ffdb270, timeout=<optimized out>) at /home/lucian/git/esp-idf/components/lwip/port/freertos/sys_arch.c:317
#2  0x400d9673 in tcpip_timeouts_mbox_fetch (mbox=<optimized out>, msg=<optimized out>) at /home/lucian/git/esp-idf/components/lwip/lwip/src/api/tcpip.c:104
#3  tcpip_thread (arg=0x0) at /home/lucian/git/esp-idf/components/lwip/lwip/src/api/tcpip.c:142
#4  0x4002d861 in vPortTaskWrapper (pxCode=0x400d962c <tcpip_thread>, pvParameters=0x0) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 5 (TCB: 0x3ffd776c, name: 'modem_task') =====================
#0  uxTaskResetEventItemValue () at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5660
#1  0x4002e1d8 in xEventGroupWaitBits (xEventGroup=0x3ffd14f8, uxBitsToWaitFor=36, xClearOnExit=0, xWaitForAllBits=0, xTicksToWait=7000) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/event_groups.c:438
#2  0x400a2d40 in Modem::wait_powered_down (this=0x3ffd1458, timeout=7000) at /home/lucian/git/lmb-firmware/main/dev/modem/modem.cpp:895
#3  0x4008f518 in modem_task (task_args=<optimized out>) at /home/lucian/git/lmb-firmware/main/tasks/modem_task.cpp:458
#4  0x4002d861 in vPortTaskWrapper (pxCode=0x4008f0c0 <modem_task(void*)>, pvParameters=0x3ffccfa8) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 6 (TCB: 0x3ffdeba0, name: 'modem ctl task') =====================
#0  0x4002d4d6 in xQueueReceive (xQueue=0x3ffd15b0, pvBuffer=0x3ffdea98, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1659
#1  0x400a8672 in Modem::ctl_wait_for_event (this=0x3ffd1458, req=...) at /home/lucian/git/lmb-firmware/main/dev/modem/ctl.cpp:260
#2  0x400a9396 in Modem::ctl_loop (this=0x3ffd1458) at /home/lucian/git/lmb-firmware/main/dev/modem/ctl.cpp:509
#3  0x400a13f5 in operator() (__closure=0x0, arg=0x3ffd1458) at /home/lucian/git/lmb-firmware/main/dev/modem/modem.cpp:127
#4  _FUN () at /home/lucian/git/lmb-firmware/main/dev/modem/modem.cpp:135
#5  0x4002d861 in vPortTaskWrapper (pxCode=0x400a13e0 <_FUN(void*)>, pvParameters=0x3ffd1458) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 7 (TCB: 0x3ffca0bc, name: 'main') =====================
#0  0x4001a8d4 in _xtos_set_intlevel ()
#1  0x4002d970 in vPortClearInterruptMaskFromISR (prev_level=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:560
#2  vPortExitCritical (mux=0x3ffc4304 <xKernelLock>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:504
#3  vPortExitCritical (mux=0x3ffc4304 <xKernelLock>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:489
#4  0x4002f0f2 in vTaskSuspend (xTaskToSuspend=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:2060
#5  0x4008c163 in start_modem_if_necessary (is_led_en=true, is_gsm_en=<optimized out>) at /home/lucian/git/lmb-firmware/main/lmb-firmware.cpp:369
#6  app_main () at /home/lucian/git/lmb-firmware/main/lmb-firmware.cpp:399
#7  0x4012b872 in main_task (args=0x0) at /home/lucian/git/esp-idf/components/freertos/app_startup.c:208
#8  0x4002d861 in vPortTaskWrapper (pxCode=0x4012b7fc <main_task>, pvParameters=0x0) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 8 (TCB: 0x3ffc9be4, name: 'esp_timer') =====================
#0  0x4001a8d4 in _xtos_set_intlevel ()
#1  0x4002d970 in vPortClearInterruptMaskFromISR (prev_level=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:560
#2  vPortExitCritical (mux=0x3ffc4304 <xKernelLock>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:504
#3  vPortExitCritical (mux=0x3ffc4304 <xKernelLock>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:489
#4  0x4002f9b5 in ulTaskGenericNotifyTake (uxIndexToWait=<optimized out>, xClearCountOnExit=1, xTicksToWait=4294967295) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5756
#5  0x400d006d in timer_task (arg=0x0) at /home/lucian/git/esp-idf/components/esp_timer/src/esp_timer.c:480
#6  0x4002d861 in vPortTaskWrapper (pxCode=0x400d005c <timer_task>, pvParameters=0x0) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 9 (TCB: 0x3ffcd860, name: 'Tmr Svc') =====================
#0  prvProcessReceivedCommands () at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/timers.c:856
#1  prvTimerTask (pvParameters=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/timers.c:688
#2  0x4002d861 in vPortTaskWrapper (pxCode=0x4002ddc0 <prvTimerTask>, pvParameters=0x0) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

==================== THREAD 10 (TCB: 0x3ffdc29c, name: 'sys_evt') =====================
#0  0x4002d4d6 in xQueueReceive (xQueue=0x3ffdb4c4, pvBuffer=0x3ffdc1f0, xTicksToWait=<optimized out>) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1659
#1  0x4012a5c0 in esp_event_loop_run (event_loop=0x3ffdb49c, ticks_to_run=4294967295) at /home/lucian/git/esp-idf/components/esp_event/esp_event.c:560
#2  0x4012a5dd in esp_event_loop_run_task (args=0x3ffdb49c) at /home/lucian/git/esp-idf/components/esp_event/esp_event.c:105
#3  0x4002d861 in vPortTaskWrapper (pxCode=0x4012a5cc <esp_event_loop_run_task>, pvParameters=0x3ffdb49c) at /home/lucian/git/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134


======================= ALL MEMORY REGIONS ========================
Name   Address   Size   Attrs
.rtc.text 0x40070000 0x2c R XA
.rtc.force_fast 0x3ff9e02c 0x4 RW A
.rtc.data 0x50000000 0x43 RW A
.rtc.force_slow 0x50000044 0x0 RW  
.iram0.vectors 0x40024000 0x403 R XA
.iram0.text 0x40024404 0xfe9c R XA
.dram0.data 0x3ffc42a0 0x2020 RW A
.ext_ram.bss 0x3f800000 0x0 RW  
.flash.appdesc 0x3f000020 0x100 R  A
.flash.rodata 0x3f000120 0x33708 RW A
.flash.text 0x40080020 0xac10e R XA
.iram0.text_end 0x400342a0 0x0 RW  
.dram0.heap_start 0x3ffc8eb8 0x0 RW  
.coredump.tasks.data 0x3ffd8e20 0x150 RW 
.coredump.tasks.data 0x3ffd8bf0 0x210 RW 
.coredump.tasks.data 0x3ffd9f90 0x150 RW 
.coredump.tasks.data 0x3ffd9e30 0x140 RW 
.coredump.tasks.data 0x3ffca82c 0x150 RW 
.coredump.tasks.data 0x3ffca700 0x110 RW 
.coredump.tasks.data 0x3ffdb2d8 0x150 RW 
.coredump.tasks.data 0x3ffdb170 0x150 RW 
.coredump.tasks.data 0x3ffd776c 0x150 RW 
.coredump.tasks.data 0x3ffd7620 0x130 RW 
.coredump.tasks.data 0x3ffdeba0 0x150 RW 
.coredump.tasks.data 0x3ffde9a0 0x1e0 RW 
.coredump.tasks.data 0x3ffca0bc 0x150 RW 
.coredump.tasks.data 0x3ffccea0 0x190 RW 
.coredump.tasks.data 0x3ffc9be4 0x150 RW 
.coredump.tasks.data 0x3ffcbf00 0x120 RW 
.coredump.tasks.data 0x3ffcd860 0x150 RW 
.coredump.tasks.data 0x3ffcd750 0xf0 RW 
.coredump.tasks.data 0x3ffdc29c 0x150 RW 
.coredump.tasks.data 0x3ffdc110 0x170 RW 

===================== ESP32 CORE DUMP END =====================
===============================================================
Done!
```

### Diagnostic report archive.

[diag-524c1e33-9437-4cc3-ab3a-2c49653be33e.zip](https://github.com/user-attachments/files/22634054/diag-524c1e33-9437-4cc3-ab3a-2c49653be33e.zip)

**Comment by tore-espressif** [comment]
Hello @cristianghsandu , thank you for the report.
We have encountered issues with similar symptoms before and it should be already fixed in latest [5.3.4](https://github.com/espressif/esp-idf/releases/tag/v5.3.4) release. Can you please try updating to 5.3.4 and try again?

**Comment by crazyquark** [comment]
Hello @tore-espressif , thanks for the quick response, we will try v5.3.4. Could you share what the fix was for this issue?

**Comment by tore-espressif** [comment]
We 'accidentally' fixed it while we reworked the logic for external HUBs. IIRC, the problem disappeared after https://github.com/espressif/esp-idf/commit/a602befe1b48d8d7529e23d60c9bf04c3ac520f7 , so 5.3.1 should be first good release.

**Comment by tore-espressif** [comment]
@cristianghsandu is the original issue solved? can we close this issue?

**Comment by tore-espressif** [comment]
Closing as the issue is fixed in latest releases. Feel free to reopen if there are any more questions

**Comment by cristianghsandu** [comment]
Aa far as I can tell, it no longer happens in 5.3.2 but still happens in 5.3.1.
