### ISSUE TITLE
fatfs open("xx",O_CREAT|O_WRONLY,0666) fails

### ISSUE THREAD

**Issue by maierkomor** [espressif/esp-idf#1817]
An open call to create a file on a fatfs on spi flash fails with "no such file or directory". In contrast, fopen works without a problem.

**Comment by Reiner1210** [comment]
you use xx ? Or /sdcard/xx ?

**Comment by FayeY** [comment]
@maierkomor , any update? Is this issue solved now?

**Comment by comp500** [comment]
This is still an issue; the [`fat_mode_conv` function](https://github.com/espressif/esp-idf/blob/175e5fc260bedaa17d0e55788fa5c36ba3076a72/components/fatfs/vfs/vfs_fat.c#L252) handles `O_CREAT` with `O_EXCL` or `O_TRUNC` correctly, but falls back to `FA_OPEN_EXISTING` (failing when the file doesn't exist) with just `O_CREAT`.
