### ISSUE TITLE
Interrupt wdt timeout when repeatedly enabling/disable BT controller and BLE adv (IDFGH-492)

### ISSUE THREAD

**Issue by ghost** [espressif/esp-idf#2798]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it): v3.3-dev-396-g8c7a6be
- Build System:         [Make]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 1.22.0-80-g6c4433a
- Operating System:     [Linux]
- Power Supply:         [USB]

## Problem Description

Recently when updating to latest ESP-IDF we started experiencing interrupt watchdog timeout crashes related to enabling/disabling BLE advertisements. I was able to reproduce the problem by patching the ble_adv example code. Bisected the problem and found it started when the following patch (in components/bt/lib) got in:

commit cd196645e29d0d7b050c1aadec850d285fbb1da6
Author: Tian Hao <tianhao@espressif.com>
Date:   Tue Nov 13 17:28:03 2018 +0800

```
    fix controller disable cause some problem bug (ac67b340)
    
    1. Fix the bug that disable controller suddenly cause crash when ble is working. (585cfba1)
    2. Fix the bug that when disable controller, it will cause wifi cannot RX,  TX timeout,  buffer lack and etc. (f8546145)
    3. Update dport access as the newest version of IDF. (ac67b340)
```

### Expected Behavior
1. Enable Bluetooth controller
2. Start BLE adv
3. Stop BLE adv
4. Disable Bluetooth controller
5. Repeat from 1.

No crash should be seen

### Actual Behavior
Already second time BLE adv is started an interrupt wdt reset is seen.

### Steps to repropduce

1. Apply the attached patch to esp-idf repo
2. Build and flash the ble_adv example code with default defconfig
3. Let example code run for just a few seconds
4. Notice the crash.

### Code to reproduce this issue

Please see the attached patch file to be applied to esp-idf repo.

## Debug Logs

```
Toolchain path: esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
Python requirements from esp/esp-idf/requirements.txt are satisfied.
MONITOR
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6220
load:0x40078000,len:10248
load:0x40080400,len:6552
entry 0x40080764
I (29) boot: ESP-IDF v3.3-dev-397-ga03fd47-dirty 2nd stage bootloader
I (29) boot: compile time 11:23:13
I (30) boot: Enabling RNG early entropy source...
I (35) boot: SPI Speed      : 40MHz
I (39) boot: SPI Mode       : DIO
I (43) boot: SPI Flash Size : 4MB
I (47) boot: Partition Table:
I (51) boot: ## Label            Usage          Type ST Offset   Length
I (58) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (66) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (73) boot:  2 factory          factory app      00 00 00010000 00100000
I (81) boot: End of partition table
I (85) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x0ed4c ( 60748) map
I (115) esp_image: segment 1: paddr=0x0001ed74 vaddr=0x3ff80000 size=0x00000 (     0) load
I (115) esp_image: segment 2: paddr=0x0001ed7c vaddr=0x3ff80000 size=0x00000 (     0) load
I (122) esp_image: segment 3: paddr=0x0001ed84 vaddr=0x3ffbdb60 size=0x0128c (  4748) load
I (133) esp_image: segment 4: paddr=0x00020018 vaddr=0x400d0018 size=0x3a254 (238164) map
0x400d0018: _stext at ??:?

I (223) esp_image: segment 5: paddr=0x0005a274 vaddr=0x3ffbedec size=0x0155c (  5468) load
I (225) esp_image: segment 6: paddr=0x0005b7d8 vaddr=0x3ffc0348 size=0x00000 (     0) load
I (230) esp_image: segment 7: paddr=0x0005b7e0 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at esp/esp-idf/components/freertos/xtensa_vectors.S:1685

I (239) esp_image: segment 8: paddr=0x0005bbe8 vaddr=0x40080400 size=0x11514 ( 70932) load
I (277) esp_image: segment 9: paddr=0x0006d104 vaddr=0x400c0000 size=0x00000 (     0) load
I (277) esp_image: segment 10: paddr=0x0006d10c vaddr=0x50000000 size=0x00000 (     0) load
I (284) esp_image: segment 11: paddr=0x0006d114 vaddr=0x50000000 size=0x00000 (     0) load
I (303) boot: Loaded app from partition at offset 0x10000
I (303) boot: Disabling RNG early entropy source...
I (305) cpu_start: Pro cpu up.
I (308) cpu_start: Application information:
I (313) cpu_start: Project name:     ble_adv
I (318) cpu_start: App version:      v3.3-dev-397-ga03fd47-dirty
I (325) cpu_start: Compile time:     11:23:12
I (330) cpu_start: Compile date:     Dec  6 2018
I (335) cpu_start: ESP-IDF:          v3.3-dev-397-ga03fd47-dirty
I (342) cpu_start: Starting app cpu, entry point is 0x40081058
0x40081058: call_start_cpu1 at esp/esp-idf/components/esp32/cpu_start.c:261

I (0) cpu_start: App cpu up.
I (352) heap_init: Initializing. RAM available for dynamic allocation:
I (359) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (365) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (371) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (377) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (383) heap_init: At 3FFC2D78 len 0001D288 (116 KiB): DRAM
I (390) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (396) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (402) heap_init: At 40091914 len 0000E6EC (57 KiB): IRAM
I (409) cpu_start: Pro cpu start user code
I (91) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (177) BTDM_INIT: BT controller compile version [ac67b34]
I (177) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
BLE advt task start
I (1257) phy: phy_version: 4000, b6198fa, Sep  3 2018, 15:11:06, 0, 0
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 1
host rcv pkt: 040e0405030c00
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 2
host rcv pkt: 040e0405062000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 3
host rcv pkt: 040e0405082000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 4
host rcv pkt: 040e04050a2000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 5
host rcv pkt: 0413050109000000
host rcv pkt: 040e04050a2000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 6
BLE Advertise, flag_send_avail: 1, cmd_sent: 7
BLE Advertise, flag_send_avail: 1, cmd_sent: 1
host rcv pkt: 040e0405030c00
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 2
host rcv pkt: 040e0405062000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 3
host rcv pkt: 040e0405082000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 4
host rcv pkt: 040e04050a2000
controller rcv pkt ready
BLE Advertise, flag_send_avail: 1, cmd_sent: 5
ASSERT_PARAM(512 0), in rwble.c at line 222
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0)
Core 0 register dump:
PC      : 0x400846d1  PS      : 0x00060034  A0      : 0x80087cee  A1      : 0x3ffbe620  
0x400846d1: r_assert_param at ??:?

A2      : 0x00000001  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x60008054  
A6      : 0x3ffbdbbc  A7      : 0x60008050  A8      : 0x800846d1  A9      : 0x3ffbe600  
A10     : 0x00000004  A11     : 0x00000000  A12     : 0x6000804c  A13     : 0xffffffff  
A14     : 0x00000000  A15     : 0xfffffffc  SAR     : 0x00000004  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x40084609  LEND    : 0x40084610  LCOUNT  : 0x00000000  
0x40084609: r_assert_param at ??:?

0x40084610: r_assert_param at ??:?

Core 0 was running in ISR context:
EPC1    : 0x40109bbe  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x400846d1
0x40109bbe: esp_pm_impl_waiti at esp/esp-idf/components/esp32/pm_esp32.c:487

0x400846d1: r_assert_param at ??:?


Backtrace: 0x400846d1:0x3ffbe620 0x40087ceb:0x3ffbe640 0x400888b7:0x3ffbe660 0x400825e1:0x3ffbe680 0x40109bbb:0x00000000
0x400846d1: r_assert_param at ??:?

0x40087ceb: r_rwble_isr at ??:?

0x400888b7: r_rwbtdm_isr_wrapper at intc.c:?

0x400825e1: _xt_lowint1 at esp/esp-idf/components/freertos/xtensa_vectors.S:1105

0x40109bbb: esp_pm_impl_waiti at esp/esp-idf/components/esp32/pm_esp32.c:487


Core 1 register dump:
PC      : 0x40109bbe  PS      : 0x00060634  A0      : 0x800d187e  A1      : 0x3ffbc330  
0x40109bbe: esp_pm_impl_waiti at esp/esp-idf/components/esp32/pm_esp32.c:487

A2      : 0x00000000  A3      : 0x80000001  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0x00000003  A7      : 0x00060023  A8      : 0x800d2892  A9      : 0x3ffbc300  
A10     : 0x00000000  A11     : 0x00060623  A12     : 0x00060620  A13     : 0x00000001  
A14     : 0x00060620  A15     : 0x3ffbd250  SAR     : 0x00000000  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40109bbe:0x3ffbc330 0x400d187b:0x3ffbc350 0x4008fc11:0x3ffbc370 0x4008ec55:0x3ffbc390
0x40109bbe: esp_pm_impl_waiti at esp/esp-idf/components/esp32/pm_esp32.c:487

0x400d187b: esp_vApplicationIdleHook at esp/esp-idf/components/esp32/freertos_hooks.c:86

0x4008fc11: prvIdleTask at esp/esp-idf/components/freertos/tasks.c:3537

0x4008ec55: vPortTaskWrapper at esp/esp-idf/components/freertos/port.c:403


Rebooting...
```

## Other items if possible

esp-idf patch file to apply for reproducing the problem

[0001-Repeatedly-turn-on-off-bt-controller-and-ble-adverti.patch.txt](https://github.com/espressif/esp-idf/files/2652904/0001-Repeatedly-turn-on-off-bt-controller-and-ble-adverti.patch.txt)

**Comment by mikaelkanstrup** [comment]
@Weijian-Espressif I saw that fix and tried with an updated IDF already but unfortunately that didn't solve the problem. Updated today to latest IDF (v3.3-beta1-44-gda2116f) but problem is still there.

The patch I attached to this case reproduces the problem within less than a minute. Can you please check if you're able to reproduce the problem with this?

**Comment by Weijian-Espressif** [comment]
@mikaelkanstrup, I reproduced this bug . We have fixed this bug and are doing stress testing. If the code is merged into IDF, I will notify you in time, thanks.

**Comment by mikaelkanstrup** [comment]
@Weijian-Espressif Ok great. Thanks!

**Comment by ViXXoR** [comment]
I am still experiencing this exact problem on v3.3 right now.
I can disable BLE, sleep, wake up, enable BLE all with no issues. As soon as I try to advertise, the chip resets.
Was there a fix for this that just didn't make it into v3.3?

**Comment by ViXXoR** [comment]
For anyone who may come here looking for a work-around like I did, here is my solution:

I completely deinit the bt/ble stack before going to sleep:
```
esp_bluedroid_disable();
esp_bluedroid_deinit();
esp_bt_controller_disable();
esp_bt_controller_deinit();
```
Then bring it all back up when waking:
```
esp_bt_controller_init(&bt_cfg);
esp_bt_controller_enable(ESP_BT_MODE_BLE);
esp_bluedroid_init();
esp_bluedroid_enable();
```
Doing it this way seems to work for me right now.

**Comment by sowmimalu** [comment]
hai ,
i am working on dual mode at first its working . when i disable the mode as like the above form its disable the mode but not able to enable again ..can you please tell me??

**Comment by GYC-Espressif** [comment]
Hello @sowmimalu , we have known this issue and the solution is under test. For now, if you want to close the Bluetooth functions, we recommend you do the following things.
```
esp_bluedroid_disable();
esp_bluedroid_deinit();
esp_bt_controller_disable();
esp_bt_controller_deinit();
```
And you can restart the Bluetooth functions whit following things.
```
esp_bt_controller_init(&bt_cfg);
esp_bt_controller_enable(ESP_BT_MODE_BLE);
esp_bluedroid_init();
esp_bluedroid_enable();
```
And I will inform you here when the fix solution is release. Thank you.

**Comment by jack0c** [comment]
This is fixed in version after release/v3.3
