### ISSUE TITLE
esp-idf-tools-setup-2.1 Fail to Install - Windows 10 (IDFGH-2189)

### ISSUE THREAD

**Issue by mikeoto** [espressif/esp-idf#4341]
## Environment

- Development Kit:      [ESP32-Wroom]
- Kit version (for DevKitC): [v4]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version (run ``git describe --tags`` to find it): 
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description
Here is my install paths:

**Using Python 3.6:
      C:\Users\Michael Bot\AppData\Local\Programs\Python\Python36-32\python.exe

Using Git 2.21.0.windows.1:
      C:\Program Files\Git\cmd\git.exe

Using existing ESP-IDF copy: 
      C:\esp\esp-idf

IDF tools directory (IDF_TOOLS_PATH):
      C:\esp32

Running esp-idf-tools-setup-2.1.exe, I get errors as follows:

Running command: C:\Users\Michael Bot\AppData\Local\Programs\Python\Python36-32\python.exe C:\esp\esp-idf\tools\idf_tools.py install-python-env
                          Using base prefix 'C:\\Users\\Michael Bot\\AppData\\Local\\Programs\\Python\\Python36-32'
                          New python executable in C:\esptools\.espressif\python_env\idf4.1_py3.6_env\Scripts\python.exe
                          Installing setuptools, pip, wheel...
                          done.
                          Processing \\${idf_path}\tools\kconfig_new\esp-windows-curses
                          ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '\\\\${IDF_PATH}\\tools\\kconfig_new\\esp-windows-curses'
                          
                          Creating a new Python environment in C:\esptools\.espressif\python_env\idf4.1_py3.6_env
                          Installing Python packages from C:\esp\esp-idf\requirements.txt
                          Traceback (most recent call last):
                            File "C:\esp\esp-idf\tools\idf_tools.py", line 1349, in <module>
                              main(sys.argv[1:])
                            File "C:\esp\esp-idf\tools\idf_tools.py", line 1345, in main
                              action_func(args)
                            File "C:\esp\esp-idf\tools\idf_tools.py", line 1163, in action_install_python_env
                              subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr)
                            File "C:\Users\Michael Bot\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 291, in check_call
                              raise CalledProcessError(retcode, cmd)
                          subprocess.CalledProcessError: Command '['C:\\esptools\\.espressif\\python_env\\idf4.1_py3.6_env\\Scripts\\python.exe', '-m', 'pip', 'install', '--no-warn-script-location', '-r', 'C:\\esp\\esp-idf\\requirements.

Let me know if there is something I'm missing.

**Comment by joeynoodlesfang** [comment]
Second that, same issue.

**Comment by dobairoland** [comment]
Are you sure that you have IDF v3.2? Maybe `IDF_PATH` points to the wrong directory?

The failure regarding `esp-windows-curses` indicates that the installer is using the `requirements.txt` file included only in IDF v4.1.

**Comment by mikeoto** [comment]
If I was using the IDF Tools Installer, how could I have an incorrect IDF? I am able to get this system running by downloading and installing the parts individually but if you don't do that, the installer doesn't seem to be working correctly.

**Comment by flufsor** [comment]
I fixed it with a manually downloaded esp-idf from github, and setting up the IDF_PATH variable pointing to it.
Its a temp fix but works atleast.

**Comment by mikeoto** [comment]
my manual install isnt working right. I was able to get it to compile and flash one time but then the path was lost after exiting cmd. When I tried to install again, the install.bat cant find some components and starts to download everything from scratch. Very frustrating. Is there an easier way to do this? Should I stick to using the msys32 instead of the Cmake system?

I think I was using the V4.1 version instead of V3.2, its very hard to find out if Im having problems with installation.

**Comment by keelung-yang** [comment]
> I fixed it with a manually downloaded esp-idf from github, and setting up the IDF_PATH variable pointing to it.
> Its a temp fix but works atleast.

@flufsor I tried your solution on Win10 64 bit and Python 3.8 64 bit, but still not works.

@igrr  Maybe it's caused by **esp-2019r2-8.2.0**, esp-idf-tools-setup-2.1.exe works on **r1** version as I remembered.

**Comment by igrr** [comment]
No, this is caused by the fact that the installer didn't set IDF_PATH before invoking the Python packages installation process. Since requirements.txt now uses IDF_PATH variable, it leads to this error.

The fix has been merged on our end, but due to some infrastructure issues it hasn't synced to GitHub yet. This issue will be updated when this happens. Until then, please use release/v4.0 branch as a workaround.

**Comment by 804enl** [comment]
I have been trying to install ESP-IDF with
 https://dl.espressif.com/dl/esp-idf-tools-setup-2.3.exe
but it fails because windows 10 does have xcopy.
I tried 
https://dl.espressif.com/dl/esp-idf-tools-setup-2.2.exe
But it fails near the finish, because it is missing a file,
Can you please help I have been trying for more then a couple of days.
I was useing Arduino but could not get the esp32 to run bluetooth or WiFi.
I am using a( EASY Kit esp32-C1 ) board.
Can you please help
Kind regards James Webster Email: james.webster2@bigpond.com

**Comment by igrr** [comment]
@804enl could you please attach the setup error log you got with esp-idf-tools-setup-2.3.exe?

**Comment by 804enl** [comment]
OK Thank youAs soon as I get back to my computer Regards James Sent from my Samsung Mobile on the Telstra Mobile Network
-------- Original message --------From: Ivan Grokhotkov <notifications@github.com> Date: 14/4/20  5:31 am  (GMT+10:00) To: espressif/esp-idf <esp-idf@noreply.github.com> Cc: 804enl <james.webster2@bigpond.com>, Mention <mention@noreply.github.com> Subject: Re: [espressif/esp-idf] esp-idf-tools-setup-2.1 Fail to Install - Windows 10 (IDFGH-2189) (#4341) 
@804enl could you please attach the setup error log you got with esp-idf-tools-setup-2.3.exe?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/espressif/esp-idf/issues/4341#issuecomment-613056711",
"url": "https://github.com/espressif/esp-idf/issues/4341#issuecomment-613056711",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 804enl** [comment]
Hi Ivan
Here is the log 
hope this helps
Regards James Webster

------ Original Message ------

**Comment by 804enl** [comment]
Goog day Ivan 
This is the log from:  esp-idf-tools-setup-2.2.exe
I though this might help
Regards James Webster
------ Original Message ------

**Comment by 804enl** [comment]
Hi Ivan
Did not realise I should have posted the Log file for  "esp-idf-tools-setup-2.3.exe"
hear.
Ishould have said that windows 10 does NOT have xcopy.
Hope this helps
This is the file, Thank you.
2020-04-14 10:08:02.235   Log opened. (Time zone: UTC+10:00)
2020-04-14 10:08:02.235   Setup version: Inno Setup version 6.0.2 (u)
2020-04-14 10:08:02.235   Original Setup EXE: D:\A A ELECTRONICS and  ATMEL\ESP-IDF\ESP IDF TOOLS\esp-idf-tools-setup-2.3.exe
2020-04-14 10:08:02.235   Setup command line: /SL5="$708F2,350580993,721408,D:\A A ELECTRONICS and  ATMEL\ESP-IDF\ESP IDF TOOLS\esp-idf-tools-setup-2.3.exe" 
2020-04-14 10:08:02.235   Windows version: 10.0.16299  (NT platform: Yes)
2020-04-14 10:08:02.236   64-bit Windows: Yes
2020-04-14 10:08:02.236   Processor architecture: x64
2020-04-14 10:08:02.247   User privileges: None
2020-04-14 10:08:02.257   Administrative install mode: No
2020-04-14 10:08:02.257   Install mode root key: HKEY_CURRENT_USER
2020-04-14 10:08:02.257   64-bit install mode: Yes
2020-04-14 10:08:02.297   Created temporary directory: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp
2020-04-14 10:08:02.652   -- DLL function import --
2020-04-14 10:08:02.652   Function name: idpAddFile
2020-04-14 10:08:02.652   DLL name: files:idp.dll
2020-04-14 10:08:02.652   Extracting temporary file: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.741   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.741   Importing the DLL function.
2020-04-14 10:08:02.763   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.763   -- DLL function import --
2020-04-14 10:08:02.763   Function name: idpAddFileComp
2020-04-14 10:08:02.763   DLL name: files:idp.dll
2020-04-14 10:08:02.764   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.764   Importing the DLL function.
2020-04-14 10:08:02.764   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.764   -- DLL function import --
2020-04-14 10:08:02.764   Function name: idpAddMirror
2020-04-14 10:08:02.764   DLL name: files:idp.dll
2020-04-14 10:08:02.764   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.764   Importing the DLL function.
2020-04-14 10:08:02.764   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.764   -- DLL function import --
2020-04-14 10:08:02.764   Function name: idpAddFtpDir
2020-04-14 10:08:02.764   DLL name: files:idp.dll
2020-04-14 10:08:02.765   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.765   Importing the DLL function.
2020-04-14 10:08:02.765   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.765   -- DLL function import --
2020-04-14 10:08:02.765   Function name: idpAddFtpDirComp
2020-04-14 10:08:02.765   DLL name: files:idp.dll
2020-04-14 10:08:02.765   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.765   Importing the DLL function.
2020-04-14 10:08:02.765   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.765   -- DLL function import --
2020-04-14 10:08:02.765   Function name: idpClearFiles
2020-04-14 10:08:02.765   DLL name: files:idp.dll
2020-04-14 10:08:02.766   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.766   Importing the DLL function.
2020-04-14 10:08:02.766   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.766   -- DLL function import --
2020-04-14 10:08:02.766   Function name: idpFilesCount
2020-04-14 10:08:02.766   DLL name: files:idp.dll
2020-04-14 10:08:02.766   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.766   Importing the DLL function.
2020-04-14 10:08:02.766   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.766   -- DLL function import --
2020-04-14 10:08:02.766   Function name: idpFtpDirsCount
2020-04-14 10:08:02.766   DLL name: files:idp.dll
2020-04-14 10:08:02.766   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.766   Importing the DLL function.
2020-04-14 10:08:02.767   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.767   -- DLL function import --
2020-04-14 10:08:02.767   Function name: idpFileDownloaded
2020-04-14 10:08:02.767   DLL name: files:idp.dll
2020-04-14 10:08:02.767   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.767   Importing the DLL function.
2020-04-14 10:08:02.767   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.767   -- DLL function import --
2020-04-14 10:08:02.767   Function name: idpFilesDownloaded
2020-04-14 10:08:02.767   DLL name: files:idp.dll
2020-04-14 10:08:02.767   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.767   Importing the DLL function.
2020-04-14 10:08:02.767   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.767   -- DLL function import --
2020-04-14 10:08:02.767   Function name: idpDownloadFile
2020-04-14 10:08:02.767   DLL name: files:idp.dll
2020-04-14 10:08:02.768   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.768   Importing the DLL function.
2020-04-14 10:08:02.768   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.768   -- DLL function import --
2020-04-14 10:08:02.768   Function name: idpDownloadFiles
2020-04-14 10:08:02.768   DLL name: files:idp.dll
2020-04-14 10:08:02.768   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.768   Importing the DLL function.
2020-04-14 10:08:02.768   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.768   -- DLL function import --
2020-04-14 10:08:02.768   Function name: idpDownloadFilesComp
2020-04-14 10:08:02.768   DLL name: files:idp.dll
2020-04-14 10:08:02.768   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.768   Importing the DLL function.
2020-04-14 10:08:02.768   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.768   -- DLL function import --
2020-04-14 10:08:02.768   Function name: idpDownloadFilesCompUi
2020-04-14 10:08:02.768   DLL name: files:idp.dll
2020-04-14 10:08:02.768   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.769   Importing the DLL function.
2020-04-14 10:08:02.769   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.769   -- DLL function import --
2020-04-14 10:08:02.769   Function name: idpStartDownload
2020-04-14 10:08:02.769   DLL name: files:idp.dll
2020-04-14 10:08:02.769   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.769   Importing the DLL function.
2020-04-14 10:08:02.769   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.769   -- DLL function import --
2020-04-14 10:08:02.769   Function name: idpStopDownload
2020-04-14 10:08:02.769   DLL name: files:idp.dll
2020-04-14 10:08:02.769   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.769   Importing the DLL function.
2020-04-14 10:08:02.769   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.769   -- DLL function import --
2020-04-14 10:08:02.769   Function name: idpSetLogin
2020-04-14 10:08:02.769   DLL name: files:idp.dll
2020-04-14 10:08:02.769   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.769   Importing the DLL function.
2020-04-14 10:08:02.770   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.770   -- DLL function import --
2020-04-14 10:08:02.770   Function name: idpSetProxyMode
2020-04-14 10:08:02.770   DLL name: files:idp.dll
2020-04-14 10:08:02.770   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.770   Importing the DLL function.
2020-04-14 10:08:02.770   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.770   -- DLL function import --
2020-04-14 10:08:02.770   Function name: idpSetProxyName
2020-04-14 10:08:02.770   DLL name: files:idp.dll
2020-04-14 10:08:02.770   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.770   Importing the DLL function.
2020-04-14 10:08:02.770   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.770   -- DLL function import --
2020-04-14 10:08:02.770   Function name: idpSetProxyLogin
2020-04-14 10:08:02.770   DLL name: files:idp.dll
2020-04-14 10:08:02.770   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.770   Importing the DLL function.
2020-04-14 10:08:02.771   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.771   -- DLL function import --
2020-04-14 10:08:02.771   Function name: idpConnectControl
2020-04-14 10:08:02.771   DLL name: files:idp.dll
2020-04-14 10:08:02.771   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.771   Importing the DLL function.
2020-04-14 10:08:02.771   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.771   -- DLL function import --
2020-04-14 10:08:02.771   Function name: idpAddMessage
2020-04-14 10:08:02.771   DLL name: files:idp.dll
2020-04-14 10:08:02.771   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.771   Importing the DLL function.
2020-04-14 10:08:02.771   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.771   -- DLL function import --
2020-04-14 10:08:02.771   Function name: idpSetInternalOption
2020-04-14 10:08:02.771   DLL name: files:idp.dll
2020-04-14 10:08:02.771   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.772   Importing the DLL function.
2020-04-14 10:08:02.772   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.772   -- DLL function import --
2020-04-14 10:08:02.772   Function name: idpSetDetailedMode
2020-04-14 10:08:02.772   DLL name: files:idp.dll
2020-04-14 10:08:02.772   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.772   Importing the DLL function.
2020-04-14 10:08:02.772   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.772   -- DLL function import --
2020-04-14 10:08:02.772   Function name: idpSetComponents
2020-04-14 10:08:02.772   DLL name: files:idp.dll
2020-04-14 10:08:02.772   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.772   Importing the DLL function.
2020-04-14 10:08:02.772   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.772   -- DLL function import --
2020-04-14 10:08:02.772   Function name: idpReportError
2020-04-14 10:08:02.772   DLL name: files:idp.dll
2020-04-14 10:08:02.772   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.773   Importing the DLL function.
2020-04-14 10:08:02.773   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.773   -- DLL function import --
2020-04-14 10:08:02.773   Function name: idpTrace
2020-04-14 10:08:02.773   DLL name: files:idp.dll
2020-04-14 10:08:02.773   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.773   Importing the DLL function.
2020-04-14 10:08:02.773   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.773   -- DLL function import --
2020-04-14 10:08:02.773   Function name: idpAddFileSize
2020-04-14 10:08:02.773   DLL name: files:idp.dll
2020-04-14 10:08:02.773   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.773   Importing the DLL function.
2020-04-14 10:08:02.773   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.773   -- DLL function import --
2020-04-14 10:08:02.773   Function name: idpAddFileSize
2020-04-14 10:08:02.773   DLL name: files:idp.dll
2020-04-14 10:08:02.774   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.774   Importing the DLL function.
2020-04-14 10:08:02.774   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.774   -- DLL function import --
2020-04-14 10:08:02.774   Function name: idpGetFileSize
2020-04-14 10:08:02.774   DLL name: files:idp.dll
2020-04-14 10:08:02.774   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.774   Importing the DLL function.
2020-04-14 10:08:02.774   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.774   -- DLL function import --
2020-04-14 10:08:02.774   Function name: idpGetFilesSize
2020-04-14 10:08:02.774   DLL name: files:idp.dll
2020-04-14 10:08:02.774   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idp.dll
2020-04-14 10:08:02.774   Importing the DLL function.
2020-04-14 10:08:02.774   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.775   -- DLL function import --
2020-04-14 10:08:02.775   Function name: proc_start
2020-04-14 10:08:02.775   DLL name: files:cmdlinerunner.dll
2020-04-14 10:08:02.775   Extracting temporary file: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\cmdlinerunner.dll
2020-04-14 10:08:02.837   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\cmdlinerunner.dll
2020-04-14 10:08:02.837   Importing the DLL function.
2020-04-14 10:08:02.873   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.873   -- DLL function import --
2020-04-14 10:08:02.873   Function name: proc_get_exit_code
2020-04-14 10:08:02.873   DLL name: files:cmdlinerunner.dll
2020-04-14 10:08:02.873   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\cmdlinerunner.dll
2020-04-14 10:08:02.873   Importing the DLL function.
2020-04-14 10:08:02.873   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.873   -- DLL function import --
2020-04-14 10:08:02.873   Function name: proc_get_output
2020-04-14 10:08:02.873   DLL name: files:cmdlinerunner.dll
2020-04-14 10:08:02.874   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\cmdlinerunner.dll
2020-04-14 10:08:02.874   Importing the DLL function.
2020-04-14 10:08:02.874   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.874   -- DLL function import --
2020-04-14 10:08:02.874   Function name: proc_end
2020-04-14 10:08:02.874   DLL name: files:cmdlinerunner.dll
2020-04-14 10:08:02.874   Dest DLL name: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\cmdlinerunner.dll
2020-04-14 10:08:02.874   Importing the DLL function.
2020-04-14 10:08:02.874   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:02.874   -- DLL function import --
2020-04-14 10:08:02.874   Function name: SetEnvironmentVariableW
2020-04-14 10:08:02.874   DLL name: kernel32.dll
2020-04-14 10:08:02.874   Dest DLL name: kernel32.dll
2020-04-14 10:08:02.874   Importing the DLL function.
2020-04-14 10:08:02.875   Successfully imported the DLL function. Delay loaded? No
2020-04-14 10:08:04.670   Found link in "For more infojects/esp-idf/en/latest/versions.html": "https://docs.espressif.com/projects/esp-idf/en/latest/versions.html"
2020-04-14 10:08:50.871   OnPythonPagePrepare
2020-04-14 10:08:50.871   In -2147483647\Software\Python\PythonCore
2020-04-14 10:08:50.871   In -2147483647\Software\Python\PythonCore\3.7
2020-04-14 10:08:50.871   Adding Python version=3.7 name=Python 3.7 (64-bit) executable=C:\Users\James\AppData\Local\Programs\Python\Python37\python.exe
2020-04-14 10:08:50.871   Nothing found in -2147483646\Software\Python
2020-04-14 10:08:50.872   Nothing found in -2147483646\Software\Wow6432Node\Python
2020-04-14 10:08:53.159   OnPythonPageValidate index=0
2020-04-14 10:08:53.159   OnPythonPageValidate: PythonPath=C:\Users\James\AppData\Local\Programs\Python\Python37\ PythonExecutablePath=C:\Users\James\AppData\Local\Programs\Python\Python37\python.exe
2020-04-14 10:08:53.172   OnGitPagePrepare
2020-04-14 10:08:58.920   Git path: C:\Program Files\Git\cmd\git.exe
2020-04-14 10:08:58.920   Running /C "C:\Program Files\Git\cmd\git.exe" --version >gitver.txt
2020-04-14 10:09:02.555   Git version: 2.26.0.windows.1
2020-04-14 10:09:02.555   Adding Git version=2.26.0.windows.1 name=2.26.0.windows.1 executable=C:\Program Files\Git\cmd\git.exe
2020-04-14 10:09:08.612   OnGitPageValidate index=0
2020-04-14 10:09:08.624   OnIDFPagePrepare
2020-04-14 10:09:13.349   OnIDFPageValidate index=0
2020-04-14 10:09:13.363   OnIDFDownloadPagePrepare
2020-04-14 10:09:20.601   Downloaded https://dl.espressif.com/dl/esp-idf/idf_versions.txt to C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\idf_versions.txt
2020-04-14 10:09:20.601   Versions count: 5
2020-04-14 10:09:20.601   Version 0: v4.0
2020-04-14 10:09:20.602   Version 1: v3.3.2
2020-04-14 10:09:20.602   Version 2: release/v4.0
2020-04-14 10:09:20.603   Version 3: release/v3.3
2020-04-14 10:09:20.603   Version 4: master
2020-04-14 10:09:24.529   OnIDFDownloadPageValidate index=0
2020-04-14 10:09:27.537   Checking PSMODULEPATH for Windows Defender module...
2020-04-14 10:09:27.597   CheckWinDefenderAvailable: YES (C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\\Defender)
2020-04-14 10:09:29.132   Summary message: 
                          Using Python 3.7:
                                C:\Users\James\AppData\Local\Programs\Python\Python37\python.exe
                          
                          Using Git 2.26.0.windows.1:
                                C:\Program Files\Git\cmd\git.exe
                          
                          Will download ESP-IDF v4.0 into:
                                C:\Users\James\Desktop\esp-idf-7
                          
                          IDF tools directory (IDF_TOOLS_PATH):
                                C:\Users\James\.espressif
                          
                          
2020-04-14 10:09:31.700   GetIDFZIPFileVersion(v4.0)=v4.0
2020-04-14 10:09:31.701   C:\Users\James\.espressif\releases\esp-idf-v4.0.zip already exists
2020-04-14 10:09:31.708   Calling RestartManager's RmGetList.
2020-04-14 10:09:31.743   RmGetList finished successfully.
2020-04-14 10:09:31.743   RestartManager found no applications using one of our files.
2020-04-14 10:09:31.761   Starting the installation process.
2020-04-14 10:09:31.768   Directory for uninstall files: C:\Users\James\.espressif
2020-04-14 10:09:31.855   Will append to existing uninstall log: C:\Users\James\.espressif\unins000.dat
2020-04-14 10:09:31.862   -- File entry --
2020-04-14 10:09:31.863   Dest filename: C:\Users\James\.espressif\unins000.exe
2020-04-14 10:09:31.863   Non-default bitness: 32-bit
2020-04-14 10:09:31.866   Time stamp of our file: 2020-04-14 10:08:01.129
2020-04-14 10:09:31.866   Dest file exists.
2020-04-14 10:09:31.866   Time stamp of existing file: 2020-04-14 04:05:58.711
2020-04-14 10:09:31.867   Version of our file: 51.1052.0.0
2020-04-14 10:09:31.919   Version of existing file: 51.1052.0.0
2020-04-14 10:09:31.919   Installing the file.
2020-04-14 10:09:31.953   Leaving temporary file in place for now.
2020-04-14 10:09:31.954   -- File entry --
2020-04-14 10:09:31.955   Dest filename: C:\Users\James\.espressif\idf_tools_fallback.py
2020-04-14 10:09:31.955   Time stamp of our file: 2020-02-11 09:02:54.000
2020-04-14 10:09:31.955   Dest file exists.
2020-04-14 10:09:31.956   Time stamp of existing file: 2020-02-11 09:02:54.000
2020-04-14 10:09:31.956   Version of our file: (none)
2020-04-14 10:09:31.986   Version of existing file: (none)
2020-04-14 10:09:31.986   Installing the file.
2020-04-14 10:09:32.060   Successfully installed the file.
2020-04-14 10:09:32.061   -- File entry --
2020-04-14 10:09:32.062   Dest filename: C:\Users\James\.espressif\tools_fallback.json
2020-04-14 10:09:32.062   Time stamp of our file: 2020-02-11 09:02:42.000
2020-04-14 10:09:32.062   Dest file exists.
2020-04-14 10:09:32.063   Time stamp of existing file: 2020-02-11 09:02:42.000
2020-04-14 10:09:32.063   Version of our file: (none)
2020-04-14 10:09:32.086   Version of existing file: (none)
2020-04-14 10:09:32.086   Installing the file.
2020-04-14 10:09:32.091   Successfully installed the file.
2020-04-14 10:09:32.091   -- File entry --
2020-04-14 10:09:32.092   Dest filename: C:\Users\James\.espressif\idf_cmd_init.bat
2020-04-14 10:09:32.093   Time stamp of our file: 2020-02-11 09:02:42.000
2020-04-14 10:09:32.093   Dest file exists.
2020-04-14 10:09:32.093   Time stamp of existing file: 2020-02-11 09:02:42.000
2020-04-14 10:09:32.093   Version of our file: (none)
2020-04-14 10:09:32.095   Version of existing file: (none)
2020-04-14 10:09:32.095   Installing the file.
2020-04-14 10:09:32.100   Successfully installed the file.
2020-04-14 10:09:32.101   -- File entry --
2020-04-14 10:09:32.102   Dest filename: C:\Users\James\.espressif\dist\binutils-esp32s2ulp-win32-2.28.51-esp-20191205.zip
2020-04-14 10:09:32.119   Time stamp of our file: 2020-02-11 17:56:46.000
2020-04-14 10:09:32.119   Dest file exists.
2020-04-14 10:09:32.123   Time stamp of existing file: 2020-02-11 17:56:46.000
2020-04-14 10:09:32.124   Version of our file: (none)
2020-04-14 10:09:32.141   Version of existing file: (none)
2020-04-14 10:09:32.141   Installing the file.
2020-04-14 10:09:33.325   Successfully installed the file.
2020-04-14 10:09:33.326   -- File entry --
2020-04-14 10:09:33.327   Dest filename: C:\Users\James\.espressif\dist\binutils-esp32ulp-win32-2.28.51-esp-20191205.zip
2020-04-14 10:09:33.358   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:33.358   Dest file exists.
2020-04-14 10:09:33.358   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:33.358   Version of our file: (none)
2020-04-14 10:09:33.394   Version of existing file: (none)
2020-04-14 10:09:33.394   Installing the file.
2020-04-14 10:09:34.483   Successfully installed the file.
2020-04-14 10:09:34.483   -- File entry --
2020-04-14 10:09:34.484   Dest filename: C:\Users\James\.espressif\dist\binutils-esp32ulp-win32-2.28.51-esp32ulp-20180809.zip
2020-04-14 10:09:34.513   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:34.513   Dest file exists.
2020-04-14 10:09:34.514   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:34.514   Version of our file: (none)
2020-04-14 10:09:34.542   Version of existing file: (none)
2020-04-14 10:09:34.542   Installing the file.
2020-04-14 10:09:35.568   Successfully installed the file.
2020-04-14 10:09:35.571   -- File entry --
2020-04-14 10:09:35.573   Dest filename: C:\Users\James\.espressif\dist\ccache-3.7-w64.zip
2020-04-14 10:09:35.760   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:35.760   Dest file exists.
2020-04-14 10:09:35.760   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:35.760   Version of our file: (none)
2020-04-14 10:09:35.869   Version of existing file: (none)
2020-04-14 10:09:35.870   Installing the file.
2020-04-14 10:09:35.890   Successfully installed the file.
2020-04-14 10:09:35.890   -- File entry --
2020-04-14 10:09:35.891   Dest filename: C:\Users\James\.espressif\dist\cmake-3.13.4-win64-x64.zip
2020-04-14 10:09:35.891   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:35.891   Dest file exists.
2020-04-14 10:09:35.892   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:35.892   Version of our file: (none)
2020-04-14 10:09:35.966   Version of existing file: (none)
2020-04-14 10:09:35.966   Installing the file.
2020-04-14 10:09:39.368   Successfully installed the file.
2020-04-14 10:09:39.369   -- File entry --
2020-04-14 10:09:39.369   Dest filename: C:\Users\James\.espressif\dist\idf-exe-v1.0.1.zip
2020-04-14 10:09:39.389   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.389   Dest file exists.
2020-04-14 10:09:39.390   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.390   Version of our file: (none)
2020-04-14 10:09:39.483   Version of existing file: (none)
2020-04-14 10:09:39.483   Installing the file.
2020-04-14 10:09:39.646   Successfully installed the file.
2020-04-14 10:09:39.646   -- File entry --
2020-04-14 10:09:39.647   Dest filename: C:\Users\James\.espressif\dist\mconf-v4.6.0.0-idf-20190628-win32.zip
2020-04-14 10:09:39.648   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.648   Dest file exists.
2020-04-14 10:09:39.649   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.649   Version of our file: (none)
2020-04-14 10:09:39.666   Version of existing file: (none)
2020-04-14 10:09:39.666   Installing the file.
2020-04-14 10:09:39.758   Successfully installed the file.
2020-04-14 10:09:39.758   -- File entry --
2020-04-14 10:09:39.759   Dest filename: C:\Users\James\.espressif\dist\ninja-1.9.0-win64.zip
2020-04-14 10:09:39.804   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.804   Dest file exists.
2020-04-14 10:09:39.805   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.805   Version of our file: (none)
2020-04-14 10:09:39.834   Version of existing file: (none)
2020-04-14 10:09:39.834   Installing the file.
2020-04-14 10:09:39.870   Successfully installed the file.
2020-04-14 10:09:39.870   -- File entry --
2020-04-14 10:09:39.871   Dest filename: C:\Users\James\.espressif\dist\openocd-esp32-win32-0.10.0-esp32-20190313.zip
2020-04-14 10:09:39.890   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.890   Dest file exists.
2020-04-14 10:09:39.891   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:39.891   Version of our file: (none)
2020-04-14 10:09:39.909   Version of existing file: (none)
2020-04-14 10:09:39.909   Installing the file.
2020-04-14 10:09:40.161   Successfully installed the file.
2020-04-14 10:09:40.161   -- File entry --
2020-04-14 10:09:40.162   Dest filename: C:\Users\James\.espressif\dist\openocd-esp32-win32-0.10.0-esp32-20191114.zip
2020-04-14 10:09:40.178   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:40.178   Dest file exists.
2020-04-14 10:09:40.197   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:40.197   Version of our file: (none)
2020-04-14 10:09:40.208   Version of existing file: (none)
2020-04-14 10:09:40.208   Installing the file.
2020-04-14 10:09:40.381   Successfully installed the file.
2020-04-14 10:09:40.382   -- File entry --
2020-04-14 10:09:40.382   Dest filename: C:\Users\James\.espressif\dist\placeholder
2020-04-14 10:09:40.383   Time stamp of our file: 2020-02-10 20:13:36.000
2020-04-14 10:09:40.383   Dest file exists.
2020-04-14 10:09:40.383   Time stamp of existing file: 2020-02-10 20:13:36.000
2020-04-14 10:09:40.383   Version of our file: (none)
2020-04-14 10:09:40.384   Version of existing file: (none)
2020-04-14 10:09:40.384   Installing the file.
2020-04-14 10:09:40.388   Successfully installed the file.
2020-04-14 10:09:40.388   -- File entry --
2020-04-14 10:09:40.389   Dest filename: C:\Users\James\.espressif\dist\xtensa-esp32-elf-gcc8_2_0-esp-2019r2-win32.zip
2020-04-14 10:09:40.401   Time stamp of our file: 2020-02-11 17:56:48.000
2020-04-14 10:09:40.401   Dest file exists.
2020-04-14 10:09:40.401   Time stamp of existing file: 2020-02-11 17:56:48.000
2020-04-14 10:09:40.401   Version of our file: (none)
2020-04-14 10:09:40.441   Version of existing file: (none)
2020-04-14 10:09:40.442   Installing the file.
2020-04-14 10:09:51.237   Successfully installed the file.
2020-04-14 10:09:51.237   -- File entry --
2020-04-14 10:09:51.238   Dest filename: C:\Users\James\.espressif\dist\xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip
2020-04-14 10:09:51.253   Time stamp of our file: 2020-02-11 17:56:50.000
2020-04-14 10:09:51.253   Dest file exists.
2020-04-14 10:09:51.254   Time stamp of existing file: 2020-02-11 17:56:50.000
2020-04-14 10:09:51.254   Version of our file: (none)
2020-04-14 10:09:51.294   Version of existing file: (none)
2020-04-14 10:09:51.294   Installing the file.
2020-04-14 10:10:04.811   Successfully installed the file.
2020-04-14 10:10:04.812   -- File entry --
2020-04-14 10:10:04.813   Dest filename: C:\Users\James\.espressif\dist\xtensa-esp32s2-elf-gcc8_2_0-esp-2019r2-win32.zip
2020-04-14 10:10:04.813   Time stamp of our file: 2020-02-11 17:56:50.000
2020-04-14 10:10:04.813   Dest file exists.
2020-04-14 10:10:04.814   Time stamp of existing file: 2020-02-11 17:56:50.000
2020-04-14 10:10:04.814   Version of our file: (none)
2020-04-14 10:10:04.838   Version of existing file: (none)
2020-04-14 10:10:04.838   Installing the file.
2020-04-14 10:10:16.393   Successfully installed the file.
2020-04-14 10:10:16.394   -- File entry --
2020-04-14 10:10:16.395   Dest filename: C:\Users\James\.espressif\dist\tools_WD_excl.ps1
2020-04-14 10:10:16.395   Time stamp of our file: 2020-02-11 09:02:42.000
2020-04-14 10:10:16.396   Dest file exists.
2020-04-14 10:10:16.396   Time stamp of existing file: 2020-02-11 09:02:42.000
2020-04-14 10:10:16.396   Version of our file: (none)
2020-04-14 10:10:16.436   Version of existing file: (none)
2020-04-14 10:10:16.436   Installing the file.
2020-04-14 10:10:16.443   Successfully installed the file.
2020-04-14 10:10:16.444   -- File entry --
2020-04-14 10:10:16.445   Dest filename: C:\Users\James\.espressif\dist\tools_WD_clean.ps1
2020-04-14 10:10:16.464   Time stamp of our file: 2020-02-11 09:02:42.000
2020-04-14 10:10:16.464   Dest file exists.
2020-04-14 10:10:16.464   Time stamp of existing file: 2020-02-11 09:02:42.000
2020-04-14 10:10:16.464   Version of our file: (none)
2020-04-14 10:10:16.492   Version of existing file: (none)
2020-04-14 10:10:16.492   Installing the file.
2020-04-14 10:10:16.515   Successfully installed the file.
2020-04-14 10:10:16.516   -- Registry entry --
2020-04-14 10:10:16.516   Key: HKEY_CURRENT_USER\Environment
2020-04-14 10:10:16.516   Value name: IDF_TOOLS_PATH
2020-04-14 10:10:16.516   Creating or opening the key.
2020-04-14 10:10:16.516   Deleting the value.
2020-04-14 10:10:16.516   Creating or setting the value.
2020-04-14 10:10:16.517   Successfully created or set the value.
2020-04-14 10:10:16.518   Saving uninstall information.
2020-04-14 10:10:16.518   Renaming uninstaller.
2020-04-14 10:10:16.521   Deleting uninstall key left over from previous non administrative install.
2020-04-14 10:10:16.522   Creating new uninstall key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{9E068D99-5C4B-4E5F-96A3-B17CF291E6BD}_is1
2020-04-14 10:10:16.523   Writing uninstall key values.
2020-04-14 10:10:16.526   Detected previous administrative 64-bit install? No
2020-04-14 10:10:16.527   Detected previous administrative 32-bit install? No
2020-04-14 10:10:16.625   Installation process succeeded.
2020-04-14 10:10:16.627   Setting PATH for this process: C:\Users\James\AppData\Local\Programs\Python\Python37\;C:\Program Files\Git\cmd\;C:\Program Files (x86)\Google\Chrome\Application;C:\WinAVR-20100110\bin;C:\WinAVR-20100110\utils\bin;C:\Program Files\Git\cmd;C:\Users\James\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\James\AppData\Local\Programs\Python\Python37\;C:\Users\James\AppData\Local\Microsoft\WindowsApps;C:\Users\James\AppData\Roaming\Dashlane\4.6.6.23032\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;%DASHLANE_DLL_DIR%;C:\Program Files (x86)\EaseUS\Todo Backup\bin\x64\
2020-04-14 10:10:16.628   PYTHONPATH=
2020-04-14 10:10:16.628   Extracting temporary file: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\7za.exe
2020-04-14 10:10:16.702   Extracting ESP-IDF reference repository: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\7za.exe x -oC:\Users\James\AppData\Local\Temp\is-T11P2.tmp -r -aoa "C:\Users\James\.espressif\releases\esp-idf-v4.0.zip"
2020-04-14 10:10:16.702   Reference repository path: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\esp-idf-v4.0
2020-04-14 10:13:11.010   Done, exit code=0
2020-04-14 10:13:11.010   --------
2020-04-14 10:13:12.299   Running command: C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\7za.exe x -oC:\Users\James\AppData\Local\Temp\is-T11P2.tmp -r -aoa "C:\Users\James\.espressif\releases\esp-idf-v4.0.zip"
                          
                          7-Zip (a) 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
                          
                          Scanning the drive for archives:
                          1 file, 415318076 bytes (397 MiB)
                          
                          Extracting archive: C:\Users\James\.espressif\releases\esp-idf-v4.0.zip
                          --
                          Path = C:\Users\James\.espressif\releases\esp-idf-v4.0.zip
                          Type = zip
                          Physical Size = 415318076
                          
                          Everything is Ok
                          
                          Folders: 2381
                          Files: 11484
                          Size:       614298370
                          Compressed: 415318076
                          
2020-04-14 10:13:12.300   --------
2020-04-14 10:13:12.307   Copying C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\esp-idf-v4.0 to C:\Users\James\Desktop\esp-idf-7
2020-04-14 10:13:12.550   Done, exit code=1
2020-04-14 10:13:12.551   --------
2020-04-14 10:13:12.551   Running command: cmd.exe /c ""xcopy" /s /e /i /h /q "C:\Users\James\AppData\Local\Temp\is-T11P2.tmp\esp-idf-v4.0" "C:\Users\James\Desktop\esp-idf-7""
                          '"xcopy"' is not recognized as an internal or external command,
                          operable program or batch file.
                          
2020-04-14 10:13:12.551   --------
2020-04-14 10:13:12.551   Message box (OK):
                          Installation has failed with exit code 1
2020-04-14 10:14:29.241   User chose OK.
2020-04-14 10:14:29.256   Message box (Yes/No):
                          Installation log has been created, it may contain more information about the problem.
                          Display the installation log now?
2020-04-14 10:14:30.888   User chose Yes.
2020-04-14 10:14:33.198   CurStepChanged raised an exception.
2020-04-14 10:14:33.456   Need to restart Windows? No
2020-04-14 10:14:33.467   Deinitializing Setup.

**Comment by igrr** [comment]
@804enl it seems there is a problem with your system/user PATH environment variable:

> Setting PATH for this process: C:\Users\James\AppData\Local\Programs\Python\Python37;C:\Program Files\Git\cmd;C:\Program Files (x86)\Google\Chrome\Application;C:\WinAVR-20100110\bin;C:\WinAVR-20100110\utils\bin;C:\Program Files\Git\cmd;C:\Users\James\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\James\AppData\Local\Programs\Python\Python37;C:\Users\James\AppData\Local\Microsoft\WindowsApps;C:\Users\James\AppData\Roaming\Dashlane\4.6.6.23032\bin\Firefox_Extension{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;%DASHLANE_DLL_DIR%;C:\Program Files (x86)\EaseUS\Todo Backup\bin\x64

The path doesn't include standard Windows paths, like `%SystemRoot%\system32`, `%SystemRoot%`, etc. This is not normal, as such paths are included in PATH by default on Windows 10.

Please add `C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\` to PATH environment variable ([link](https://superuser.com/a/949577)) and try again.

**Comment by amulya-incorrigible** [comment]
can someone please help me? I am recieving an installation error for idf-esp32 on windows 10. I tried different version releases too, the error is same
here is my log:
2020-10-30 10:45:36.736   --------
2020-10-30 10:45:36.745   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\asio\asio\objects\info\alternates
2020-10-30 10:45:36.747   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\bootloader\subproject\components\micro-ecc\micro-ecc\objects\info\alternates
2020-10-30 10:45:36.748   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\bt\controller\lib\objects\info\alternates
2020-10-30 10:45:36.750   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\bt\host\nimble\nimble\objects\info\alternates
2020-10-30 10:45:36.752   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\coap\libcoap\modules\ext\tinydtls\objects\info\alternates
2020-10-30 10:45:36.753   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\coap\libcoap\objects\info\alternates
2020-10-30 10:45:36.755   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\esptool_py\esptool\objects\info\alternates
2020-10-30 10:45:36.756   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\esp_wifi\lib_esp32\objects\info\alternates
2020-10-30 10:45:36.758   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\expat\expat\objects\info\alternates
2020-10-30 10:45:36.759   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\json\cJSON\objects\info\alternates
2020-10-30 10:45:36.761   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\libsodium\libsodium\objects\info\alternates
2020-10-30 10:45:36.762   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\lwip\lwip\objects\info\alternates
2020-10-30 10:45:36.764   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\mbedtls\mbedtls\objects\info\alternates
2020-10-30 10:45:36.765   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\mqtt\esp-mqtt\objects\info\alternates
2020-10-30 10:45:36.768   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\nghttp\nghttp2\modules\third-party\mruby\objects\info\alternates
2020-10-30 10:45:36.771   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\nghttp\nghttp2\modules\third-party\neverbleed\objects\info\alternates
2020-10-30 10:45:36.772   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\nghttp\nghttp2\objects\info\alternates
2020-10-30 10:45:36.773   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\protobuf-c\protobuf-c\objects\info\alternates
2020-10-30 10:45:36.775   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\spiffs\spiffs\objects\info\alternates
2020-10-30 10:45:36.776   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\components\unity\unity\objects\info\alternates
2020-10-30 10:45:36.778   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\modules\examples\build_system\cmake\import_lib\main\lib\tinyxml2\objects\info\alternates
2020-10-30 10:45:36.779   Removing C:\Users\amuly\Desktop\esp-idf-2\.git\objects\info\alternates
2020-10-30 10:45:36.780   idf_tools.py exists in IDF directory
2020-10-30 10:45:36.780   idf_tools.py command: C:\Users\amuly\anaconda3\python.exe "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py" --idf-path C:\Users\amuly\Desktop\esp-idf-2
2020-10-30 10:45:36.780   Installing tools:C:\Users\amuly\anaconda3\python.exe "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py" --idf-path C:\Users\amuly\Desktop\esp-idf-2 install
2020-10-30 10:45:37.102   Done, exit code=1
2020-10-30 10:45:37.102   --------
2020-10-30 10:45:37.102   Running command: C:\Users\amuly\anaconda3\python.exe "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py" --idf-path C:\Users\amuly\Desktop\esp-idf-2 install
                          Installing tools: xtensa-esp32-elf, esp32ulp-elf, cmake, openocd-esp32, mconf, ninja, idf-exe, ccache
                          Installing xtensa-esp32-elf@esp-2020r3-8.4.0
                          Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip to C:\.espressif\dist\xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip.tmp
                          WARNING: Download failure <urlopen error unknown url type: https>
                          WARNING: Failed to download https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip to C:\.espressif\dist\xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip.tmp
                          Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip to C:\.espressif\dist\xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip.tmp
                          WARNING: Download failure <urlopen error unknown url type: https>
                          WARNING: Failed to download https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip to C:\.espressif\dist\xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip.tmp
                          Downloading xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip to C:\.espressif\dist\xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip.tmp
                          WARNING: Download failure <urlopen error unknown url type: https>
                          WARNING: Failed to download https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip to C:\.espressif\dist\xtensa-esp32-elf-gcc8_4_0-esp-2020r3-win64.zip.tmp
                          ERROR: Failed to download, and retry count has expired
                          Traceback (most recent call last):
                            File "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py", line 1387, in <module>
                              main(sys.argv[1:])
                            File "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py", line 1383, in main
                              action_func(args)
                            File "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py", line 1167, in action_install
                              tool_obj.download(tool_version)
                            File "C:\Users\amuly\Desktop\esp-idf-2\tools\idf_tools.py", line 584, in download
                              raise DownloadError()
                          __main__.DownloadError
                          
2020-10-30 10:45:37.102   --------
2020-10-30 10:45:37.102   Message box (OK):
                          Installation has failed with exit code 1
2020-10-30 10:46:25.858   User chose OK.
2020-10-30 10:46:25.865   Message box (Yes/No):
                          Installation log has been created, it may contain more information about the problem.
                          Display the installation log now?
2020-10-30 10:46:27.373   User chose Yes.
2020-10-30 10:46:27.404   CurStepChanged raised an exception.

**Comment by igrr** [comment]
@amulya-incorrigible it looks like your copy of Python doesn't have HTTPS support installed (`WARNING: Download failure <urlopen error unknown url type: https>`). I would recommend installing Python 3.7 or 3.8 from Python.org, and choosing it in the IDF Tools installer.

**Comment by imranrajjad** [comment]
I am getting following error on Windows 10

Processing d:\esp-idf\esp-idf\tools\kconfig_new\esp-windows-curses
Exception:
Traceback (most recent call last):
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2610, in _dep_map
    return self.__dep_map
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2685, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\req\req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\req\req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2980, in parse_requirements
    "version spec")
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2945, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pip._vendor.pkg_resources.RequirementParseError: Expected version spec in windows-curses; sys_platform == "win32" at ; sys_platform == "win32"
You are using pip version 8.1.1, however version 20.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Command failed: "D:\esp-idf\python_env\idf4.1_py3.5_env\Scripts\python.exe" -m pip install -r "D:\esp-idf\esp-idf\requirements.txt"
Exception:
Traceback (most recent call last):
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2610, in _dep_map
    return self.__dep_map
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2685, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\req\req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\req\req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2980, in parse_requirements
    "version spec")
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2945, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pip._vendor.pkg_resources.RequirementParseError: Expected version spec in windows-curses; sys_platform == "win32" at ; sys_platform == "win32"
You are using pip version 8.1.1, however version 20.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Command failed: "D:\esp-idf\python_env\idf4.1_py3.5_env\Scripts\python.exe" -m pip install -r "D:\esp-idf\esp-idf\requirements.txt"
Exception:
Traceback (most recent call last):
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2610, in _dep_map
    return self.__dep_map
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2685, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\req\req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\req\req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2980, in parse_requirements
    "version spec")
  File "D:\esp-idf\python_env\idf4.1_py3.5_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2945, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pip._vendor.pkg_resources.RequirementParseError: Expected version spec in windows-curses; sys_platform == "win32" at ; sys_platform == "win32"
You are using pip version 8.1.1, however version 20.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by igrr** [comment]
@imranrajjad It seems that you are using Python 3.5 together with a very outdated pip version (8.1.1). Please try installing an up-to-date Python 3.7 or 3.8 from python.org. One way is to choose "Install Python 3.7" option in the IDF Tools Installer. It will download and install a more recent version of Python for you.
