### ISSUE TITLE
Guru Meditation Error: Core 0 panic'ed (Interrupt wdt timeout on CPU0) (IDFGH-3401)

### ISSUE THREAD

**Issue by Nepenthes** [espressif/esp-idf#5368]
## Environment
Core (if using chip or module): [ESP-WROVER-B]
IDF version (git rev-parse --short HEAD to get the commit id.): v3.3.1-143d26aa4
Development Env: [Make monitor]
Operating System: [Windows]
Power Supply: [external 5.0]
Compiler version: 5.2.0

## Problem Description
硬件看门狗触发，无法定位到业务代码，出现周期8小时到48小时不等，大概一到两天一次，修改加大CONFIG_ESP_INT_WDT_TIMEOUT_MS基本不起作用

## Debug Logs
dump1：
![fhalsfhlaskhlkh](https://user-images.githubusercontent.com/10671191/83335580-75be4800-a2e0-11ea-98ca-fe46e58c68bf.png)
![sgaksfhaks](https://user-images.githubusercontent.com/10671191/83335582-78b93880-a2e0-11ea-9adc-32df96d3f65a.png)
dump2：
![wqheoiwqhori](https://user-images.githubusercontent.com/10671191/83335586-82db3700-a2e0-11ea-8a2a-25d04d9f7b26.png)
![sdhalsflaksl](https://user-images.githubusercontent.com/10671191/83335588-853d9100-a2e0-11ea-8e3e-4bab9c76b692.png)
![fhaisofiao](https://user-images.githubusercontent.com/10671191/83335590-87075480-a2e0-11ea-8d93-2b680f91dd2f.png)

## Project file
sdkconfig文件以及elf文件
[prjFile.zip](https://github.com/espressif/esp-idf/files/4706169/prjFile.zip)

**Comment by igrr** [comment]
This should be fixed on release/v3.3 branch in commit https://github.com/espressif/esp-idf/commit/2718fdbd9578b8cf5f4cc9960dd338d3327f1ca6, could you please try to update to v3.3.2?

**Comment by Nepenthes** [comment]
7 machines in continuous testing, has been hung up for 27 hours, still continue to monitor
