### ISSUE TITLE
SPI Slave Driver holds down MISO when DMA is disabled and GPIO Matrix is enforced (IDFGH-7020)

### ISSUE THREAD

**Issue by fm1234** [espressif/esp-idf#8638]
## Environment

- Development Kit:  none
- Module or chip used:  ESP32-WROOM-32E
- IDF version (run ``git describe --tags`` to find it): v4.3.2
- Build System:  idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System: macOS
- Using an IDE?: No
- Power Supply: external 3.3V

## Problem Description

Using the SPI Slave Driver with DMA disabled and GPIO Matrix, that means:
	- spi_bus_config_t.flags = SPICOMMON_BUSFLAG_GPIO_PINS // to use GPIO matrix instead of IO Mux
	- spi_slave_initialize(HSPI_HOST, &busConfig, &slaveConig, 0) // 0 = Disable DMA
I see the problem that the MISO line is not released after CS is released but held LOW.

This leads to a problem with other SPI slaves on the bus as they cannot send any data during their active CS period.

Here is a scope of the other SPI slave trying to send something (blue = MISO, yellow = CS of the other SPI slave), but the other SPI slave can not pull the MISO line HIGH as it is held LOW by the ESP SPI Slave (even though you can see that it’s trying ;-))…
<img width="361" alt="Bildschirmfoto 2022-03-23 um 21 44 27" src="https://user-images.githubusercontent.com/14029494/159792322-430621d5-082c-4f8c-bfc2-0fe9bd2beef0.png">

If I enable DMA, the line is not held low anymore.
Of course when I keep the ESP SPI Slave in Bootloader mode (all pins floating) the other SPI slave works as well.

Do you think we can have a fix for that issue?
Thanks!

### Expected Behavior

MISO should not be pulled to low when the slave is not currently transmitting (= CS line not asserted (= CS line high))

### Actual Behavior

MISO is pulled low all the time making it impossible for other slaves on the bus to transmit data

### Steps to reproduce

Using the SPI Slave Driver with DMA disabled and GPIO Matrix, that means:
	- spi_bus_config_t.flags = SPICOMMON_BUSFLAG_GPIO_PINS // to use GPIO matrix instead of IO Mux
	- spi_slave_initialize(HSPI_HOST, &busConfig, &slaveConig, 0) // 0 = Disable DMA

### Code to reproduce this issue

See above, pretty simple

## Debug Logs

No specific logs

**Comment by wanckl** [comment]
@fm1234 Hi, is this issue resolved now? I have a try with your description as simply force GPIO Matrix and Disable DMA in slave driver of version 4.3.2 on esp32, I use 2 esp32 as slave on a same SPI bus, then take turns to activate each one by one, my master receive correct data from 2 slaves. could you give more information like which Pin you used as MISO, or is you add external pin_config (pull down or up). thank you !

Waiting you here.

**Comment by SebastiaanMerckx** [comment]
Hi @wanckl , @fm1234 ,
I am using IDF version v5.2.3 and I can confirm that the same issue still exists there.

Using following GPIO's on ESP32D0WD:
#define GPIO_NRF_SPI_CLK    26
#define GPIO_NRF_SPI_CS     27
#define GPIO_NRF_SPI_MOSI   25
#define GPIO_NRF_SPI_MISO   23

The problem is only visible in combination with other slave devices that have a lower drive strength, I think. I have 3 slave devices on my SPI bus (including ESP), and 1 of the other 2 is still working fine while an spi-flash device is not working fine.

Enabling DMA seems to do the trick for me as well.
I don't know why DMA would make a difference here. Maybe related to spi_ll_slave_set_mode ? We're using SPI mode 0.

I hope this helps? In general, you can just measure the MISO pin after initializing the SPI, with CS high. The MISO should not be pulled low

**Comment by wanckl** [comment]
@fm1234 @SebastiaanMerckx Hi, I can now reproduce this issue, there is a same issue here https://esp32.com/viewtopic.php?p=150750#p150750

I'll continue on it, but for your quickly testing, if you can't enable DMA to prevent this issue, you can reduce IO strength by 
```c
gpio_set_drive_capability(buscfg.miso_io_num, GPIO_DRIVE_CAP_0);
```
