### ISSUE TITLE
Decoding core dump fails on Windows

### ISSUE THREAD

**Issue by ddomnik** [espressif/esp-idf#9727]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

01d014c42def8d0c19e1ce55c07de6761e092ffa

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### What is the expected behavior?

After enabling the sdkconfig option to print the decoded core dump to UART
![image](https://user-images.githubusercontent.com/44225383/188569105-10ee55b5-57c9-42c5-b2bc-e22d679a6564.png)

I receive the following error:
```
ELF file SHA256: 953a138ca58cee78

Initiating core dump!
I (1785) esp_core_dump_uart: Press Enter to print core dump to UART...
I (1792) esp_core_dump_uart: Print core dump to uart...
Core dump started (further output muted)
Received  35 kB...
Core dump finished!
espcoredump.py v1.2

Traceback (most recent call last):
  File "C:\Espressif\frameworks\esp-idf-master\tools/idf_monitor.py", line 374, in <module>
    main()
  File "C:\Espressif\frameworks\esp-idf-master\tools/idf_monitor.py", line 365, in main
    monitor.main_loop()
  File "C:\Espressif\frameworks\esp-idf-master\tools/idf_monitor.py", line 162, in main_loop
    self._main_loop()
  File "C:\Espressif\frameworks\esp-idf-master\tools/idf_monitor.py", line 267, in _main_loop
    super()._main_loop()
  File "C:\Espressif\frameworks\esp-idf-master\tools/idf_monitor.py", line 207, in _main_loop
    self.serial_handler.handle_serial_input(data, self.console_parser, self.coredump,
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_monitor_base\serial_handler.py", line 102, in handle_serial_input
    with coredump.check(line):
  File "contextlib.py", line 113, in __enter__
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_monitor_base\coredump.py", line 128, in check
    self._check_coredump_trigger_before_print(line)
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_monitor_base\coredump.py", line 106, in _check_coredump_trigger_before_print
    self._process_coredump()
  File "C:\Espressif\frameworks\esp-idf-master\tools\idf_monitor_base\coredump.py", line 79, in _process_coredump
    coredump.info_corefile()
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\coredump.py", line 358, in info_corefile
    self.print_threads_info(task_info)
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\coredump.py", line 208, in print_threads_info
    threads, _ = self.gdb_esp.get_thread_info()
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 99, in get_thread_info
    result = self._gdbmi_run_cmd_get_one_response('-thread-info', 'done', 'result')['payload']
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 65, in _gdbmi_run_cmd_get_one_response
    return self._gdbmi_run_cmd_get_responses(cmd, resp_message, resp_type, multiple=False)[0]
  File "C:\Espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 58, in _gdbmi_run_cmd_get_responses
    raise ESPCoreDumpError("Couldn't find response with message '{}', type '{}' in responses '{}'".format(
esp_coredump.corefile.ESPCoreDumpError: Couldn't find response with message 'done', type 'result' in responses '[]'
```

### What is the actual behavior?

The decoded core dump should be displayed.

### Steps to reproduce.

1. Set sdkconfig as above.
2. Create crash
3. See Error

### More Information.

Tried it with the latest version on Windows - also an error.
Tried it on Ubuntu (Raspberry Pi 4) with the same commit version as above - no error.

This error may be related to my other ticket here: https://github.com/espressif/esp-idf/issues/9458
But as it works on Linux I think it is indeed a bug.

**Comment by igrr** [comment]
I suspect this has the same root cause as the last issue mentioned in https://github.com/espressif/esp-idf/issues/9379, which was solved by @Lapshin in https://github.com/espressif/esp-idf/commit/f44196c46bd37c0d386b32f49514fcee442a47f5. The fix was backported to release/v5.0 in https://github.com/espressif/esp-idf/commit/06cdc0ee4f6a254f4c682e4652e345506d194e3e. Could you please update your branch and give it another try?

**Comment by ztefanjo** [comment]
@igrr 
We seem to get the same error on more or less all CoreDumps we analyze since we introduced ESP-IDF v4.4.4. We are still being able to analyze the dumps (from v4.4.4 SW) using ESP-IDF v4.4.3. Is the fix that you mention in your comment also backported to v5.0? If so, it does not work. For us, it appears that this error was introduced (or made more likely to happen) in v4.4.4.

Output from the tool is:
```
python command to file
Traceback (most recent call last):
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\espcoredump.py", line 350, in <module>
    temp_core_files = info_corefile()
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\espcoredump.py", line 200, in info_corefile
    threads, _ = gdb.get_thread_info()
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\corefile\gdb.py", line 113, in get_thread_info
    result = self._gdbmi_run_cmd_get_one_response('-thread-info', 'done', 'result')['payload']
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\corefile\gdb.py", line 79, in _gdbmi_run_cmd_get_one_response
    return self._gdbmi_run_cmd_get_responses(cmd, resp_message, resp_type, multiple=False)[0]
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\corefile\gdb.py", line 72, in _gdbmi_run_cmd_get_responses
    raise ESPCoreDumpError("Couldn't find response with message '{}', type '{}' in responses '{}'".format(
corefile.ESPCoreDumpError: Couldn't find response with message 'done', type 'result' in responses '[]'
```

**Comment by felixcollins** [comment]
I've got this issue too. I tried updating to head of branch 5.0  - 15 July 2023 - 8df440175af54b5a8bf7228faf3ba48fc0b5ca22

It did not fix the issue. I'll try with Head of Master soon.

This is a real PITA. Basic tooling like this should be a high priority to fix.  I've been suffering with this crash since starting a project with a 5.0 release.

`
Traceback (most recent call last):
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor.py", line 378, in <module>
    main()
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor.py", line 369, in main
    monitor.main_loop()
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor.py", line 163, in main_loop
    self._main_loop()
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor.py", line 269, in _main_loop
    super()._main_loop()
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor.py", line 208, in _main_loop
    self.serial_handler.handle_serial_input(data, self.console_parser, self.coredump,
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor_base\serial_handler.py", line 102, in handle_serial_input
    with coredump.check(line):
  File "contextlib.py", line 113, in __enter__
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor_base\coredump.py", line 128, in check
    self._check_coredump_trigger_before_print(line)
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor_base\coredump.py", line 106, in _check_coredump_trigger_before_print
    self._process_coredump()
  File "C:\Users\felix\esp5\esp-idf\tools\idf_monitor_base\coredump.py", line 79, in _process_coredump
    coredump.info_corefile()
  File "c:\Users\felix\esp5\esp-tools\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\coredump.py", line 372, in info_corefile
    self.print_threads_info(task_info)
  File "c:\Users\felix\esp5\esp-tools\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\coredump.py", line 218, in print_threads_info
    threads, _ = self.gdb_esp.get_thread_info()
  File "c:\Users\felix\esp5\esp-tools\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 100, in get_thread_info
    result = self._gdbmi_run_cmd_get_one_response('-thread-info', 'done', 'result', response_delay_sec=2)['payload']
  File "c:\Users\felix\esp5\esp-tools\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 65, in _gdbmi_run_cmd_get_one_response
    return self._gdbmi_run_cmd_get_responses(cmd, resp_message, resp_type, response_delay_sec=response_delay_sec,
  File "c:\Users\felix\esp5\esp-tools\python_env\idf5.0_py3.8_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 58, in _gdbmi_run_cmd_get_responses
    raise ESPCoreDumpError("Couldn't find response with message '{}', type '{}' in responses '{}'".format(
esp_coredump.corefile.ESPCoreDumpError: Couldn't find response with message 'done', type 'result' in responses '[]'
`

**Comment by ztefanjo** [comment]
@igrr, any update on this one? We are now using v5.1.2 and still have big problems to parse coredumps with the v5.1.2 parser. So we actually still use v4.4.3 to parse our dumps (but need to apply some patches for it to work, e.g. remove all "noreturn" on functions frequently used during panic).

Examples of errors:
```
python command to file
Traceback (most recent call last):
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\espcoredump.py", line 77, in <module>
    main()
  File "C:\Data\Git\mower\Ext\esp-idf\components\espcoredump\espcoredump.py", line 62, in main
    temp_core_files = espcoredump.info_corefile()
  File "C:\Data\Git\mower\Ext\python_env\idf5.1_py3.9_env\lib\site-packages\esp_coredump\coredump.py", line 566, in info_corefile
    self.print_threads_info(task_info)
  File "C:\Data\Git\mower\Ext\python_env\idf5.1_py3.9_env\lib\site-packages\esp_coredump\coredump.py", line 334, in print_threads_info
    threads, _ = self.gdb_esp.get_thread_info(attempt * DEFAULT_GDB_TIMEOUT_SEC)
  File "C:\Data\Git\mower\Ext\python_env\idf5.1_py3.9_env\lib\site-packages\esp_coredump\corefile\gdb.py", line 122, in get_thread_info
    current_thread_id = result['current-thread-id']
KeyError: 'current-thread-id'
```



```
  File "C:\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Python\Python39\lib\threading.py", line 910, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Python39\lib\threading.py", line 910, in run
  File "C:\Python\Python39\lib\subprocess.py", line 1479, in _readerthread
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Python39\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
OSError: [Errno 22] Invalid argument
    buffer.append(fh.read())
OSError: [Errno 22] Invalid argument
```
The fact that v4.4.3 is able to parse the dump speaks for the the dump itself is correct, but the parser is not being able to handle it.

Our sdkconfig relating to this is:
```
CONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=y
# CONFIG_ESP_COREDUMP_ENABLE_TO_UART is not set
# CONFIG_ESP_COREDUMP_ENABLE_TO_NONE is not set
# CONFIG_ESP_COREDUMP_DATA_FORMAT_BIN is not set
CONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=y
CONFIG_ESP_COREDUMP_CHECKSUM_CRC32=y
CONFIG_ESP_COREDUMP_CHECK_BOOT=y
CONFIG_ESP_COREDUMP_ENABLE=y
CONFIG_ESP_COREDUMP_LOGS=y
CONFIG_ESP_COREDUMP_MAX_TASKS_NUM=20
CONFIG_ESP_COREDUMP_USE_STACK_SIZE=y
CONFIG_ESP_COREDUMP_STACK_SIZE=1280
```

**Comment by igrr** [comment]
@ztefanjo Thanks for the information! Do you think you could share an example coredump binary along with the ELF file which reproduces this issue? (For example, over email if you can't upload them here.)

@erhankur PTAL if we need to backport any fixes to v5.1.x?

**Comment by ztefanjo** [comment]
@erhankur : Strange, when reinstalling 5.1.2, I still get Python 3.9. Are we perhaps doing something wrong, or is the Python version stepped to 3.11 first in esp-idf v5.1.3?

**Comment by erhankur** [comment]
@ztefanjo For Windows, the best way to install the tools is by using an online installer.  https://dl.espressif.com/dl/esp-idf/ 
You can keep your existing idf but re-install the other things around.

**Comment by Zmmfly** [comment]
Same problem with python310 and idf 5.2.1

**Comment by erhankur** [comment]
@Zmmfly Can you select the don't decode option and send the base64 output with your app elf file? (From here or by email)

I would like to make sure coredump data is recorded without an error and the issue is specific to Windows. 
I couldn't reproduce it yet also on Windows, though. Maybe you can prepare a minimal reproducible app.

And, did you try to transfer with a lower baud rate like 115200?

**Comment by jksemple** [comment]
I have the same problem.
I am running in a fresh install of ESP-IDF v5.5.1 with Python v3.11 on Windows 11. My target device is ESP32S3
I have downloaded a coredump from the coredump partition of my device to a file and I'm running esp-coredump as follows:
> esp-coredump info_corefile -c e:\downloads\deviceDC5475D7B0CC_coredump.0.4.5f.bin e:/platformio/projects/coredump/.pio/build/seeed_xiao_esp32s3/firmware.elf
The last line of the output is:
esp_coredump.corefile.ESPCoreDumpError: Couldn't find response with message 'done', type 'result' in responses '[]'

If I change the parameter "info_corefile" to "dbg_corefile" it starts up a GDB debugging session which opens up correctly at the line where the panic occurred and "bt full" shows the stack trace.

This proves there is nothing wrong with the coredump.bin file or the firmware.elf file.

NB GDB reports:
"warning: couild not convert 'main' from the host encoding (CP1252) to UTF-32.
This normally should not happen, please file a bug report."

Not sure if this is relevant to the reported issue or not.

I can supply a coredump.bin and firmware.elf file if you tell me where to send it

**Comment by gerekon** [comment]
@jksemple 
If it is still possible, please, attach coredump.bin and firmware.elf here.

**Comment by jksemple** [comment]
These are not exactly the files I referenced above but they exhibit the same error:

[deviceDC5475D7B0CC_coredump.0.4.6m.zip](https://github.com/user-attachments/files/25878691/deviceDC5475D7B0CC_coredump.0.4.6m.zip)

[0.4.6m-firmware.zip](https://github.com/user-attachments/files/25878698/0.4.6m-firmware.zip)

**Comment by erhankur** [comment]
@jksemple When you download the coredump from the partition manually, it contains a 20 byte header that is not part of the ELF format. After removing the first 20 bytes from the file, you will be able to decode the coredump.
```
espcoredump.py info_corefile -c cd.elf -t elf app.elf                                                                                                                                                                                                                                                               
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3fcf4f34, name: 'JobQueues', GDB name: 'process 1070550836'

================== CURRENT THREAD REGISTERS ===================
exccause       0x1d (StoreProhibitedCause)
excvaddr       0x0
epc1           0x420a05d9
epc2           0x0
epc3           0x0
epc4           0x42165dd2
epc5           0x0
epc6           0x0
eps2           0x0
eps3           0x0
eps4           0x60320
eps5           0x0
eps6           0x0
pc             0x403775f1          0x403775f1 <panic_abort+21>
lbeg           0x40056f08          1074097928
lend           0x40056f12          1074097938
lcount         0x0                 0
sar            0x8                 8
ps             0x60d20             396576
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             0x8037e288          -2143821176
a1             0x3fcaf9d0          1070266832
a2             0x3fcafa54          1070266964
a3             0x1                 1
a4             0xa                 10
a5             0x3fcaf9a0          1070266784
a6             0x60023             393251
a7             0x3                 3
a8             0x0                 0
a9             0x1                 1
a10            0x3fcafa1f          1070266911
a11            0x3fcafa1f          1070266911
a12            0x3fcafa1f          1070266911
a13            0x3fcaf970          1070266736
a14            0x1                 1
a15            0x3fcac580          1070253440

==================== CURRENT THREAD STACK =====================
#0  0x403775f1 in panic_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
#1  0x4037e288 in esp_system_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137
#2  0x40384884 in __assert_func (file=<optimized out>, line=<optimized out>, func=<optimized out>, expr=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/assert.c:85
#3  0x4037eea6 in xQueueGenericSend (xQueue=0x3fcf1cbc, pvItemToQueue=0x0, xTicksToWait=<optimized out>, xCopyPosition=0) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:821
#4  0x4200c789 in Mutex::~Mutex (this=0x3fcafbe8, __in_chrg=<optimized out>) at src/Mutex.h:20
#5  <lambda()>::operator()(void) const (__closure=0x3fcafd6c) at src/EventLogger2.cpp:152
#6  0x4200c8f0 in std::_Function_handler<void(), EventLogger::save()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\\users\\jks.scs\\.platformio\\packages\     oolchain-xtensa-esp32s3\\xtensa-esp32s3-elf\\include\\c++\\8.4.0\\bits/std_function.h:88
#7  0x4200bbb2 in std::function<void()>::operator() (this=0x3fcafd6c) at c:\\users\\jks.scs\\.platformio\\packages\     oolchain-xtensa-esp32s3\\xtensa-esp32s3-elf\\include\\c++\\8.4.0\\bits/std_function.h:687
#8  0x4200bd18 in Mutex::runExclusive (func=..., timeout=0, this=0x3fcafd68) at src/Mutex.h:26
#9  EventLogger::save (this=0x3fca1a90 <Device+328>) at src/EventLogger2.cpp:97
#10 0x42025c85 in <lambda()>::operator() (__closure=0x3fcafe44) at src/StateMgr.cpp:1759
#11 std::_Function_handler<void(), StateMgr::queueEventLoggerSave(int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\\users\\jks.scs\\.platformio\\packages\   oolchain-xtensa-esp32s3\\xtensa-esp32s3-elf\\include\\c++\\8.4.0\\bits/std_function.h:297
#12 0x4200bbb2 in std::function<void()>::operator() (this=0x3fcafe44) at c:\\users\\jks.scs\\.platformio\\packages\     oolchain-xtensa-esp32s3\\xtensa-esp32s3-elf\\include\\c++\\8.4.0\\bits/std_function.h:687
#13 0x4205f191 in JobRunTask (args=0x3fca1cdc <JobRunner>) at .pio/libdeps/debug/JobQueues/src/JobQueues.cpp:117
...
```

**Comment by erhankur** [comment]
@jksemple To refresh our memory, could you please share the output of the command below? It performs the same steps you did manually above (download + decode).
```
idf.py coredump-info -b 115200 -p /dev/tty.usbserial-210 -s cd.elf        
```

**Comment by jksemple** [comment]
When I run that idf.py command I get CMakeLists.txt not found in project directory E:\PlatformIO\Projects\BuzzCopper
My project was not built using ESP-IDF

If I run espcoredump.py I get an error telling me to install esp_coredump.  However, I can run esp_coredump directly.
When I run esp_coredump info_corefile -c cd.elf -t elf app.elf I do not get the output you showed above. I still get the error ending "Couldn't find response with message 'done'
I have edited the coredump file downloaded from flash to remove the first 20 bytes and both those ELF files now start with 0x7F, "ELF" as they should.  What am I doing wrong?

**Comment by erhankur** [comment]
I have created a clean environment and run inside it. Looks still fine to me.
```
python3 -m venv .venv
source .venv/bin/activate
pip install esp_coredump
export PATH=/Users/user/.espressif/tools/xtensa-esp-elf-gdb/16.3_20250913/xtensa-esp-elf-gdb/bin:"${PATH}"
esp-coredump info_corefile -c coredump-elf/cd.elf -t elf coredump-elf/app.elf
```

@peterdragun Is there anything we need to do differently on Windows?

**Comment by jksemple** [comment]
The output from my attempted coredump analysis is:
```
E:\Downloads\Coredump issue>esp-coredump info_corefile -c cd.elf -t elf app.elf
espcoredump.py v1.14.0
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3fcf4f34, name: '', GDB name: 'process 1070550836'

================== CURRENT THREAD REGISTERS ===================
exccause       0x1d (StoreProhibitedCause)
excvaddr       0x0
epc1           0x420a05d9
epc2           0x0
epc3           0x0
epc4           0x42165dd2
epc5           0x0
epc6           0x0
eps2           0x0
eps3           0x0
eps4           0x60320
eps5           0x0
eps6           0x0


==================== CURRENT THREAD STACK =====================


======================== THREADS INFO =========================

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Scripts\esp-coredump.exe\__main__.py", line 6, in <module>
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Lib\site-packages\esp_coredump\__main__.py", line 41, in main
    temp_core_files = espcoredump.info_corefile()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Lib\site-packages\esp_coredump\coredump.py", line 587, in info_corefile
    self.print_threads_info(task_info)
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Lib\site-packages\esp_coredump\coredump.py", line 349, in print_threads_info
    threads, _ = self.gdb_esp.get_thread_info(attempt * DEFAULT_GDB_TIMEOUT_SEC)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Lib\site-packages\esp_coredump\corefile\gdb.py", line 131, in get_thread_info
    result = self._gdbmi_run_cmd_get_one_response('-thread-info', 'done', 'result', response_delay_sec=response_delay_sec)['payload']
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Lib\site-packages\esp_coredump\corefile\gdb.py", line 80, in _gdbmi_run_cmd_get_one_response
    return self._gdbmi_run_cmd_get_responses(cmd, resp_message, resp_type, response_delay_sec=response_delay_sec,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Espressif\python_env\idf5.5_py3.11_env\Lib\site-packages\esp_coredump\corefile\gdb.py", line 73, in _gdbmi_run_cmd_get_responses
    raise ESPCoreDumpError("Couldn't find response with message '{}', type '{}' in responses '{}'".format(
esp_coredump.corefile.ESPCoreDumpError: Couldn't find response with message 'done', type 'result' in responses '[]'
```

So I would guess it is unable to read some part of the app.elf file

However, when run with the dbg_corefile parameter it does manage to decode symbol names and print out the stack trace with 'bt full'.  However, it takes several seconds after printing 'Reading symbols from app.elf' before it shows further output

**Comment by erhankur** [comment]
Could you please try to increase gdb timeout, for example to 100 seconds?
```
esp-coredump --gdb-timeout-sec 100 info_corefile -c coredump-elf/cd.elf -t elf coredump-elf/app.elf
```

**Comment by jksemple** [comment]
Well done. That's fixed it!
```
E:\Downloads\Coredump issue>esp-coredump --gdb-timeout 100 info_corefile -c cd.elf -t elf app.elf
espcoredump.py v1.14.0
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3fcf4f34, name: 'JobQueues', GDB name: 'process 1070550836'

================== CURRENT THREAD REGISTERS ===================
exccause       0x1d (StoreProhibitedCause)
excvaddr       0x0
epc1           0x420a05d9
epc2           0x0
epc3           0x0
epc4           0x42165dd2
epc5           0x0
epc6           0x0
eps2           0x0
eps3           0x0
eps4           0x60320
eps5           0x0
eps6           0x0
pc             0x403775f1          0x403775f1 <panic_abort+21>
lbeg           0x40056f08          1074097928
lend           0x40056f12          1074097938
lcount         0x0                 0
sar            0x8                 8
ps             0x60d20             396576
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             0x8037e288          -2143821176
a1             0x3fcaf9d0          1070266832
a2             0x3fcafa54          1070266964
a3             0x1                 1
a4             0xa                 10
a5             0x3fcaf9a0          1070266784
a6             0x60023             393251
a7             0x3                 3
a8             0x0                 0
a9             0x1                 1
a10            0x3fcafa1f          1070266911
a11            0x3fcafa1f          1070266911
a12            0x3fcafa1f          1070266911
a13            0x3fcaf970          1070266736
a14            0x1                 1
a15            0x3fcac580          1070253440

==================== CURRENT THREAD STACK =====================
#0  0x403775f1 in panic_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
#1  0x4037e288 in esp_system_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137
#2  0x40384884 in __assert_func (file=<optimized out>, line=<optimized out>, func=<optimized out>, expr=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/assert.c:85
#3  0x4037eea6 in xQueueGenericSend (xQueue=0x3fcf1cbc, pvItemToQueue=0x0, xTicksToWait=<optimized out>, xCopyPosition=0) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:821
#4  0x4200c789 in Mutex::~Mutex (this=0x3fcafbe8, __in_chrg=<optimized out>) at src/Mutex.h:20
#5  <lambda()>::operator()(void) const (__closure=0x3fcafd6c) at src/EventLogger2.cpp:152
#6  0x4200c8f0 in std::_Function_handler<void(), EventLogger::save()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:88
#7  0x4200bbb2 in std::function<void()>::operator() (this=0x3fcafd6c) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#8  0x4200bd18 in Mutex::runExclusive (func=..., timeout=0, this=0x3fcafd68) at src/Mutex.h:26
#9  EventLogger::save (this=0x3fca1a90 <Device+328>) at src/EventLogger2.cpp:97
#10 0x42025c85 in <lambda()>::operator() (__closure=0x3fcafe44) at src/StateMgr.cpp:1759
#11 std::_Function_handler<void(), StateMgr::queueEventLoggerSave(int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\users\jks.scs\.platformio\packages        oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
#12 0x4200bbb2 in std::function<void()>::operator() (this=0x3fcafe44) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#13 0x4205f191 in JobRunTask (args=0x3fca1cdc <JobRunner>) at .pio/libdeps/debug/JobQueues/src/JobQueues.cpp:117

======================== THREADS INFO =========================
  Id   Target Id          Frame
* 1    process 1070550836 0x403775f1 in panic_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
  2    process 1070318872 0x420978fd in uart_ll_is_tx_idle (hw=0x60000000) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/hal/esp32s3/include/hal/uart_ll.h:779
  3    process 1070514888 0x420978fa in uart_ll_is_tx_idle (hw=0x60000000) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/hal/esp32s3/include/hal/uart_ll.h:779
  4    process 1070555700 0x42165dd2 in esp_pm_impl_waiti () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855
  5    process 1070557100 0x42165dd2 in esp_pm_impl_waiti () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855
  6    process 1070310332 0x4037f35a in vPortEnterCritical (mux=0x3fcb9714) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
  7    process 1070287052 0x4202023d in LedFlashTask (args=0x3fcb41c8) at src/LedFlasher.cpp:32
  8    process 1070534980 0x4037f4bc in vPortEnterCritical (mux=0x3fcf0d1c) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
  9    process 1070397024 0x4037f35a in vPortEnterCritical (mux=0x3fcd0170) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
  10   process 1070562416 0x4037f35a in vPortEnterCritical (mux=0x3fcf7320) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
  11   process 1070314400 0x4037f35a in vPortEnterCritical (mux=0x3fcba714) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
  12   process 1070536680 0x4037f4ba in vPortEnterCritical (mux=0x3fcf13c0) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
  13   process 1070548504 0x400559e0 in ?? ()
  14   process 1070331312 0x4037f35a in vPortEnterCritical (mux=0x3fcbd4e4) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578


       TCB             NAME PRIO C/B  STACK USED/FREE
---------- ---------------- -------- ----------------
0x3fcf4f34        JobQueues      1/1       1520/13464
0x3fcbc518   arduino_events    19/19        2064/2024
0x3fcec2c8         loopTask      1/1        1648/6536
0x3fcf6234            IDLE0      0/0          608/412
0x3fcf67ac            IDLE1      0/0          608/404
0x3fcba3bc              tiT    18/18         672/2388
0x3fcb48cc     LedFlashTask      1/1          560/656
0x3fcf1144             ipc0    24/24          608/412
0x3fccf660        async_tcp      3/3        624/15756
0x3fcf7c70         cam_task    23/23         656/1376
0x3fcbb3a0          sys_evt    20/20         688/1856
0x3fcf17e8             ipc1    24/24          608/408
0x3fcf4618        esp_timer    22/22         640/3960
0x3fcbf5b0             wifi    23/23         656/5984

==================== THREAD 1 (TCB: 0x3fcf4f34, name: 'JobQueues') =====================
#0  0x403775f1 in panic_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
#1  0x4037e288 in esp_system_abort (details=0x3fcafa54 "assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137
#2  0x40384884 in __assert_func (file=<optimized out>, line=<optimized out>, func=<optimized out>, expr=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/assert.c:85
#3  0x4037eea6 in xQueueGenericSend (xQueue=0x3fcf1cbc, pvItemToQueue=0x0, xTicksToWait=<optimized out>, xCopyPosition=0) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:821
#4  0x4200c789 in Mutex::~Mutex (this=0x3fcafbe8, __in_chrg=<optimized out>) at src/Mutex.h:20
#5  <lambda()>::operator()(void) const (__closure=0x3fcafd6c) at src/EventLogger2.cpp:152
#6  0x4200c8f0 in std::_Function_handler<void(), EventLogger::save()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:88
#7  0x4200bbb2 in std::function<void()>::operator() (this=0x3fcafd6c) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#8  0x4200bd18 in Mutex::runExclusive (func=..., timeout=0, this=0x3fcafd68) at src/Mutex.h:26
#9  EventLogger::save (this=0x3fca1a90 <Device+328>) at src/EventLogger2.cpp:97
#10 0x42025c85 in <lambda()>::operator() (__closure=0x3fcafe44) at src/StateMgr.cpp:1759
#11 std::_Function_handler<void(), StateMgr::queueEventLoggerSave(int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\users\jks.scs\.platformio\packages        oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
#12 0x4200bbb2 in std::function<void()>::operator() (this=0x3fcafe44) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#13 0x4205f191 in JobRunTask (args=0x3fca1cdc <JobRunner>) at .pio/libdeps/debug/JobQueues/src/JobQueues.cpp:117

==================== THREAD 2 (TCB: 0x3fcbc518, name: 'arduino_events') =====================
#0  0x420978fd in uart_ll_is_tx_idle (hw=0x60000000) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/hal/esp32s3/include/hal/uart_ll.h:779
#1  log_printfv (format=<optimized out>, arg=...) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-uart.c:851
#2  0x420ce108 in __wrap_log_printf (format=0x3c1729dc "[%6u][I][%s:%u] %s(): Saved event %d\r
") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/esp-rainmaker/components/esp-insights/components/esp_diagnostics/src/esp_diagnostics_log_hook.c:426
#3  0x4200ccbe in <lambda()>::operator() (__closure=0xfffffffc) at src/EventLogger2.cpp:56
#4  std::_Function_handler<void(), EventLogger::log(char const*, char const*, ...)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:\users\jks.scs\.platformio\packages    oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
#5  0x4200bbb2 in std::function<void()>::operator() (this=0x3fcbbf1c) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#6  0x4200bf45 in event_t::~event_t (this=0x3fcbbf08, __in_chrg=<optimized out>) at src/EventLogger2.h:20
#7  EventLogger::log (this=<optimized out>, eventType=0x3c1763f8 "WiFi", format=<optimized out>) at src/EventLogger2.cpp:51
#8  0x42048427 in wiFiLoggingCallback (logMessage=...) at src/main.cpp:309
#9  0x420484c9 in std::_Function_handler<void(String), void (*)(String)>::_M_invoke (__functor=..., __args#0=...) at c:\users\jks.scs\.platformio\packages      oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
#10 0x4203f3cc in std::function<void(String)>::operator() (this=0x3fca18b0 <WiFiMgr+160>, __args#0=...) at c:\users\jks.scs\.platformio\packages        oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#11 0x4203f401 in WiFiMgr2Class::log (this=0x3fca1810 <WiFiMgr>, logMessage=...) at src/WiFiMgr2.cpp:67
#12 0x4203f4c4 in <lambda(arduino_event_id_t, arduino_event_info_t)>::operator() (info=..., event=<optimized out>, __closure=<optimized out>) at src/WiFiMgr2.cpp:36
#13 std::_Function_handler<void(arduino_event_id_t, arduino_event_info_t), <lambda(arduino_event_id_t, arduino_event_info_t)> >::_M_invoke(const std::_Any_data &, arduino_event_id_t &&, arduino_event_info_t &&) (__functor=..., __args#0=@0x3fcbc1dc: ARDUINO_EVENT_WIFI_STA_DISCONNECTED, __args#1=...) at c:\users\jks.scs\.platformio\packages    oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
#14 0x420570f5 in std::function<void(arduino_event_id_t, arduino_event_info_t)>::operator() (this=0x3fcbc354, __args#0=<optimized out>, __args#1=...) at c:\users\jks.scs\.platformio\packages  oolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687
#15 0x420574e0 in WiFiGenericClass::_eventCallback (event=0x3fccf93c) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.cpp:1168
#16 0x42057530 in _arduino_event_task (arg=0x0) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.cpp:306

==================== THREAD 3 (TCB: 0x3fcec2c8, name: 'loopTask') =====================
#0  0x420978fa in uart_ll_is_tx_idle (hw=0x60000000) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/hal/esp32s3/include/hal/uart_ll.h:779
#1  log_printfv (format=<optimized out>, arg=...) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-uart.c:851
#2  0x420ce108 in __wrap_log_printf (format=0x3c1738c8 "[%6u][I][%s:%u] %s(): Token info: type = %s, status = %s\r
") at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/esp-rainmaker/components/esp-insights/components/esp_diagnostics/src/esp_diagnostics_log_hook.c:426
#3  0x42019d74 in tokenStatusCallback (info=...) at src/GCSAgent.cpp:690
#4  0x4206eece in GAuth_OAuth2_Client::sendTokenStatusCB (this=0x3fca1178 <g_GCSAgent+4>) at lib/ESP-Signer/src/auth/GAuth_OAuth2_Client.cpp:714
#5  0x420728ca in GAuth_OAuth2_Client::createJWT (this=0x3fca1178 <g_GCSAgent+4>) at lib/ESP-Signer/src/auth/GAuth_OAuth2_Client.cpp:822
#6  0x42073a5c in GAuth_OAuth2_Client::tokenProcessingTask (this=0x3fca1178 <g_GCSAgent+4>) at lib/ESP-Signer/src/auth/GAuth_OAuth2_Client.cpp:514
#7  0x42073b15 in GAuth_OAuth2_Client::handleToken (this=0x3fca1178 <g_GCSAgent+4>) at lib/ESP-Signer/src/auth/GAuth_OAuth2_Client.cpp:399
#8  0x42073bd1 in GAuth_OAuth2_Client::checkToken (this=0x3fca1178 <g_GCSAgent+4>) at lib/ESP-Signer/src/auth/GAuth_OAuth2_Client.cpp:1138
#9  0x42073be3 in GAuth_OAuth2_Client::tokenReady (this=0x3fca1178 <g_GCSAgent+4>) at lib/ESP-Signer/src/auth/GAuth_OAuth2_Client.cpp:1146
#10 0x4206c844 in ESP_Signer::tokenReady (this=0x3fca1174 <g_GCSAgent>) at lib/ESP-Signer/src/ESP_Signer.cpp:91
#11 0x4201cb47 in GCSAgent::getToken (this=0x3fca1174 <g_GCSAgent>) at src/GCSAgent.cpp:70
#12 0x42028a80 in onTimeSyncedUpdate () at src/StateMgr.cpp:463
#13 0x4205f654 in Fsm::run_machine (this=0x3fca14e0 <g_StateMgr>) at .pio/libdeps/debug/arduino-fsm/Fsm.cpp:145
#14 0x4202a1b1 in StateMgr::update (this=0x3fca14e0 <g_StateMgr>) at src/StateMgr.cpp:910
#15 0x42048d89 in loop () at src/main.cpp:250
#16 0x42097a80 in loopTask (pvParameters=<optimized out>) at C:/Users/jks.SCS/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:50

==================== THREAD 4 (TCB: 0x3fcf6234, name: 'IDLE0') =====================
#0  0x42165dd2 in esp_pm_impl_waiti () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855
#1  0x420a0dcc in esp_vApplicationIdleHook () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/freertos_hooks.c:63
#2  0x4037f983 in prvIdleTask (pvParameters=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:4099

==================== THREAD 5 (TCB: 0x3fcf67ac, name: 'IDLE1') =====================
#0  0x42165dd2 in esp_pm_impl_waiti () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855
#1  0x420a0dcc in esp_vApplicationIdleHook () at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/freertos_hooks.c:63
#2  0x4037f983 in prvIdleTask (pvParameters=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:4099

==================== THREAD 6 (TCB: 0x3fcba3bc, name: 'tiT') =====================
#0  0x4037f35a in vPortEnterCritical (mux=0x3fcb9714) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueReceive (xQueue=0x3fcb96c8, pvBuffer=0x3fcba23c, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1400
#2  0x420bca56 in sys_arch_mbox_fetch (mbox=<optimized out>, msg=0x3fcba23c, timeout=74) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/port/esp32/freertos/sys_arch.c:330
#3  0x420ae102 in tcpip_timeouts_mbox_fetch (mbox=<optimized out>, msg=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c:110
#4  tcpip_thread (arg=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c:148

==================== THREAD 7 (TCB: 0x3fcb48cc, name: 'LedFlashTask') =====================
#0  0x4202023d in LedFlashTask (args=0x3fcb41c8) at src/LedFlasher.cpp:32

==================== THREAD 8 (TCB: 0x3fcf1144, name: 'ipc0') =====================
#0  0x4037f4bc in vPortEnterCritical (mux=0x3fcf0d1c) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueSemaphoreTake (xQueue=0x3fcf0cd0, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1563
#2  0x40379ee7 in ipc_task (arg=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_ipc/src/esp_ipc.c:54

==================== THREAD 9 (TCB: 0x3fccf660, name: 'async_tcp') =====================
#0  0x4037f35a in vPortEnterCritical (mux=0x3fcd0170) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueReceive (xQueue=0x3fcd0124, pvBuffer=0x3fcc8a9c, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1400
#2  0x4213fa87 in _get_async_event (e=<unavailable>) at .pio/libdeps/debug/AsyncTCP@1.1.1/src/AsyncTCP.cpp:115
#3  _async_service_task (pvParameters=<optimized out>) at .pio/libdeps/debug/AsyncTCP@1.1.1/src/AsyncTCP.cpp:188

==================== THREAD 10 (TCB: 0x3fcf7c70, name: 'cam_task') =====================
#0  0x4037f35a in vPortEnterCritical (mux=0x3fcf7320) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueReceive (xQueue=0x3fcf72d4, pvBuffer=0x3fcf7ae4, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1400
#2  0x420d0208 in cam_task (arg=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/esp32-camera/driver/cam_hal.c:125

==================== THREAD 11 (TCB: 0x3fcbb3a0, name: 'sys_evt') =====================
#0  0x4037f35a in vPortEnterCritical (mux=0x3fcba714) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueReceive (xQueue=0x3fcba6c8, pvBuffer=0x3fcbb1e0, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1400
#2  0x4216cc29 in esp_event_loop_run (event_loop=0x3fcba6a0, ticks_to_run=4294967295) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_event/esp_event.c:566
#3  0x4216cda7 in esp_event_loop_run_task (args=0x3fcba6a0) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_event/esp_event.c:115

==================== THREAD 12 (TCB: 0x3fcf17e8, name: 'ipc1') =====================
#0  0x4037f4ba in vPortEnterCritical (mux=0x3fcf13c0) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueSemaphoreTake (xQueue=0x3fcf1374, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1563
#2  0x40379ee7 in ipc_task (arg=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_ipc/src/esp_ipc.c:54

==================== THREAD 13 (TCB: 0x3fcf4618, name: 'esp_timer') =====================
#0  0x400559e0 in ?? ()
#1  0x403816ad in vPortClearInterruptMaskFromISR (prev_level=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:571
#2  vPortExitCritical (mux=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/port.c:332
#3  0x40380f49 in ulTaskGenericNotifyTake (uxIndexToWait=<optimized out>, xClearCountOnExit=1, xTicksToWait=4294967295) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:5513
#4  0x420c10c5 in timer_task (arg=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_timer/src/esp_timer.c:420

==================== THREAD 14 (TCB: 0x3fcbf5b0, name: 'wifi') =====================
#0  0x4037f35a in vPortEnterCritical (mux=0x3fcbd4e4) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578
#1  xQueueReceive (xQueue=0x3fcbd498, pvBuffer=0x3fcbf420, xTicksToWait=<optimized out>) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1400
#2  0x420abd40 in queue_recv_wrapper (queue=0x3fcbd498, item=0x3fcbf420, block_time_tick=4294967295) at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_wifi/esp32s3/esp_adapter.c:424
#3  0x4216a6c8 in ppTask ()


======================= ALL MEMORY REGIONS ========================
Name   Address   Size   Attrs
.rtc.text 0x600fe000 0x21 R XA
.rtc.force_fast 0x600fe024 0x8 RW A
.rtc.force_slow 0x50000028 0x0 RW
.iram0.vectors 0x40374000 0x403 R XA
.iram0.text 0x40374404 0x124f7 R XA
.dram0.data 0x3fc96900 0x7808 RW A
.noinit 0x3fc9e108 0x0 RW
.flash.text 0x42000020 0x16e3c7 R XA
.rtc.entry.literal 0x4216e3e8 0x0 R XA
.flash.appdesc 0x3c170020 0x100 R  A
.flash.rodata 0x3c170120 0x72838 RW A
.iram0.text_end 0x403868fb 0x0 RW
.iram0.bss 0x403868fc 0x0 RW
.dram0.heap_start 0x3fcac110 0x0 RW
.coredump.tasks.data 0x3fcbc518 0x158 RW
.coredump.tasks.data 0x3fcbbcf0 0x810 RW
.coredump.tasks.data 0x3fcec2c8 0x158 RW
.coredump.tasks.data 0x3fcebc40 0x670 RW
.coredump.tasks.data 0x3fcf4f34 0x158 RW
.coredump.tasks.data 0x3fcaf910 0x6e0 RW
.coredump.tasks.data 0x3fcf6234 0x158 RW
.coredump.tasks.data 0x3fcf5fc0 0x260 RW
.coredump.tasks.data 0x3fcf67ac 0x158 RW
.coredump.tasks.data 0x3fcf6530 0x260 RW
.coredump.tasks.data 0x3fcba3bc 0x158 RW
.coredump.tasks.data 0x3fcba100 0x2a0 RW
.coredump.tasks.data 0x3fcb48cc 0x158 RW
.coredump.tasks.data 0x3fcb4680 0x230 RW
.coredump.tasks.data 0x3fcf1144 0x158 RW
.coredump.tasks.data 0x3fcf0ed0 0x260 RW
.coredump.tasks.data 0x3fccf660 0x158 RW
.coredump.tasks.data 0x3fcc8990 0x270 RW
.coredump.tasks.data 0x3fcf7c70 0x158 RW
.coredump.tasks.data 0x3fcf79c0 0x290 RW
.coredump.tasks.data 0x3fcbb3a0 0x158 RW
.coredump.tasks.data 0x3fcbb0d0 0x2b0 RW
.coredump.tasks.data 0x3fcf17e8 0x158 RW
.coredump.tasks.data 0x3fcf1570 0x260 RW
.coredump.tasks.data 0x3fcf4618 0x158 RW
.coredump.tasks.data 0x3fcf4380 0x280 RW
.coredump.tasks.data 0x3fcbf5b0 0x158 RW
.coredump.tasks.data 0x3fcbf300 0x290 RW

===================== ESP32 CORE DUMP END =====================
===============================================================
Done!
```

**Comment by erhankur** [comment]
Glad to hear it helped. Feel free to reopen this if you run into another issue.
